### ISSUE TITLE
`onSpecUpdate` not firing

### ISSUE THREAD

**Issue by baughmann** [scalar/scalar#1021]
### What happens?

`onSpecUpdate` callback does not appear to fire when the spec changes. I am using Scalar via Elysia ([linked issue](https://github.com/elysiajs/elysia/issues/491))

### What did you expect to happen?

I expected to see `Writing spec to file` in the stdout any time I update an endpoint.

### How can we reproduce the issue?

Simply use this script in `index.ts` and `bun run dev`:

```ts
import { Elysia, t } from "elysia";
import { swagger } from "@elysiajs/swagger";
import fs from "fs";

const app = new Elysia()
  .use(swagger({
    scalarConfig: {
      onSpecUpdate: (spec) => {
        // write the spec to a file
        console.log("Writing spec to file");
        fs.writeFileSync("./spec.json", JSON.stringify(spec, null, 2));
      },
    }
  }))
  .get("/api/:id", () => "Hello Elysia", {
    query: t.Object(
      {
        name: t.String(),
      },
      {
        description: "Query parameter",
      }
    ),
    params: t.Object(
      {
        id: t.String(),
      },
      {
        description: "Path parameter",
      }
    ),
    response: {
      
    },
    detail: {
      summary: "Get Hello Elysia",
      description: "Get Hello Elysia",
      tags: ["Hello Elysia"],
      security: [],
    },
  })
  .listen(3000);

console.log(
  `🦊 Elysia is running at ${app.server?.hostname}:${app.server?.port}`
);
```

**Comment by hanspagel** [comment]
Oops! Thanks for reporting, I’ll fix this.

**Comment by jusbuc2k** [comment]
It seems like this feature was lost again? I don't see anywhere in the codebase where this callback is called:


https://github.com/search?q=repo%3Ascalar%2Fscalar%20onSpecUpdate%20&type=code
