### ISSUE TITLE
Basic Authentication displays Og=='

### ISSUE THREAD

**Issue by hbcondo** [scalar/scalar#1026]
### What happens?

When specifying Basic Authentication as a security schema in an OpenAPI spec, the string `Og=='` is displayed in the rendered code box and _Test Request_ dialog:

![image](https://github.com/scalar/scalar/assets/306958/935995c7-9b3e-4af5-9acf-759d19c21fa3)
![image](https://github.com/scalar/scalar/assets/306958/fc072525-72d8-4ea2-9968-05e2368e4287)

### What did you expect to happen?

The string `Og=='` is a base64-encoding of the colon character :
It should not be rendered but `Authorization: Basic` should still appear

### How can we reproduce the issue?

Include a basicAuth securitySchemes in the openapi spec, for example:

```cli
openapi: 3.0.0
info:
  title: HTTPS + Basic auth example
  version: 1.0.0

servers:
  - url: https://httpbin.org

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: Use `user` / `passwd` as the test credentials

paths:
  /basic-auth/user/passwd:
    get:
      security:
        - basicAuth: []
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized. The username or password provided is incorrect.
```

### Swagger/OpenAPI Example

https://sandbox.scalar.com/e/snZUC

**Comment by marclave** [comment]
thanks for reporting this @hbcondo ! 

we will fix this ✨
