### ISSUE TITLE
Parameterized Server Protocol Generates Faulty URL

### ISSUE THREAD

**Issue by bigmike36c** [scalar/scalar#1035]
### What happens?

I believe the [PR](https://github.com/scalar/scalar/pull/990) tied to this [issue](https://github.com/scalar/scalar/issues/937) resulted in a regression for when the protocol itself is parameterized in the openAPI specification. 

For example, here is the servers property in our openAPI spec:
![image](https://github.com/scalar/scalar/assets/81941044/9feb235f-23c2-41e8-955d-fe0ecefbb67a)

This results in Scalar generating broken URLs such as `http://127.0.0.1:3000/https://localhost:8083/management/v2/environments/{envId}/apis` as shown below:
<img width="1103" alt="Screenshot 2024-02-22 at 9 49 45 AM" src="https://github.com/scalar/scalar/assets/81941044/d524124e-3a67-43b9-8db9-708e0e26589b">

### What did you expect to happen?

Scalar should use the full URL provided in the spec and not treat it as a path that gets appended to the window origin.

### How can we reproduce the issue?

Use the following OpenAPI Specification with Scalar:

```
{
  "openapi": "3.0.3",
  "info": {
    "title": "Debug",
    "description": "Debugging",
    "version": "2.0.0"
  },
  "security": [
    { "BasicAuth": [] },
    { "CookieAuth": [] }
  ],
  "paths": {
    "/management/v2/example": {
      "get": {
        "summary": "Example endpoint",
        "description": "Returns a simple example",
        "security": [
          { "BasicAuth": [] },
          { "CookieAuth": [] }
        ],
        "responses": {
          "200": {
            "description": "A successful response"
          }
        }
      }
    }
  },
  "servers": [
    {
      "url": "{protocol}://{managementAPIHost}/management/v2",
      "description": "APIM Management API v2 - Default base URL",
      "variables": {
        "protocol": {
          "description": "The protocol you want to use to communicate with the mAPI",
          "default": "https",
          "enum": [
            "https",
            "http"
          ]
        },
        "managementAPIHost": {
          "description": "The domain of the server hosting your Management API",
          "default": "localhost:8083"
        }
      }
    }
  ]
}
```

### Swagger/OpenAPI Example

https://sandbox.scalar.com/e/PPank

**Comment by hanspagel** [comment]
Oh, good find! Let me come up with a better fix.

**Comment by lirc571** [comment]
Hi, I still see the same issue in the latest release. When using the example spec above in <https://docs.scalar.com/swagger-editor>, the server URL is prepended with `https://docs.scalar.com/` (e.g. `https://docs.scalar.com/https://localhost:8083/management/v2`)
