### ISSUE TITLE
Icons aren't loading properly in the latest release using CDN (1.17.12) 

### ISSUE THREAD

**Issue by mouhannad-sh** [scalar/scalar#1093]
### What happens?

<img width="1128" alt="image" src="https://github.com/scalar/scalar/assets/18495740/6b911b29-cce7-47f1-860b-e8c71017fe77">
<img width="1120" alt="image" src="https://github.com/scalar/scalar/assets/18495740/4d2fc4dc-dd6b-4a63-8202-7695948e0eae">

### What did you expect to happen?

The icons should look normal sized

### How can we reproduce the issue?

[codesandbox](https://codesandbox.io/p/sandbox/focused-voice-kmvsf9?file=%2Findex.html%3A14%2C21&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clt83k6kl00063b6h0eo44p4p%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clt83k6kk00023b6h55l5int2%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clt83k6kk00033b6hxdgln34p%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clt83k6kk00053b6hl4s9amh6%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clt83k6kk00023b6h55l5int2%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clt83k6kk00013b6hrcg8riqj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A14%252C%2522startColumn%2522%253A21%252C%2522endLineNumber%2522%253A14%252C%2522endColumn%2522%253A21%257D%255D%257D%255D%252C%2522id%2522%253A%2522clt83k6kk00023b6h55l5int2%2522%252C%2522activeTabId%2522%253A%2522clt83k6kk00013b6hrcg8riqj%2522%257D%252C%2522clt83k6kk00053b6hl4s9amh6%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clt83k6kk00043b6h1ebldu5w%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clt83k6kk00053b6hl4s9amh6%2522%252C%2522activeTabId%2522%253A%2522clt83k6kk00043b6h1ebldu5w%2522%257D%252C%2522clt83k6kk00033b6hxdgln34p%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clt83k6kk00033b6hxdgln34p%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Afalse%252C%2522sidebarPanelSize%2522%253A0%257D)

**Comment by hanspagel** [comment]
Thanks for reporting! Damn, this was my mistake. I [introduced the regression](https://github.com/scalar/scalar/pull/1079), saw it and [thought I fixed it](https://github.com/scalar/scalar/pull/1089), but I didn’t. Thankfully @cameronrohani and @marclave [fixed it swiftly](https://github.com/scalar/scalar/pull/1094) and [released it quickly](https://github.com/scalar/scalar/pull/1092). 🙏
