### ISSUE TITLE
visual regression testing

### ISSUE THREAD

**Issue by hanspagel** [scalar/scalar#1122]
We need to somehow make sure we don't break the CDN (and all other packages) on release.

Should we add visual regression testing?

Related:

* https://github.com/scalar/scalar/pull/1095
* https://github.com/scalar/scalar/pull/1095#issuecomment-1974158325

**Comment by hwkr** [comment]
I would be down, I've used \[Chromatic\]([https://www.chromatic.com/](https://www.chromatic.com/)) before but maybe theres better options?

**Comment by tmastrom** [comment]
@hwkr it looks like Chromatic has a Playwright integration! We have Playwright set up to test the CDN here https://github.com/scalar/scalar/blob/main/tests/cdn.spec.ts so this could be an easy one 🤞
