### ISSUE TITLE
Docusarus bug when not using Typescript

### ISSUE THREAD

**Issue by tjperry07** [scalar/scalar#1138]
### What happens?

When running my sit, after npm start. I get the following error:

```

Module not found: Error: Can't resolve '/Users/tatiana/Documents/my-website/node_modules/@scalar/docusaurus/dist/ScalarDocusaurus' in '/Users/tatiana/Documents/my-website/.docusaurus'

--------------------------

Module not found: Error: Can't resolve '/Users/tatiana/Documents/my-website/node_modules/@scalar/docusaurus/dist/ScalarDocusaurus' in '/Users/tatiana/Documents/my-website/.docusaurus'
client (webpack 5.90.3) compiled with 2 errors
```

### What did you expect to happen?

For the site to start and for the plugin to load

### How can we reproduce the issue?

I am not using typescript. In a `docusaurus.config.js` add the following, then npm start.

```
  plugins: [
    [
      '@scalar/docusaurus',
      {
        label: 'Scalar',
        route: '/scalar',
        configuration: {
          spec: {
            url: 'https://petstore3.swagger.io/api/v3/openapi.json',
          },
        },
      }
    ],
  ],
  ```

### Swagger/OpenAPI Example

https://petstore3.swagger.io/api/v3/openapi.json

**Comment by amritk** [comment]
hey @tjperry07 do you think you could put up a minimum reproduction repository? I'm not too familiar with docusaurus so I'm not sure how yours would be setup.

**Comment by amritk** [comment]
Thanks for the repo @tjperry07, fix is in PR

https://github.com/scalar/scalar/pull/1139
