### ISSUE TITLE
Enable/disable property toggle is not intuitive and leads to silly user mistakes.

### ISSUE THREAD

**Issue by arthurfiorette** [scalar/scalar#1145]
### What happens?

When a query or header is declared optional, its checkbox is not marked by default:

![image](https://github.com/scalar/scalar/assets/47537704/84972b9b-d0c0-46d7-874d-1830aa91c01e)

Its not intuitive to the end user that the "square box" after the input is a checkbox that should be marked if he wants to sent the data he have just written.

![image](https://github.com/scalar/scalar/assets/47537704/1ae56efe-2a0c-4d56-98f3-b6017a141f7e)

I've received a lot of user complaints that they expected the data they've written to be sent to the API.

Properties with default values aren't checked by default and shouldn't. Only if the user edits the value it should enable it.

![image](https://github.com/scalar/scalar/assets/47537704/5ec04f40-df3e-4eed-be9b-afdcbacd93cc)

(edits it) ->

![image](https://github.com/scalar/scalar/assets/47537704/73cdda66-77ae-4989-9460-371db6cce53f)

### What did you expect to happen?

Just simply checking a default non-checked field when the user inputs something into it, would drastically improve UX and avoid these silly mistakes.

---

Example:

UI starts in this way:

![image](https://github.com/scalar/scalar/assets/47537704/84972b9b-d0c0-46d7-874d-1830aa91c01e)

Simply by typing something into the input, the checkbox should be marked automatically.

![image](https://github.com/scalar/scalar/assets/47537704/b59fb372-672b-49e1-9d0d-05c39408ac42)

The checkbox could later be disabled/enabled manually by the user.

### How can we reproduce the issue?

Just create a route with a query param as optional. Even after writing something into it, the checkbox won't be marked.

**Comment by marclave** [comment]
i love this idea @arthurfiorette !

really appreciate the thorough ticket as well.

let's add this @cameronrohani @hanspagel 

im thinking if a user types in a default disabled property, we enable it but then after a user disables it again we dont automatically toggle it again :) so just for the first time ✨ thoughts @cameronrohani @hanspagel @arthurfiorette ?

**Comment by arthurfiorette** [comment]
awesome!
