### ISSUE TITLE
Response schema not scrollable when rendering with Vue

### ISSUE THREAD

**Issue by johannesspohr** [scalar/scalar#1164]
### What happens?

I might be missing something here, but I can not get it to work. I copied the `web` folder from examples to run it outside of the workspace and replaced all import magic with the regular packages from npm, and when I run it then the response area is not scrollable anymore. It works fine when using in the context of the project though.
![image](https://github.com/scalar/scalar/assets/1831098/35e5c53e-e7bb-4c90-a9c5-d8164d525b80)

### What did you expect to happen?

The response schema should be scrollable and always show the bottom bar.

### How can we reproduce the issue?

1. Copy web folder to new folder
2. Remove import alias from vite config
3. Remove all `workspace:*` dependencies from the package.json
4. Run `pnpm install @scalar/api-reference @scalar/api-client @scalar/swagger-editor @scalar/swagger-parser @scalar/themes`
5. Run `pnpm run dev`
6. Navigate to any example and adjust window size so the area should be scrollable.

**Comment by marclave** [comment]
@johannesspohr thanks for reporting this ✨ looking into this right now

**Comment by johannesspohr** [comment]
Thank you! I tried again today in my project and it seemed like with the new version the problem is gone.

**Comment by marclave** [comment]
amazing! :)
