### ISSUE TITLE
Make the URL editable for friendly UX 

### ISSUE THREAD

**Issue by basheer-taplane** [scalar/scalar#1189]
### What happens?

The URL is not editable and requires to replace a variable through **VARIABLES** section. However, this is user friendly and possibly will make things worse. Please see the attached screen

![image](https://github.com/scalar/scalar/assets/138797071/7117d93d-f5b1-4120-888d-f16fbd7af00d)

### What did you expect to happen?

The Address bar or the URL should be editable to make the changes

### How can we reproduce the issue?

- Provide a URL with any OpenApi spec encapsulating a variable and try to edit or update it through Address bar.

The issue was already confirmed on the discord channel by the author

https://discord.com/channels/1135330207960678410/1180602650476154950/1217598466457604370

**Comment by hanspagel** [comment]
Oh, I understand where you’re coming from. I never considered this. I think it’s a little bit more complex than it seems, let me think about it. But I’d say we should make the URL indeed editable, as you suggested. :v:

**Comment by Amorim33** [comment]
Hmm interesting suggestion, @hanspagel may I try to tackle this?

**Comment by marclave** [comment]
@Amorim33 @hanspagel we should be able to add another configuration object and pass the prop directly down to the apiclient config which actually has a editable prop already :)

**Comment by hanspagel** [comment]
The URL is editable, but I don’t write to the request state, so it doesn’t have any effect on the actual request :D
