### ISSUE TITLE
On classic layout - the theme won't fill the whole page 

### ISSUE THREAD

**Issue by benirave** [scalar/scalar#1190]
### What happens?

Hi there,

When you create a new API reference, and you only have a couple of endpoints, the theme won't fill the whole page. 

![Screenshot 2024-03-14 201823](https://github.com/scalar/scalar/assets/23312114/11d2b7b5-c01d-4131-b0e6-c80ffabd5708)

### What did you expect to happen?

I would expect that the whole site matches the theme.

### How can we reproduce the issue?

1. Create a new Api Reference with the following configurations.:
```javascript     
var configuration = {
        theme: 'bluePlanet',
        layout: 'classic'
}
```
2. Use the following spec file.:
[openapi-spen.json](https://github.com/scalar/scalar/files/14607097/openapi-spen.json)

By the way, with the bluePlanet theme, the dark mode button disappears, but it is still clickable.

**Comment by hwkr** [comment]
Hey @benirave, I tried to replicate this but it seems to be working fine for me. Are you using the CDN version or the Vue component? (Or one of the other packages)

**Comment by hanspagel** [comment]
Closing this for now. Happy to reopen if there’s more information. ✌️
