### ISSUE TITLE
search doesn't work when the API client is open

### ISSUE THREAD

**Issue by hanspagel** [scalar/scalar#1208]
The search is still visible when the API client is open, but when I try to open a specific operation it seems to not do this in the API client, but in the background.

![Screenshot 2024-03-15 at 15 53 26](https://uploads.linear.app/06a32804-030f-45a1-98aa-79d02a076af5/934543b8-b796-4357-aca8-8e85971aa7d6/ea294283-686b-467a-8b92-9fbecc6c16db?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzA2YTMyODA0LTAzMGYtNDVhMS05OGFhLTc5ZDAyYTA3NmFmNS85MzQ1NDNiOC1iNzk2LTQzNTctYWNhOC04ZTg1OTcxYWE3ZDYvZWEyOTQyODMtNjg2Yi00NjdhLThiOTItOWZiZWNjNmMxNmRiIiwiaWF0IjoxNzEwNzc0NTA1LCJleHAiOjMzMjgxMzM0NTA1fQ.eAHwx8JBLKmSEwHgg8_MVLuCdlKTfJusT_CXLBCUOSc "=1511x")

**Comment by hwkr** [comment]
@hanspagel This seems to be working on latest main 🤔 

https://github.com/scalar/scalar/assets/6374090/9597d3b5-bd17-4a9a-83cb-d7bd30877f41

**Comment by hwkr** [comment]
@hanspagel Going to close this for now, feel free to reopen if need 😄
