### ISSUE TITLE
`fastify-api-reference` is not released along with other `*-reference` packages

### ISSUE THREAD

**Issue by lundibundi** [scalar/scalar#1246]
### What happens?

Latest changes in `api-reference` didn't result in `fastify-api-reference` release.

https://github.com/scalar/scalar/pull/1219
https://github.com/scalar/scalar/pull/1245

### What did you expect to happen?

`fastify-api-reference`  to be released upon changes in `api-reference`.

### How can we reproduce the issue?

automatic creation of release PR after changes to `api-reference`.

**Comment by hanspagel** [comment]
Oops! Yes, it’s not added as a dependency there, which prevents our release process from picking up the changes, so we manually need to release that. Maybe we should just add the package as a dependency there. Let me check once more if we can find another way.

Meanwhile, I’ll do a manual release for the fastify integration.

**Comment by lundibundi** [comment]
@hanspagel Thank you =).

**Comment by zAlweNy26** [comment]
Any update?

**Comment by hanspagel** [comment]
I think this was fixed in #1246!
