### ISSUE TITLE
hiddenClients property doesnt hide clients

### ISSUE THREAD

**Issue by Lumca** [scalar/scalar#1250]
### What happens?

It stays as it is, even when empty array is passed, it doesnt show clients that are not shown by default

### What did you expect to happen?

Hide the clients

Or that could be a feature where can I set which clients I want to show, we want to show just a HTTP1.1. 
But the feature for hidding is good enough

### How can we reproduce the issue?

Set for example hiddenClients: [`node`] in ApiReference

Thanks for checking! :)

**Comment by hanspagel** [comment]
Thanks for the report! I’ll fix that.

**Comment by SlavaSereb** [comment]
Hey @hanspagel I can see that you're extensively working on the fix, thank you!

Any estimated time for pushing it?

**Comment by hanspagel** [comment]
Very soon :)

**Comment by hanspagel** [comment]
Should be fixed in #1387 :)

**Comment by Lumca** [comment]
Thanks guys!

**Comment by Lumca** [comment]
So I have tested it and there is still little bug.
I have setted:
`hiddenClients: {
          php: true,
          python: true,
          c: true,
          node: true,
          javascript: true,
          go: true,
          java: true,
          ruby: true,
          shell: true,
          clojure: true,
          csharp: true,
          kotlin: true,
          objc: true,
          swift: true,
          r: true,
          powershell: true,
          ocaml: true,
          curl: true,
        },`

It still makes curl default:
![image](https://github.com/scalar/scalar/assets/4989415/966b9d8c-4c8e-4837-940b-8cd0c67cec4c)

and upon clicking there is only http
![image](https://github.com/scalar/scalar/assets/4989415/795feab7-4b46-4a6f-9e92-e8200451bd11)

should I create new bug? :) 

thank you guys!
