### ISSUE TITLE
Buffer is not defined

### ISSUE THREAD

**Issue by gpsfl** [scalar/scalar#1272]
### What happens?

After entering credentials for basic auth the http client previews will no longer render

```
api-reference:19 ReferenceError: Buffer is not defined
    at vf (api-reference:26:206867)
    at yf (api-reference:26:206992)
    at api-reference:38:762435
    at r (api-reference:19:2864)
    at rr (api-reference:21:2908)
    at Proxy.<anonymous> (api-reference:38:283486)
    at mn (api-reference:19:3180)
    at le.l [as fn] (api-reference:21:19220)
    at le.run (api-reference:14:1475)
    at api-reference:21:20095
```

This should be following line in code:
https://github.com/scalar/scalar/blob/c4a26a7e9317436ca75c5c837aa40c873637efdf/packages/api-reference/src/helpers/getRequestFromAuthentication.ts#L167

### What did you expect to happen?

Authentication should be shown correctly in the client code previews

### How can we reproduce the issue?

1. Create a page as explained in the "From a CDN" example

2. Add a basic security scheme to the open api spec
```json
    "securitySchemes" : {
      "auth" : {
        "type" : "http",
        "scheme" : "basic"
      }
    }
```

3. Enter credentials in the authentication field

![image](https://github.com/scalar/scalar/assets/38128299/28e29910-c56b-4583-b20f-4029409bd2da)

**Comment by gpsfl** [comment]
I assume this happens because `Buffer` isn't available in the browser. For some reason I can't reproduce this in the code sandbox, there it doesn't render the authentication but also doesn't show any errors.

**Comment by hanspagel** [comment]
Yes! We dropped a polyfill for it recently I think. I’ll fix this asap.

**Comment by gpsfl** [comment]
Basic Auth works for me now. Not sure if this is related to the changes, but schemas aren't showing for me after updating

![image](https://github.com/scalar/scalar/assets/38128299/d95b25d7-2f9e-4613-ac8c-061e90d0bfe1)

**Comment by hanspagel** [comment]
Fixed :)
