### ISSUE TITLE
URLs in request tool are transformed to lowercase

### ISSUE THREAD

**Issue by gpsfl** [scalar/scalar#1287]
### What happens?

The "Test request" tool transforms all URLs to lowercase

![image](https://github.com/scalar/scalar/assets/38128299/05831b2f-148d-4575-bb9d-7995d7dcd24d)

### What did you expect to happen?

It should not transform the URLs to lowercase because paths and query parameters are case sensitive

### How can we reproduce the issue?

1. Use an URL with uppercase letters
2. Send a request using the "Test request" tool

**Comment by marclave** [comment]
sorry! didnt see you self assigned on linear since it was still in triage

**Comment by hwkr** [comment]
No problem!
