### ISSUE TITLE
Descriptions repeat themselves

### ISSUE THREAD

**Issue by Vilsol** [scalar/scalar#1318]
### What happens?

Descriptions of an object repeat twice:

![image](https://uploads.linear.app/06a32804-030f-45a1-98aa-79d02a076af5/17478d78-0923-4617-bfde-5a7d4d94b54c/bc0585f9-4c7f-4ce3-a3f0-29346df205ea?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzA2YTMyODA0LTAzMGYtNDVhMS05OGFhLTc5ZDAyYTA3NmFmNS8xNzQ3OGQ3OC0wOTIzLTQ2MTctYmZkZS01YTdkNGQ5NGI1NGMvYmMwNTg1ZjktNGM3Zi00Y2UzLWEzZjAtMjkzNDZkZjIwNWVhIiwiaWF0IjoxNzExOTg1NDk0LCJleHAiOjMzMjgyNTQ1NDk0fQ.UBQ6a4t7O8v4IpEd87tELzjlmTdeFtVPn2ULgHQ4wFM)

### What did you expect to happen?

Not to repeat descriptions

### How can we reproduce the issue?

Go to sandbox

### Swagger/OpenAPI Example

[https://sandbox.scalar.com/e/SpV4O](https://sandbox.scalar.com/e/SpV4O)

---

It gets even weirder when testing against [https://docs.scalar.com/swagger-editor](https://docs.scalar.com/swagger-editor). `a`, `c`, `d` work, but `b` has no description at all.

![image](https://uploads.linear.app/06a32804-030f-45a1-98aa-79d02a076af5/1e34d9d6-4e43-4d76-bbb2-0765cd3c17c2/4e22bf91-cfa1-488c-9530-9951be7c8c34?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzA2YTMyODA0LTAzMGYtNDVhMS05OGFhLTc5ZDAyYTA3NmFmNS8xZTM0ZDlkNi00ZTQzLTRkNzYtYmJiMi0wNzY1Y2QzYzE3YzIvNGUyMmJmOTEtY2ZhMS00ODhjLTk1MzAtOTk1MWJlN2M4YzM0IiwiaWF0IjoxNzExOTg1NDk0LCJleHAiOjMzMjgyNTQ1NDk0fQ.nMr7lN28Q-aZRipcFB01jWxC2Oc0WciFwSs2HSyO7HI)

**Comment by antlio** [comment]
it seems like when a schema has a description but also properties, it renders it for the value + for the schema card child property. however i don't reproduce the `b` missing description in the editor.

would checking in SchemaProperty that `value?.description && !value.properties` make sense / be enough here?

**Comment by hanspagel** [comment]
Thanks for reporting! Probably introduced with https://github.com/scalar/scalar/pull/1275.
