### ISSUE TITLE
Bun / Hono - Do not found swagger.json file

### ISSUE THREAD

**Issue by adriangallegos** [scalar/scalar#1320]
### What happens?

On Bun 1.0.35 / Hono 3.7.2 / @scalar/hono-api-reference 0.4.18

`
import { Hono } from "hono"
import { apiReference } from "@scalar/hono-api-reference"

const app = new Hono()

app.get(
  "/docs",
  apiReference({
    pageTitle: "API Validación Gunei",
    spec: { url: "/static/swagger.json" },
  })
)
`

Do not find **swagger.json**, I tried "./static/swagger.json", "swagger.json", "/swagger.json", "./swagger.json"

The floder structure is:

-> src
  |-> index.ts
  |-> /static
     |-> swagger.json

Scalar page open "empty" at /docs and logging

`
Started server http://localhost:3000
  <-- GET /static/swagger.json
  --> GET /static/swagger.json 404 1ms
`

### What did you expect to happen?

Read the swagger.json file
[swagger.json](https://github.com/scalar/scalar/files/14765231/swagger.json)

### How can we reproduce the issue?

On Bun 1.0.35 / Hono 3.7.2 / @scalar/hono-api-reference 0.4.18

`import { Hono } from "hono"
import { apiReference } from "@scalar/hono-api-reference"

const app = new Hono()

app.get(
  "/docs",
  apiReference({
    pageTitle: "API Validación Gunei",
    spec: { url: "/static/swagger.json" },
  })
)`

**Comment by marclave** [comment]
hi @adriangallegos we will investigate first thing in the morning :)

**Comment by amritk** [comment]
hi @adriangallegos to serve a static file you will need to use the `staticAdapter` check out these docs for usage:
https://hono.dev/getting-started/basic#adapter

I will add it to the example we have in this repo as well 😄

**Comment by adriangallegos** [comment]
hi @amritk !!!

Thanks for your response !!!

Working on it !!!
