### ISSUE TITLE
Improvements to `@scalar/fastify-api-reference`

### ISSUE THREAD

**Issue by arthurfiorette** [scalar/scalar#1328]
### What happens?

The fastify scalar plugin only uses `fastify-html` to set the correct content type header. The problem lives by `fastify-html` decorating the fastify reply with `.html` which is a common name also used by a lot of other pacakges:

1. @kitajs/fastify-html-plugin
2. @fastify/vite
3. @fastify/react
4. (and others)

Since the main feature of `fastify-html` is layouts (which is not used here), we could simply remove the plugin to avoid such conflict issues. _[The entire plugin source code.](https://github.com/mcollina/fastify-html/blob/main/index.js)_

Also, current setup doesn't install it automatically (its only on peerDeps and devDeps) and npm does not install peer dependencies by default (pnpm with `auto-install-deps` does, but not everyone uses it). So if the plugin will be keept, it should be moved to the package's dependencies.

### What did you expect to happen?

above :)

### How can we reproduce the issue?

above :)

**Comment by hanspagel** [comment]
Thanks for reporting! This sounds legit. I just want to mention that I think @mcollina asked us to add fastify-html, so we might need to check whether there’s an alternative solution to the problem. 🤔

**Comment by arthurfiorette** [comment]
Thanks :)

---

Btw, I think this plugin can be even further improved:

1. By extracting the custom theme to a css file, it can be later imported ([and minified a little bit](https://github.com/kitajs/kitajs/blob/8f06fb4f8dc6ec184b763e6d982da6b194b6ed68/packages/parser/src/util/swagger.ts#L22)) which improves what is sent but also allows the custom fastify theme to be used elsewhere, [just like I did with kitajs](https://github.com/kitajs/kitajs/tree/main/packages/parser#using-kitas-scalarui-theme) to also use the created theme at in our [documentation](https://github.com/kitajs/docs/blob/7831054caa79a4a0116fd2d9ac0a01246c5ecea5/public/swagger/practical-example.html#L12).

2. A custom property called `head` could be added to allow custom `scripts`/`assets`/`styles`/`meta` to be added to the [document's head](https://github.com/scalar/scalar/blob/390fd982bf6796c6267f2d6ae105a6567f3700f2/packages/fastify-api-reference/src/fastifyApiReference.ts#L157). E.g: If I wanted to add some sort of tracking/analytics to my API documentation, there's no current way of doing this.

3. There still some configuration being [calculated on every request](https://github.com/scalar/scalar/blob/390fd982bf6796c6267f2d6ae105a6567f3700f2/packages/fastify-api-reference/src/fastifyApiReference.ts#L203), which could be extracted to outside the route handler.

**Comment by arthurfiorette** [comment]
Hmm... Interesting, seems that I was in fact wrong... [Its a known limitation of fastify vite](https://fastify-vite.dev/guide/known-limitations#known-limitations). 

However is there a reason to use `fastify-html`? Even the content type is being set manually:

https://github.com/scalar/scalar/blob/8b0691bce77ef4311a9513e0fbe9303d633a3663/packages/fastify-api-reference/src/fastifyApiReference.ts#L200
