### ISSUE TITLE
Authentication resets on sidebar navigation

### ISSUE THREAD

**Issue by Amorim33** [scalar/scalar#1336]
### What happens?

[Screencast from 2024-03-28 23-52-28.webm](https://github.com/scalar/scalar/assets/42624869/cdcc004a-947f-46ae-950c-de0e640fbec3)

Currently, when changing the current endpoint via sidebar, the authentication header is cleared.
The UI continues showing it. However, it is not added to the request headers.

### What did you expect to happen?

Authentication header to be present in the request.

### How can we reproduce the issue?

1. Add authentication to the API
2. Click on "Test Request" in any endpoint
3. Navigate through the endpoints via sidebar
4. Try to "Send Request"

**Comment by Amorim33** [comment]
If this makes sense, I will be stoked to fix it!

**Comment by marclave** [comment]
@Amorim33 would love for you to tackle this! ✨
