### ISSUE TITLE
link security in components to global security field

### ISSUE THREAD

**Issue by marclave** [scalar/scalar#1343]
### What happens?

if you add security to components it doesnt render

![image](https://github.com/scalar/scalar/assets/6176314/c6bd181a-03d4-4fc1-a061-5a465aadbc4a)
![image](https://github.com/scalar/scalar/assets/6176314/1a8b7c62-8060-404b-8d67-082de4ac0179)

### What did you expect to happen?

it renders globally

### How can we reproduce the issue?

add a security to a component

**Comment by hwkr** [comment]
Looks like this got fixed at some point

![Google Chrome-2024-04-09-12-22-40@2x](https://github.com/scalar/scalar/assets/6374090/65674ccf-d1dd-4010-b9c5-3d7fd7389be5)
![Code-2024-04-09-12-22-45@2x](https://github.com/scalar/scalar/assets/6374090/97bf245d-42f7-43b2-a8c7-4c1a157d6ed3)
