### ISSUE TITLE
Authentication dropdown not showing options

### ISSUE THREAD

**Issue by ga1az** [scalar/scalar#1349]
### What happens?

Authentication dropdown not showing options, I've always used it with the default settings from the @elysiajs/swagger package, but it stopped showing the options for some reason.

![CleanShot 2024-03-30 at 22 35 17@2x](https://github.com/scalar/scalar/assets/75758899/23337069-85fd-41a5-ae53-2ecb2ea537c0)

### What did you expect to happen?

It should show the options to add an authentication variable, as it did before by default.

### How can we reproduce the issue?

I'm using the @elysiajs/swagger package, but you can still see from the scalar playground, that the authentication option doesn't display the information it should.

### Swagger/OpenAPI Example

https://sandbox.scalar.com/e/tqX40

**Comment by marclave** [comment]
a 3 day dinner 👀 

im on it now ✨

**Comment by marclave** [comment]
fixed here! https://github.com/scalar/scalar/pull/1367 ✨ 

fixed in latest scalar api reference version! `@scalar/api-reference@1.20.20`

**Comment by marclave** [comment]
@ga1az im on the latest CDN and its workign for me ✨ 

<img width="623" alt="image" src="https://github.com/scalar/scalar/assets/6176314/ce3c8717-63e3-4869-b655-ed23a195e7f1">


can you confirm latest is working? :) are you using the CDN or one of our packages?

**Comment by ga1az** [comment]
It must be because I'm testing it from the package. 
`@elysiajs/swagger`
But I updated the package at my place and it works perfectly.
`"@scalar/api-reference": "^1.20.20"`
<img width="617" alt="image" src="https://github.com/scalar/scalar/assets/75758899/789606a2-56f4-4df2-a576-6d38722feb58">

Thanks for the change 🚀

**Comment by marclave** [comment]
@ga1az awesome!! is it working inside of the @elysiajs/swagger package? :)

**Comment by ga1az** [comment]
It does work for the package: `"@elysiajs/swagger": "^1.0.3"` which is the one I tested.

**Comment by marclave** [comment]
awesome! closing :)

**Comment by russism** [comment]
Seems broken again in "@elysiajs/swagger": "^1.0.5". I can't see the Authentication dropdown at all.

![image](https://github.com/scalar/scalar/assets/156235049/3fc355dc-107c-4d0e-bdf8-62ca5c47fdf9)
