### ISSUE TITLE
404 cannot load file browser.js with fastify plugin

### ISSUE THREAD

**Issue by isaacfink** [scalar/scalar#1385]
### What happens?

the ui doesn't load

### What did you expect to happen?

The UI should load

### How can we reproduce the issue?

Create a fastify instance like this

```ts
const app = Fastify()
  .register(fastifySwagger, {
    transformObject: () => openApiDocument,
    
  })
  .register(ScalarUi, {
    prefix: '/docs'
  });
```

And run with bun

**Comment by hanspagel** [comment]
Would you mind to try routePrefix instead of prefix?

**Comment by hanspagel** [comment]
I think it’s `routePrefix` instead of `prefix`. I followed this guide: https://github.com/scalar/scalar/blob/main/documentation/fastify.md and everything seems to work just fine.

I’m closing this for now, let me know if I missed something. :)
