### ISSUE TITLE
Response message get processed by JSON.stringify() multiple times.

### ISSUE THREAD

**Issue by MrLis** [scalar/scalar#1396]
### What happens?

Response message get processed by JSON.stringify() multiple times.

See example
![Screenshot 2024-04-08 233406 (2)](https://github.com/scalar/scalar/assets/14166216/54559e5a-78ab-4236-9dba-17a502ead42a)

Method "ping" actually returns string `"Pong\n"` not the `"\\"Pong\\\\n\\""`.

I want to note that i'm not using data-proxy-url.
It seems that using a proxy may change the visible response value.

### What did you expect to happen?

Raw data that server returns:
![Screenshot 2024-04-08 233406 (3)](https://github.com/scalar/scalar/assets/14166216/0cc29a59-e26c-403c-9e1e-ee65573fefae)

### How can we reproduce the issue?

The same result can be achieved by using this command:
`console.log(JSON.stringify(JSON.stringify("Pong\n")));`

**Comment by hanspagel** [comment]
Not merged and released yet, though. But soon. 🤞
