### ISSUE TITLE
Blank render, no errors in console. Works fine <= 1.1.8.7

### ISSUE THREAD

**Issue by rmoff** [scalar/scalar#1404]
### What happens?

We're using Scalar to render our API docs here https://docs.decodable.co/api/data-plane.html

We noticed that it had stopped working - the API reference doesn't render. There's no error in the console.

![CleanShot 2024-04-09 at 09 55 16](https://github.com/scalar/scalar/assets/3671582/f84c27a2-0ae0-4c90-8231-b8521a67f6c8)

Nothing had changed on our side. By process of trial and error we found that the latest working version of Scalar is 1.18.7. Versions 1.19.1 and above don't work. 

### What did you expect to happen?

It should work, like it did previously.

### How can we reproduce the issue?

This works: 

```html
<!DOCTYPE html> <html lang="en"> <head> <title>API Reference [Decodable]</title> </head> <body>
    
    <div id="api-reference-container">
          <script
      id="api-reference"
      data-url="https://docs.decodable.co/_attachments/decodable-data-plane-openapi3-v1alpha2.yaml"
      data-proxy-url="https://api.scalar.com/request-proxy"></script>
    <script>
      var configuration = {
        darkMode: false,
      }

      var apiReference = document.getElementById('api-reference')
      apiReference.dataset.configuration = JSON.stringify(configuration)
    </script>
    <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference@1.18.7"></script>
    </div>
  </body> </html>
```

This doesn't work: 

```html
<!DOCTYPE html> <html lang="en"> <head> <title>API Reference [Decodable]</title> </head> <body>
    
    <div id="api-reference-container">
          <script
      id="api-reference"
      data-url="https://docs.decodable.co/_attachments/decodable-data-plane-openapi3-v1alpha2.yaml"
      data-proxy-url="https://api.scalar.com/request-proxy"></script>
    <script>
      var configuration = {
        darkMode: false,
      }

      var apiReference = document.getElementById('api-reference')
      apiReference.dataset.configuration = JSON.stringify(configuration)
    </script>
    <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference@1.19.1§"></script>
    </div>
  </body> </html>
```

### Swagger/OpenAPI Example

https://docs.decodable.co/_attachments/decodable-data-plane-openapi3-v1alpha2.yaml

**Comment by amritk** [comment]
hey @rmoff there looks like there's an extra character in the version there
```html
<script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference@1.19.1§"></script>
```
an extra `§`. I just tested your spec with version `1.19.1` as well as the latest `1.20.27` and it seems to be working great!

![image](https://github.com/scalar/scalar/assets/2039539/45e8fdea-f640-48b4-9b80-6f9cfd6b70a8)

Please let me know if that solves your issue!

Cheers

**Comment by rmoff** [comment]
OK, that is super-weird. The `§` was a copy-pasta error, and I was definitely getting a blank render when using the correct syntax

```
<script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference@1.19.1"></script>
```

and same with

```
<script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>
```

…But now both work fine. Which is good, I guess. 

Thanks for following up…fingers crossed this was just a glitch in the matrix :D
