### ISSUE TITLE
Response `examples` not used (only `example`)

### ISSUE THREAD

**Issue by TimoGlastra** [scalar/scalar#1406]
### What happens?

When using `examples` in the response content media type examples for OpenAPI, they are not rendered by Scalar.

If you look at the OpenAPI spec, it mentions you can use `examples`, allowing you to add extra metadata like description, etc..: https://spec.openapis.org/oas/v3.1.0#media-type-examples.

I worked around it for now by post processing our generated OpenAPI file and create an `example` field based on the first example from the examples object

### What did you expect to happen?

At least the first example from examples is rendered, preferably all examples

### How can we reproduce the issue?

1. Go to the example sandbox and see the difference between the examples. The `examples` are not rendered, but `example` is.

### Swagger/OpenAPI Example

https://sandbox.scalar.com/e/BpTOG

**Comment by hwkr** [comment]
@TimoGlastra thank you so much for the sandbox 🙏 Makes debugging stuff like this 100x easier.

Looks like we only considered it "multiple examples" if it used the `examples` property __and__ also had more than one entry.  Opened a PR with a fix :)

**Comment by TimoGlastra** [comment]
Thanks for the quick fix, awesome project! 🙏
