### ISSUE TITLE
Sidebar shows on mobile even when showSidebar: false

### ISSUE THREAD

**Issue by paulmeller** [scalar/scalar#1421]
### What happens?

Sidebar shows on mobile even when showSidebar: false

### What did you expect to happen?

Header and sidebar to not show on mobile when showSidebar: false

### How can we reproduce the issue?

set showSidebar: false, and open on mobile

**Comment by amritk** [comment]
Hey @paulmeller I'll take a look at that right now

**Comment by amritk** [comment]
hi @paulmeller I was unable to get the sidebar to show up when you set it to false, could you show me an example and which versions you were using? I did however fix the header not showing

**Comment by paulmeller** [comment]
It I just the header, but, the hamburger made it look like it sidebar too. Thanks!
