### ISSUE TITLE
Anchor do not always work because of content shift

### ISSUE THREAD

**Issue by rubenfiszel** [scalar/scalar#1426]
### What happens?

Anchor do not always work because of content shift and browser end up being not at the right endpoint

https://github.com/scalar/scalar/assets/275584/26b42b87-0537-448f-a638-8b18927e7a47

### What did you expect to happen?

Anchor go to link and browser stay there

### How can we reproduce the issue?

 1. Use recent version of firefox
 2. Go to: https://app.windmill.dev/openapi.html#tag/job/post/w/{workspace}/jobs/run/p/{path}

**Comment by amritk** [comment]
Hello there @rubenfiszel, I can certainly take a look at that for you

**Comment by amritk** [comment]
hey @rubenfiszel could you confirm that it works now?
