### ISSUE TITLE
Editor not displaying

### ISSUE THREAD

**Issue by paulmeller** [scalar/scalar#1432]
### What happens?

I'm getting this issue from both plain HTML with CDN and the React component:
<img width="1481" alt="Screenshot 2024-04-14 at 11 14 22 AM" src="https://github.com/scalar/scalar/assets/14568/ab1ef1df-db9c-4378-92da-4422247d841d">

### What did you expect to happen?

The Editor to be displayed

### How can we reproduce the issue?

<!doctype html>
<html>

<head>
  <title>API Reference</title>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
</head>

<body>
  <script id="api-reference" data-url="https://petstore3.swagger.io/api/v3/openapi.json"
    data-proxy-url="https://api.scalar.com/request-proxy"></script>
  <script>
    var configuration = {
      theme: 'purple',
      isEditable: true
    }

    var apiReference = document.getElementById('api-reference')
    apiReference.dataset.configuration = JSON.stringify(configuration)
  </script>
  <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>
</body>

</html>

### Swagger/OpenAPI Example

https://petstore3.swagger.io/api/v3/openapi.json

**Comment by marclave** [comment]
hey @paulmeller we are going to be adding a separate package so we dont bundle the editor with the standalone app! We will update this issue with our progress from this week ✨

**Comment by paulmeller** [comment]
What version did the split occur as I will need to lock the older release?

Thanks
Paul

**Comment by hanspagel** [comment]
Relevant PR #1490

**Comment by hanspagel** [comment]
There’s a new `@scalar/api-reference-editor` now: #1490
