### ISSUE TITLE
allow the ability to sort tags

### ISSUE THREAD

**Issue by marclave** [scalar/scalar#1436]
### Discussed in https://github.com/scalar/scalar/discussions/1434

<div type='discussions-op-text'>

<sup>Originally posted by **itizarsa** April 15, 2024</sup>
How do we achieve [tagsSorter](https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/#:~:text=values%20for%20Parameters.-,tagsSorter,-Unavailable) behaviour from swagger UI with Scalar?</div>

**Comment by kylemclaren** [comment]
+1
