### ISSUE TITLE
Display Global Headers & Parameters

### ISSUE THREAD

**Issue by itizarsa** [scalar/scalar#1443]
### What happens?

Global headers & parameters under components aren't displayed

### What did you expect to happen?

OpenAPI spec supports global headers & parameters under components. It should be displayed alongside the operation

<img width="1154" alt="SS" src="https://github.com/scalar/scalar/assets/77574889/1c079ded-d0f1-469d-9032-64bb17257ff7">

### How can we reproduce the issue?

Current Doc - https://sandbox.scalar.com/e/b59fw

Expected Doc - https://sandbox.scalar.com/e/6sWkt

**Comment by itizarsa** [comment]
@marclave @hanspagel I can pick this up. If someone could help me figure out where do I check start working on this.

**Comment by hanspagel** [comment]
That’s so kind! Actually, this is part is a little complex (or maybe I should even say messy). If you want to give it a try, that’s where I’d start:

We need the `components` as a 2nd parameter in this function:
https://github.com/scalar/scalar/blob/main/packages/api-reference/src/hooks/useOperation.ts#L19

Unfortunately, we don’t have the `components` available in the component (yet). So we’ll probably need some prop drilling, passing the whole specification down as a prop:
https://github.com/scalar/scalar/blob/main/packages/api-reference/src/components/Content/Operation/EndpointDetails.vue

And once it’s in there, you can add the mentioned logic to `useOperation`.

Unfortunately, we’ll probably need to pass the headers to the API client too and it’s not using the same logic:
https://github.com/scalar/scalar/blob/main/packages/api-reference/src/helpers/openClientFor.ts

When I look at the code, I see a lot of potential for refactoring. I’m so sorry for making it so hard. If you’re stuck, just ping me again, and I’ll give it a try asap. It’d be a great opportunity for some refactoring anyway. :)

**Comment by itizarsa** [comment]
@hanspagel This is not supported on Swagger, should we do this on the scalar? Since it's not the behaviour of Swagger, people might want to opt out of this. We need to think about that too.

**Comment by hanspagel** [comment]
It’s in the OpenAPI specification, so we definitely want to support this. :) And if someone asks for it, we’ll add a setting for sure, but we can do this quickly once it’s needed I’d say.

**Comment by hanspagel** [comment]
Ah, I didn’t read properly. Putting `headers` under `components` is supported by the OpenAPI specification, but it says:

> **Components Object**
> Holds a set of reusable objects for different aspects of the OAS. **All objects defined within the components object will have no effect on the API unless they are explicitly referenced from properties outside the components object.**

We should only show them, if they are referenced in the operation, like shown here:

https://sandbox.scalar.com/e/jPFlQ

I’ll close this for now, but feel free to add to the discussion here. :v:
