### ISSUE TITLE
Anchors for endpoints with parameters (braces) do not work

### ISSUE THREAD

**Issue by databyjp** [scalar/scalar#1444]
### What happens?

Anchors for endpoints such as this work fine:
[https://weaviate.io/developers/weaviate/api/rest#tag/objects/get/objects](https://weaviate.io/developers/weaviate/api/rest#tag/objects/get/objects)

But for those with parameters like this [https://weaviate.io/developers/weaviate/api/rest#tag/objects/get/objects/%7BclassName%7D/%7Bid%7D](https://weaviate.io/developers/weaviate/api/rest#tag/objects/get/objects/%7BclassName%7D/%7Bid%7D) do not seem to work, unfortunately. 

Tested on: Mac OS X, Chromium & Safari. 

### What did you expect to happen?

For both link to navigate to the correct OpenAPI spec section

### How can we reproduce the issue?

Go to [https://weaviate.io/developers/weaviate/api/rest#tag/objects/get/objects/%7BclassName%7D/%7Bid%7D](https://weaviate.io/developers/weaviate/api/rest#tag/objects/get/objects/%7BclassName%7D/%7Bid%7D). The sidebar will open the right section, but the page will navigate to the right anchor / verb.

### Swagger/OpenAPI Example

https://raw.githubusercontent.com/weaviate/weaviate/openapi_docs/openapi-specs/schema.json

**Comment by amritk** [comment]
Hey @databyjp we actually recently fixed this! 

https://github.com/scalar/scalar/pull/1407

@marclave we probably just need to release right?

**Comment by amritk** [comment]
hey @databyjp was just checking if this was still an issue?

**Comment by databyjp** [comment]
Hey @amritk - sorry about the late reply! Yes it works now 🎉😊
