### ISSUE TITLE
Create ESM javascript build + docs

### ISSUE THREAD

**Issue by amritk** [scalar/scalar#1445]
A requested feature is to have a JS ESM version of references. This should be easy to do by creating a little wrapper around vue with an init function.

**Comment by Ansett** [comment]
Hello. Any rough ETA on this?
We're planning to use Scalar, but we're still on Vue 2.7.

**Comment by amritk** [comment]
unfortunately not at the moment, as things are pretty crazy! But we hope to start setting up our roadmap later this year so you will be able to track the tickets!

**Comment by geoffgscott** [comment]
@Ansett We were able to get something completed this week. You can take a look at https://github.com/scalar/scalar/pull/1855 for an example integration but in Vue 2 you would likely just do something along the lines of:
```js
data: {
  scalarInstance: null,
  configuration: {
    // ... Some config here. When this changes the watcher will trigger and update the configuration
  },
},
mounted() {
  this.scalarInstance = createScalarReferences(
    this.$refs.element,
    this.configuration ?? {}
  );
},
beforeDestroy() {
  this.scalarInstance?.unmount();
},
watch: {
  configuration: function (val) {
    this.scalarInstance?.updateConfig(val, false);
  },
}
```
Excuse any syntax errors my Vue2 is very rusty.

**Comment by Ansett** [comment]
Wonderful! We're going to try this. Thanks a lot.

**Comment by Ansett** [comment]
Well, actually, since headlessui needs a vue3 peer-depency and we've vue2.7 installed I guess it still can't work.
We'll find an other way thanks anyway :D
