### ISSUE TITLE
searchHotKey uses WIN (meta) instead of CTRL on Linux / Windows

### ISSUE THREAD

**Issue by Alvie** [scalar/scalar#1447]
### What happens?

The search box display shows `^K` so I assumed it to be CTRL  + K. Unfortunately this was not working, it seems to be using WIN + K instead.
I, using Linux, asked my colleague to check on Windows and they came across the same issue. Another colleague using macOS found the CMD+K shortcut to work fine.

### What did you expect to happen?

Search box to open with CTRL + K, not with WIN + K

### How can we reproduce the issue?

1. Use a Windows / Linux machine
2. Visit a page using scalar e.g. https://sandbox.scalar.com
3. Hit CTRL + K (nothing happens)
4. Hit WIN + K (works)

### Swagger/OpenAPI Example

https://sandbox.scalar.com

**Comment by Alvie** [comment]
I think from here? I'm not too familiar with the ins and outs but I believe the `meta` key is the "WIN" key (also sometimes called "Super")
https://github.com/scalar/scalar/blob/f2cb2faee0ab421a0feabbaa5231f3bab5a7d1c1/packages/api-reference/src/components/SearchButton.vue#L23

The same issue might exist here:
https://github.com/scalar/scalar/blob/f2cb2faee0ab421a0feabbaa5231f3bab5a7d1c1/packages/api-client/src/components/ApiClient/AddressBar.vue#L25

Based on this site, I think `meta` should be replaced with `control` for non-Apple devices:
https://vueuse.org/core/useMagicKeys/

**Comment by amritk** [comment]
You got it! We got a PR up, I will check out the address bar as well

**Comment by amritk** [comment]
hey @Alvie check out this preview build, does it fix all the issues?

https://432ab736-7795-49bf-b078-83a2366eeece--scalar-deploy-preview.netlify.app/

**Comment by Alvie** [comment]
> hey @Alvie check out this preview build, does it fix all the issues?
> 
> https://432ab736-7795-49bf-b078-83a2366eeece--scalar-deploy-preview.netlify.app/

Hey @amritk! This is brilliant, thank you :) It's working great on Linux, I'll double check on Windows too

**Comment by amritk** [comment]
Cool! I'll merge and send up a release

**Comment by Alvie** [comment]
> Cool! I'll merge and send up a release

Can confirm working as expected on Windows too!
