### ISSUE TITLE
Nuxt Module Runtime Error

### ISSUE THREAD

**Issue by corepay** [scalar/scalar#1453]
### What happens?

Install plugin via `npx nuxi module add @scalar/nuxt` on fresh install no problems adding module.

* Using bun worspaces
* Without adding module to nuxt.config or any other changes:

`bun run dev` 

[4:22:29 PM]  ERROR  Cannot start nuxt:  Cannot find module '/home/runner/work/scalar/scalar/node_modules/.pnpm/jiti@1.21.0/node_modules/jiti/lib/index.js'

Tried this on both a fresh full nuxt app app and in a layers app same result.

NOTICING...

In the layers and full app where I run the plugin installation the package.json gets the `    "@scalar/nuxt": "^0.0.5",` as dependency BUT the `    "@scalar/api-reference": "^1.21.2",` is stuffed into the root bun workspace package.json.  I tremoved `@scalar/api-reference` and tried to add it to the layers/nuxt3 app in th workspace but got the above error and won't build at all now.

### What did you expect to happen?

Able to run nuxt app with or without module enabled in nuxt.config

### How can we reproduce the issue?

1.  fresh empty folder add a bun workspace package.json to root:
```json
{
  "name": "bun-workspace",
  "private": true,
  "workspaces": [
    "apps/*",
    "layers/*"
  ]
}
```

create 2 folders:  `layers` and `apps`

In the `layers` folder:
* create a nuxt layer app `npx nuxi init -t layer layerapp` and use bun as build tool option
cd to layerapp:
* install scalar`npx nuxi module add @scalar/nuxt`. 
* then `bun run dev`

You should get the same error message.

To test on a full nuxt app you'll need to delete the layerapp becuase you won't be able to install a new app now because a build error from the workspace layerapp scalar module is created.

In the `apps` folder:
* create a nuxt app `npx nuxi init nuxtapp` and use bun as build tool option
cd to nuxtapp:
* install scalar`npx nuxi module add @scalar/nuxt`. 
* then `bun run dev`

**Comment by corepay** [comment]
ADD:  I do not think this is a bun issue or a bun workspaces related problem.  I did fresh installs using bun as a build tool standalone outside of any workspace and same error after installing plugin.  I then did a fresh nuxt3 app install using pnpm as a build tool and same errors.

**Comment by corepay** [comment]
The referenced missing file in the error does indeed exist in the node_modules:

![image](https://github.com/scalar/scalar/assets/48992923/855648a8-4744-4b55-bfa9-0f556d2af0fd)

**Comment by amritk** [comment]
hey @corepay can you update to version `0.0.9` and try again? it should be good now. 

Cheers

**Comment by corepay** [comment]
Sure I will.

FYI I found the backdoor to really what I wanted to accomplish was have an API attached to my nuxt project for rapid prototype via what looks to be built into nitro server already `https://nitro.unjs.io/config#experimental`.

**Comment by amritk** [comment]
Yep the nitro one already existed for prototyping. This new nuxt one will be good for user facing docs as they are server side rendered now!

**Comment by corepay** [comment]
It's early I just woke up and haven't had any coffee yet so maybe I'm still in bed dreaming but this is what I am getting:

![image](https://github.com/scalar/scalar/assets/48992923/75845573-239f-4919-97d7-0b6f1704c2db)

I am a tthe root of my nuxt project.  Tried both `npx nuxi module add @scalar/nuxt` and `npx nuxi module add @scalar/nuxt@0.0.9`

```
rp@MBP Admin % npx nuxi module add @scalar/nuxt

ℹ Installing dev dependency @scalar/nuxt@latest                                                    4:18:48 AM

 ERROR  No package manager auto-detected.                                                           4:18:48 AM

  at resolveOperationOptions (/Users/rp/node_modules/nuxi/dist/shared/nuxi.5d0fe0bd.mjs:52:11)
  at async addDependency (/Users/rp/node_modules/nuxi/dist/shared/nuxi.5d0fe0bd.mjs:165:27)
  at async Object.setup (/Users/rp/node_modules/nuxi/dist/chunks/add2.mjs:26605:19)
  at async runCommand$1 (/Users/rp/node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1620:5)
  at async runCommand$1 (/Users/rp/node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1639:11)
  at async runCommand$1 (/Users/rp/node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1639:11)
  at async runMain$1 (/Users/rp/node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1773:7)


✔ Install failed for @scalar/nuxt@latest. Do you want to continue adding the module to nuxt.config?
No
rp@MBP Admin % npx nuxi module add @scalar/nuxt@0.0.9

ℹ Installing dev dependency @scalar/nuxt@0.0.9                                                     4:21:31 AM

 ERROR  No package manager auto-detected.                                                           4:21:31 AM
```

**Comment by corepay** [comment]
Remember I am in a bun workspace here.

I did a fresh install outside of the workspace and everything installed correctly.  I'll configure it now and see what I can do there

**Comment by corepay** [comment]
`bun run dev` fresh install right after plugin and update nuxt.config.ts:

![image](https://github.com/scalar/scalar/assets/48992923/58937777-9041-4796-a6f3-216977c7d5ef)


![image](https://github.com/scalar/scalar/assets/48992923/f673c4a9-0008-467b-9ad5-16a2365684a9)

**Comment by amritk** [comment]
Okay so the issue was with adding bun to an existing project?

**Comment by corepay** [comment]
no - brand new nuxt install in my project bun workspace resulted in first error:  
![image](https://github.com/scalar/scalar/assets/48992923/40bd3365-a575-4904-981f-c877e56f982d)

then did brand new nuxt install with bun outside the workspace adn got the 2nd error.  

![image](https://github.com/scalar/scalar/assets/48992923/2322bea4-ad76-41ab-8f56-a364a377e5df)

Different errors based on the install environment.

**Comment by corepay** [comment]
Bun isn't something you add - it is a build tool supported by Nuxt.

**Comment by amritk** [comment]
hmm the first one looks like a possible issue with the install command since it can't find out which package manager you are using.

The second one can be ignored for now, I'll figure out why the source maps aren't working

**Comment by corepay** [comment]
I dont have time to test right now but just had a thought might be helpful.   Try installing the module via `bunx` instead of `npx` as in `bunx nuxi module add @scalar/nuxt@0.0.9`.  I probably should be doing this already but to this point `npx` works just fine on other modules.

**Comment by codeofsumit** [comment]
I have the same issue (but using with npm)
