### ISSUE TITLE
Swagger loads fonts from google

### ISSUE THREAD

**Issue by Anulo2** [scalar/scalar#1471]
### What happens?

https://github.com/elysiajs/elysia-swagger/issues/104

as said here the swagger interface loads some google fonts

### What did you expect to happen?

To not load external fonts and remain a completely local interface

### How can we reproduce the issue?

See code in linked issue

**Comment by hanspagel** [comment]
PR is in the works :)
https://github.com/scalar/scalar/pull/1477
