### ISSUE TITLE
Platformatic css missing

### ISSUE THREAD

**Issue by clabnet** [scalar/scalar#1472]
### What happens?

Related to https://github.com/platformatic/platformatic/issues/2429#issuecomment-2066820088
is required to wait your release or Fastify release ? 

### What did you expect to happen?

A Scalar beautiful page

### How can we reproduce the issue?

Platformatic create service 
```
pnpm create platformatic@latest
```

**Comment by marclave** [comment]
hey @clabnet ! we fixed this in the latest release of Scalar

what version are you running?

https://github.com/platformatic/platformatic/issues/2429#issuecomment-2066820088

**Comment by clabnet** [comment]
1.36.1 of Platformatic

Il giorno 20 apr 2024, 21:50, alle ore 21:50, Marc Laventure ***@***.***> ha scritto:

**Comment by marclave** [comment]
@clabnet which version of scalar are you running? :) it should show in your lock file/package.json :)

**Comment by clabnet** [comment]
@marclave   The scalar versions contained into PLT 1.36.1 are:
- @scalar/fastify-api-reference **1.21.0**
- @platformatic/scalar-theme **1.35.2**

**Comment by marclave** [comment]
@clabnet could you update @scalar/fastify-api-reference to latest version `1.22.3` :)

**Comment by clabnet** [comment]
Yes, it works! Thanks @marclave
