### ISSUE TITLE
Show name of the schema instead of `Show Child Attributes`

### ISSUE THREAD

**Issue by marclave** [scalar/scalar#1473]
### Discussed in [https://github.com/scalar/scalar/discussions/1454](https://github.com/scalar/scalar/discussions/1454)

Originally posted by **kovapatrik** April 18, 2024
When a schema has a reference to another, it shows in the API reference as `Show Child Attributes`. But if I have a `oneOf` or `allOf` field like this, it would be nice to know which schema is which.

![image](https://uploads.linear.app/06a32804-030f-45a1-98aa-79d02a076af5/052af9b0-8868-4f5d-a562-f46864451de3/1ce3f113-5fcf-4d40-a14b-2e6ce1a94f13?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzA2YTMyODA0LTAzMGYtNDVhMS05OGFhLTc5ZDAyYTA3NmFmNS8wNTJhZjliMC04ODY4LTRmNWQtYTU2Mi1mNDY4NjQ0NTFkZTMvMWNlM2YxMTMtNWZjZi00ZDQwLWExNGItMmU2Y2UxYTk0ZjEzIiwiaWF0IjoxNzEzNzk2MDc2LCJleHAiOjMzMjg0MzU2MDc2fQ.Pl-3LlA90vyF0A_wmuGAFIu-GIPxW9FcC-cY82d5pmI "=290x")

**Comment by hanspagel** [comment]
That’s such a great idea!
