### ISSUE TITLE
Display response schemas (similar to Redoc)

### ISSUE THREAD

**Issue by marclave** [scalar/scalar#1481]
### Discussed in [https://github.com/scalar/scalar/discussions/1268](https://github.com/scalar/scalar/discussions/1268)

Originally posted by **Schnorts** March 20, 2024
Redoc:

![image](https://uploads.linear.app/06a32804-030f-45a1-98aa-79d02a076af5/f026f60d-e164-4ce6-abaf-e1eb24c73c6c/fe012d91-70ed-4d23-8b08-921747de3c02?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzA2YTMyODA0LTAzMGYtNDVhMS05OGFhLTc5ZDAyYTA3NmFmNS9mMDI2ZjYwZC1lMTY0LTRjZTYtYWJhZi1lMWViMjRjNzNjNmMvZmUwMTJkOTEtNzBlZC00ZDIzLThiMDgtOTIxNzQ3ZGUzYzAyIiwiaWF0IjoxNzEzODgxNDg5LCJleHAiOjMzMjg0NDQxNDg5fQ.6mDkQCtcpkj98e5IZ5tj1p89Qm1EAqknjHt4Tm7-k98 "=1490x")

vs. Scalar:

![image](https://uploads.linear.app/06a32804-030f-45a1-98aa-79d02a076af5/2a1205b3-24d6-4734-827c-0f910ad96129/7eb6c410-c3af-4870-8827-c1b0664b7f94?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzA2YTMyODA0LTAzMGYtNDVhMS05OGFhLTc5ZDAyYTA3NmFmNS8yYTEyMDViMy0yNGQ2LTQ3MzQtODI3Yy0wZjkxMGFkOTYxMjkvN2ViNmM0MTAtYzNhZi00ODcwLTg4MjctYzFiMDY2NGI3Zjk0IiwiaWF0IjoxNzEzODgxNDg5LCJleHAiOjMzMjg0NDQxNDg5fQ.T2H6lbQuBEcl87Ks-i4IVr2vWFVzuh5Aue8VgdnLi1s "=1711x")

**Comment by Lumca** [comment]
This would be awesome! :)

**Comment by Ryan2018-js** [comment]
+1

**Comment by soGit** [comment]
@hanspagel do you already have a design idea (UI/UX)?  I want to create a MR for this functionality, check the video bellow:
https://github.com/scalar/scalar/assets/10682798/e898098f-07b6-402d-9eb1-9a0b6b0de25e

**Comment by j-z10** [comment]
@hanspagel Hi, thanks for your work on this project. Do you have any updates about this feature? It would be really helpful to us.

**Comment by lucasbledsoe** [comment]
This is the one thing preventing us from adopting scalar. Would love to see it!

**Comment by marclave** [comment]
o m g

here we are! the wonderful @soGit set the foundation and did bulk of the work for this! it's in the latest scalar release 😎 

https://github.com/scalar/scalar/pull/2832

@lucasbledsoe @j-z10 @Lumca

**Comment by Lumca** [comment]
This is absolute madness, thank you for developing this one!

**Comment by marclave** [comment]
@Lumca @soGit @lucasbledsoe @j-z10 we got this released in https://github.com/scalar/scalar/pull/2832 so we can close this :)
