### ISSUE TITLE
MIT License in standalone.js

### ISSUE THREAD

**Issue by marclave** [scalar/scalar#1482]
### Discussed in https://github.com/scalar/scalar/discussions/1335

<div type='discussions-op-text'>

<sup>Originally posted by **Alvie** March 28, 2024</sup>
Hi!

I want to use this but I am a little confused about the MIT Licensing. From what I understand, is that I need to include the copyright notice and the license with the "software", but I am retrieving it with NPM and only exposing the standalone.js

I am not too familiar with how licenses work, I want to include the copyright notice and the license info, but do I need to do this separately. Perhaps it should be included in the standalone.js instead?
https://github.com/scalar/scalar/discussions?discussions_q=MIT+License+in+standalone.js%3F
Sorry if this is a very nooby question 😅 
</div>

**Comment by Alvie** [comment]
Thanks for creating this issue! I'll be sure to update my @scalar/api-reference once it is done

**Comment by hanspagel** [comment]
You’re right, this wasn’t very clear. MIT is basically the "do whatever you want" license, so people do with the code whatever they want. But looking at the license it totally makes sense to expect it to be part of the output. [What we did](https://github.com/scalar/scalar/pull/1512) is to add a tiny header with a link to the LICENSE:

https://github.com/scalar/scalar/blob/404227c5f409356fdf9388be42b53df7789e19d2/packages/api-reference/license-banner.txt

Not released yet, but we’ll probably release it later this day. What do you think? Does this help?

**Comment by hanspagel** [comment]
Oops, that automation wasn’t helpful.

**Comment by Alvie** [comment]
> You’re right, this wasn’t very clear. MIT is basically the "do whatever you want" license, so people do with the code whatever they want. But looking at the license it totally makes sense to expect it to be part of the output. [What we did](https://github.com/scalar/scalar/pull/1512) is to add a tiny header with a link to the LICENSE:
> 
> https://github.com/scalar/scalar/blob/404227c5f409356fdf9388be42b53df7789e19d2/packages/api-reference/license-banner.txt
> 
> Not released yet, but we’ll probably release it later this day. What do you think? Does this help?

Thanks, I think it looks good :) I guess this is more up to you how you want to apply it. I think you might want to add a copyright notice, examples:
```
Copyright 2023-2024 Scalar (https://github.com/scalar/scalar/graphs/contributors)
Copyright: Scalar
(c) Scalar and other contributors
```
Look at how bootstrap does it and explains it:
https://getbootstrap.com/docs/4.1/about/license/
https://github.com/scalar/scalar/discussions/1335#discussioncomment-8943851

Or jQuery

```js
/*! jQuery v3.7.1 -ajax,-ajax/jsonp,-ajax/load,-ajax/script,-ajax/var/location,-ajax/var/nonce,-ajax/var/rquery,-ajax/xhr,-manipulation/_evalUrl,-deprecated/ajax-event-alias,-effects,-effects/animatedSelector,-effects/Tween | (c) OpenJS Foundation and other contributors | jquery.org/license */
```
https://code.jquery.com/jquery-3.7.1.slim.min.js

But I'm not an expert on this matter, it's more of a legal thing I guess, and it's up to you how to enforce it. I just didn't want to fall foul of the rules by accident 😅
