### ISSUE TITLE
allow multiple specs for Nuxt integration

### ISSUE THREAD

**Issue by marclave** [scalar/scalar#1500]
### What happens?

currently if youre using the Nuxt integration you can only use one spec (or nitro)

### What did you expect to happen?

allow to pass in an array

### How can we reproduce the issue?

integrate with latest @scalar/nuxt
https://www.npmjs.com/package/@scalar/nuxt

**Comment by hanspagel** [comment]
What does that look like? Like really multiple specifications? Or a single specification with multiple files?

**Comment by amritk** [comment]
would probably need to change our config to include path per file. Or maybe the whole config is just an array

**Comment by marclave** [comment]
> would probably need to change our config to include path per file. Or maybe the whole config is just an array

i think we can do smth similar to Docusaurus https://github.com/scalar/scalar/blob/main/packages/docusaurus/README.md#usage

you can pass in an array of scalar plugins really simply, but right now its not clear how to do that w nuxt or nitro : )

**Comment by max06** [comment]
Perfect timing!
My nuxt app provides 2 different APIs, I'd really love to be able to show both. (Although I'd have to figure out first how to separate my generators properly 😅 )

**Comment by amritk** [comment]
@max06 so you have two different open api spec files that you wish to display at two different routes?

**Comment by max06** [comment]
@amritk That sounds correct, yep. 

(We have one api for single resources, and one "flowapi" for complex scenarios consisting of individual single resources)
