### ISSUE TITLE
Response schema not rendered when it has circular type 

### ISSUE THREAD

**Issue by TimoGlastra** [scalar/scalar#1511]
### What happens?

When using a circular type in response objects, the `Show Schema [ ]` button on a response will not show the response schema. If the circular type is removed, it will render correctly.

I know it's really pushing the limits of API definitions, however it seems seems to handle the recursion fine for the Models sections. I think the issue here is that it should be rendered to a JSON object, and the recursion means that it will never finish construction the JSoN (as there's always another layer)

This is also given as error when i click "Show Schema":

```
Unhandled Runtime Error
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'anyOf' -> object with constructor 'Object'
    |     index 3 -> object with constructor 'Object'
    --- property 'additionalProperties' closes the circle
```

### What did you expect to happen?

I expect the schema in the response to render, maybe using a `$ref` for circular types, or showing something like an object where the value is a comment noting it's a circular type.

### How can we reproduce the issue?

1. Go to https://sandbox.scalar.com/e/ub9yy and look at the response type of example endpiont. Click on `Show Schema [ ]` and see that nothing shows. If you remove the circular type (e.g. remove `JsonObject` from `JsonValue`, it will render correctly. 

### Swagger/OpenAPI Example

https://sandbox.scalar.com/e/ub9yy

**Comment by hanspagel** [comment]
Ah! Never thought this, thanks for reporting!

**Comment by hanspagel** [comment]
Came up with a suggested fix here: https://github.com/scalar/scalar/pull/1514 :)
