### ISSUE TITLE
cURL snippets and playground not rendered properly + errors reading openapi.json file

### ISSUE THREAD

**Issue by xoelop** [scalar/scalar#1513]
### What happens?

The Scalar version of our API, hosted at [api.theirstack.com](https://api.theirstack.com) don't show

Our OpenAPI JSON can be found at https://api.theirstack.com/openapi.json, automatically generated with FastAPI. We also have a Swagger/OpenAPI page that renders properly at [api.theirstack.com/openapi](https://api.theirstack.com/openapi).

In the main page, cURL and code snippets aren't properly generated
![image](https://github.com/scalar/scalar/assets/8508402/789222d0-4fad-4700-947b-2240e75fd47e)

And in the HTTP playground, none of the body/headers/cookies is populated or editable
![image](https://github.com/scalar/scalar/assets/8508402/96db3b83-63c1-4a7f-a2c1-092623c3f887)

This is what the console shows
```
api-reference:38 Please open an issue on https://github.com/scalar/scalar
 Scalar OpenAPI Parser Warning:
 Array(3)0: {start: {…}, end: undefined, error: ': if must match "then" schema', path: '/components/securitySchemes/OAuth2PasswordBearer'}1: {start: {…}, end: undefined, error: ': if must match "else" schema', path: '/components/securitySchemes/OAuth2PasswordBearer'}2: {start: {…}, end: undefined, error: ': format must match format "uri"', path: '/components/securitySchemes/OAuth2PasswordBearer/flows/password/tokenUrl'}end: undefinederror: ": format must match format \"uri\""path: "/components/securitySchemes/OAuth2PasswordBearer/flows/password/tokenUrl"start: {line: 1, column: 1, offset: 0}[[Prototype]]: Objectlength: 3[[Prototype]]: Array(0)
(anonymous) @ api-reference:38
api-reference:19 TypeError: Cannot read properties of undefined (reading 'username')
    at BT (api-reference:26:656544)
    at api-reference:38:664257
    at r (api-reference:19:2864)
    at rr (api-reference:21:2908)
    at Proxy.<anonymous> (api-reference:38:206620)
    at mn (api-reference:19:3180)
    at le.l [as fn] (api-reference:21:19813)
    at le.run (api-reference:14:1475)
    at F.e.update (api-reference:21:20095)
    at F (api-reference:21:20122)
(anonymous) @ api-reference:19
api-reference:19 TypeError: Cannot read properties of null (reading 'length')
    at QT (api-reference:26:656140)
    at api-reference:38:662751
    at xn.deep (api-reference:38:663111)
    at Qt (api-reference:19:54)
    at Ft (api-reference:19:124)
    at S (api-reference:19:5175)
    at An (api-reference:19:5433)
    at xn (api-reference:19:4393)
    at setup (api-reference:38:662612)
    at Qt (api-reference:19:54)
(anonymous) @ api-reference:19
api-reference:19 TypeError: Cannot read properties of undefined (reading 'username')
    at BT (api-reference:26:656544)
    at api-reference:38:664257
    at r (api-reference:19:2864)
    at rr (api-reference:21:2908)
    at Proxy.<anonymous> (api-reference:38:206620)
    at mn (api-reference:19:3180)
    at le.l [as fn] (api-reference:21:19813)
    at le.run (api-reference:14:1475)
    at F.e.update (api-reference:21:20095)
    at F (api-reference:21:20122)
(anonymous) @ api-reference:19
api-reference:19 TypeError: Cannot read properties of null (reading 'length')
    at QT (api-reference:26:656140)
    at api-reference:38:662751
    at xn.deep (api-reference:38:663111)
    at Qt (api-reference:19:54)
    at Ft (api-reference:19:124)
    at S (api-reference:19:5175)
    at An (api-reference:19:5433)
    at xn (api-reference:19:4393)
    at setup (api-reference:38:662612)
    at Qt (api-reference:19:54)
(anonymous) @ api-reference:19
```

### What did you expect to happen?

I'd expect the cURL commands to be populated, as well as the body parts of the HTTP client that pops up when clicking on Test Request. 

If I upload the openapi.json file to the scalar.com website, it works as expected and this is what I see

![image](https://github.com/scalar/scalar/assets/8508402/2786d755-54a5-4588-9efb-cbf68ef4811b)

![image](https://github.com/scalar/scalar/assets/8508402/fcde0ce2-ec89-4b0e-8203-32352e4abbff)

### How can we reproduce the issue?

Open an html file with these contents on your browser:

```html
<!doctype html>
<html>

<head>
    <title>TheirStack API Reference</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
</head>

<body>
    <script id="api-reference">
    </script>

    <script>
        var configuration = {
            "title": "TheirStack API Reference",
            "isEditable": false,
            "spec": {
                "url": "https://api.theirstack.com/openapi.json"
            },
            "proxyUrl": "https://api.scalar.com/request-proxy",
            "darkMode": false,
            "layout": "modern",
            "theme": "default",
            "showSidebar": true,
            "searchHotKey": "k",
            "metaData": {},
            "customCss": "",
            "hiddenClients": [],
            "authentication": {
                "preferredSecurityScheme": "Bearer",
                "http": {
                    "bearer": {
                        "token": null
                    }
                }
            }
        }

        var apiReference = document.getElementById('api-reference')
        apiReference.dataset.configuration = JSON.stringify(configuration)
    </script>
    <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>
</body>

</html>
```

### Swagger/OpenAPI Example

https://api.theirstack.com/openapi.json

**Comment by hanspagel** [comment]
Thanks for reporting! Smells like it’s coming from our OpenAPI parser. 🤔  We’ll look into this.

**Comment by hanspagel** [comment]
One finding: The example response can not be shown, because it has an empty schema.

```diff
{
  "responses": {
   "200": {
   "description": "Successful Response",
   "content": {
     "application/json": {
+       "schema": {}
     }
   }
  }
}
```

**Comment by hanspagel** [comment]
The request example renders properly for me: https://sandbox.scalar.com/e/aqsWl

<img width="432" alt="Screenshot 2024-04-24 at 13 41 08" src="https://github.com/scalar/scalar/assets/1577992/b8662da4-0c46-4d2f-9b80-fccabb0e8bb6">

The error message you posted says something about `username` which is only used by the HTTP Basic Authentication, but this is not defined in your OpenAPI specification. Can you help me to understand how that happened? Can you reload the docs and make sure you choose `Authentication: None` in the first section? And then let me know if at least this works for you. 🤔 

<img width="443" alt="Screenshot 2024-04-24 at 13 42 44" src="https://github.com/scalar/scalar/assets/1577992/69c28baf-8c67-45dd-9b60-65ea98deb62b">

**Comment by xoelop** [comment]
Thanks for taking a look. I found a solution to my issue: adding a `basic` section to the `authentication` section makes the cURL snippets include request bodies properly. Plus, passing `null` to the `http.bearer.token` makes it fail too, it only works when passing a string.

So passing this

```json
            "authentication": {
                "preferredSecurityScheme": "Bearer",
                "http": {
                    "bearer": {
                        "token": "null"
                    },
                    "basic": {
                        "username": "user",
                        "password": "pass"
                    }
                }
            }
```

Instead of of this

```json
            "authentication": {
                "preferredSecurityScheme": "Bearer",
                "http": {
                    "bearer": {
                        "token": null
                    }
                }
            }
```

Setting `Authentication: None` in the first section didn't change anything.

And regarding this `One finding: The example response can not be shown, because it has an empty schema` I'm aware, we're not showing a response for one endpoint because its schema can vary, but the request body should have been shown regardless of that in the snippets.

**Comment by darcyclarke** [comment]
Ran into this issue myself, wasn't sure what was going on but @xoelop's hack worked; wondering if there's a more permanent fix out there.
