### ISSUE TITLE
Markdown images are not supported in endpoint description

### ISSUE THREAD

**Issue by deka** [scalar/scalar#1543]
### What happens?

Hi,

According to this line, `withImages` props is not set (default value is false) : https://github.com/scalar/scalar/blob/2700c5c9ad4ab555ff5404ead0c6874ec61136ae/packages/api-reference/src/components/Content/Operation/EndpointDetails.vue#L18

- OpenAPI V3.1

### What did you expect to happen?

Markdown images support in endpoints descripions
 
Is it possible to enable image support? or make it configurable ?

### How can we reproduce the issue?

With MarkdownRender unit test ?

**Comment by hanspagel** [comment]
Definitely possible! What are you using the images for in the endpoint description!

**Comment by deka** [comment]
@hanspagel 👌!
