### ISSUE TITLE
Global CSS cannot be imported from within node_modules

### ISSUE THREAD

**Issue by gsidsid** [scalar/scalar#1564]
### What happens?

This has been an issue when using Scalar on pretty much every Next.js project I've tried it on. There usually is a workaround but it isn't straightforward.

### What did you expect to happen?

If there was a simple way to pull styles externally that'd be ideal. Afaik the only way to really resolve this manually is by serving Scalar out of the API routes directory or by messing with CSS loaders.

### How can we reproduce the issue?

Try using Scalar as a react component on any non-api route page in a Next JS app.

**Comment by amritk** [comment]
Hey  @gsidsid  could you please provide a minimal reproduction? We will be building a proper Next.js integration, but maybe we can get something working in the meantime.

I just opened an issue to track the next.js integration work that you can subscribe to.
https://github.com/scalar/scalar/issues/1565

**Comment by gsidsid** [comment]
Will try and spin up a repo later. I'm currently trying to use Scalar in [Nextra's](https://nextra.site/) docs template, which would be one way to hit this error.

**Comment by amritk** [comment]
Hey @gsidsid, styles are now external!
