### ISSUE TITLE
Custom MetaData not reflecting in the express integration.

### ISSUE THREAD

**Issue by NinadJoshi222** [scalar/scalar#1623]
### What happens?

```
On adding the title and description and the other fields in the metaData section in the express integration, there is no changes taking place.
```

### What did you expect to happen?

```
Expected title of the webpage to update as per the provided custom title.
```

Custom Title expected to be "My Custom Title" but stays as API Reference

![image](https://uploads.linear.app/06a32804-030f-45a1-98aa-79d02a076af5/d5ab66ec-9cc3-4672-a1f2-b7c16b880bd0/527e23e6-08c2-4c09-ad2d-89a7b1838541?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzA2YTMyODA0LTAzMGYtNDVhMS05OGFhLTc5ZDAyYTA3NmFmNS9kNWFiNjZlYy05Y2MzLTQ2NzItYTFmMi1iN2MxNmI4ODBiZDAvNTI3ZTIzZTYtMDhjMi00YzA5LWFkMmQtODlhN2IxODM4NTQxIiwiaWF0IjoxNzE1MzUwNzYyLCJleHAiOjMzMjg1OTEwNzYyfQ.wreK2R1z_2zT2NGT2wsP8K3s-3ldLdSzBbZscXDUs_0)

### How can we reproduce the issue?

While configuring the apiReference add the metaData field as a key and the required parameters inside it as shown below:

```
Code:-
app.use(
    "/api-docs",
    apiReference({
        layout: "modern",
        theme: "default",
        spec:{
            content:apiData,
        },
        metaData: {
          title: 'My Custom Title',
          description: 'My page page',
      },
    })
);
```

**Comment by hanspagel** [comment]
Thanks for reporting!

Relevant #709

**Comment by foxted** [comment]
Same issue for the Nest.js integration.

**Comment by fellipeutaka** [comment]
Same here for the Fastify integration
