### ISSUE TITLE
Automatically expand all sections

### ISSUE THREAD

**Issue by lys623** [scalar/scalar#1663]
### What happens?

![image](https://github.com/scalar/scalar/assets/4364314/598d56d2-46de-4a89-bc32-6e247b625e71)

### What did you expect to happen?

how to set showmore button automatically expands

### How can we reproduce the issue?

how to set showmore button automatically expands

**Comment by amritk** [comment]
@lys623 when would you like it to open? For a big spec we probably shouldn't open it by default as it'll be too slow, but would you like it to open when you scroll down?

**Comment by lys623** [comment]
> @lys623 when would you like it to open? For a big spec we probably shouldn't open it by default as it'll be too slow, but would you like it to open when you scroll down?

yes, pls help to open when scroll down, Or can  expose a method to control opening？

**Comment by amritk** [comment]
Yea we had this before, maybe we can add it as a config option @marclave @hanspagel what do you think?

**Comment by lys623** [comment]
> Yea we had this before, maybe we can add it as a config option @marclave @hanspagel what do you think?

@marclave @hanspagel  pls help

**Comment by lys623** [comment]
this feature very important , Hope to support it，can see grab website, it render the entire document https://developer.grab.com/docs/grabfood/api/v1-1-3/#section/Introduction/Key-takeaways

**Comment by lys623** [comment]
@amritk @marclave @hanspagel Hello. Any progress on this？

**Comment by lys623** [comment]
I really need your help. Can you take a look @hanspagel

**Comment by amritk** [comment]
yea this comes down to a product question, tagging @marclave who should be back

**Comment by amritk** [comment]
But also just so you are aware @lys623 we do some smart caching using these buttons, having them open by default will cause some lag

**Comment by lys623** [comment]
I need to make it expand by default, is there any way to do that now

**Comment by lys623** [comment]
Any progress on this? thank you. @hanspagel @amritk

**Comment by lys623** [comment]
Hello, is there a solution for this? Our requirement is going live soon and we need this feature @hanspagel @amritk

**Comment by marclave** [comment]
@lys623 i'll tackle it right now

**Comment by marclave** [comment]
sorry about the delay :)

**Comment by lys623** [comment]
> @lys623 i'll tackle it right now

Thank you for your reply，Looking forward to its launch

**Comment by lys623** [comment]
import { ApiReferenceReact } from '@scalar/api-reference-react'

I use this npm package. If this requirement is supported, please upgrade the version of this package

**Comment by marclave** [comment]
@lys623 being worked on in here :)

https://github.com/scalar/scalar/pull/2479

**Comment by lys623** [comment]
@marclave Hello, the function is still not implemented, maybe I did not express it clearly，I want the content to expand, not just tag。
![image](https://github.com/user-attachments/assets/a28a546c-54ae-49f5-84eb-8b522aa53f4e)

**Comment by lys623** [comment]
Hello. Any progress on this？  @marclave @amritk

**Comment by marclave** [comment]
hi @lys623 https://github.com/scalar/scalar/blob/main/documentation/configuration.md#defaultopenalltags-boolean

so this configuration option didnt work for you? I just tested and it did for a my spec :)  

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/cddb0e45-4c53-4d1e-9514-32b74543b6ba">


and all the sidebar is open too

**Comment by lys623** [comment]
yes, in my prd, i need to set 'showSidebar' to false, then we can see this function not work ;

https://github.com/lys623/scalar-api-reference-react-demo a minimal reproducible repository , pls help to check.

error link: http://localhost:3000/docs @marclave

**Comment by lys623** [comment]
We need to customize the left sidebar, because the content not just  one <ApiReferenceReact ../> component, 

maybe look like :

<div>
  <MdxComponent />
  <ApiReferenceReact .../> 
  <MdxComponent />
  <MdxComponent />
  <ApiReferenceReact .../> 
</div>

**Comment by lys623** [comment]
@marclave hi, any update？

**Comment by lys623** [comment]
@marclave Hello, can you help me look into this problem？

**Comment by lys623** [comment]
> yes, in my prd, i need to set 'showSidebar' to false, then we can see this function not work ;
> 
> https://github.com/lys623/scalar-api-reference-react-demo a minimal reproducible repository , pls help to check.
> 
> error link: http://localhost:3000/docs @marclave

@marclave hello, Can you help me look at the problem
