### ISSUE TITLE
show nested examples (remove ellipsis)

### ISSUE THREAD

**Issue by marclave** [scalar/scalar#1664]
### What happens?

![image](https://github.com/scalar/scalar/assets/6176314/fbc75e91-8a68-4a68-a1d1-ae0df6dab5af)

### What did you expect to happen?

... is removed and you can show the examples :) 

### How can we reproduce the issue?

✨

**Comment by hanspagel** [comment]
The screenshot shows nested request query params and has an arrow pointing to the example response body. Can you give me more information? IIRC it had something nested in the response schema, do you know more? 🤔

**Comment by marclave** [comment]
ah the arrow isnt pointing from query params, but rather showing the "…" and we should show the example values from the body if we have them

**Comment by hanspagel** [comment]
I somehow like the idea to be clever and use values from a `requestBody` to prefill the `responses` and I started to work on this. It feels a little bit wrong, though. Let’s say we have a request body, that looks like this:

```json
{
  "title": "Mars",
  "data": {
    "size": "XL"
  }
}
```

and the actual API would respond with a nested structure:

```diff
{
  "status": "created",
  "data": {
+    "title": "Mars",
+    "data": {
+      "size": "XL"
+    }
  }
}
```

Our **generated example response** would then look like this:

```diff
{
  "status": "created",
  "data": {
+    "size": "XL"
  }
}
```

That would be straight up wrong. 😬 Wdyt @marclave?
