### ISSUE TITLE
remove Microsoft.AspNetCore.OpenApi from Scalar.AspNetCore

### ISSUE THREAD

**Issue by marclave** [scalar/scalar#1738]
### What happens?

https://github.com/scalar/scalar/pull/1737#discussion_r1600817974

### What did you expect to happen?

remove duplicated package

### How can we reproduce the issue?

install latest

**Comment by xC0dex** [comment]
@marclave This issue can be closed. We no longer have this dependency. It was removed in https://github.com/scalar/scalar/pull/2722

**Comment by hanspagel** [comment]
So cool! :)
