### ISSUE TITLE
consume the data URL in the config object

### ISSUE THREAD

**Issue by marclave** [scalar/scalar#1739]
### What happens?

currently the scalar dotnet integration does not include reference to the data url

### What did you expect to happen?

the scalar dotnet integration should include reference to the data url

### How can we reproduce the issue?

no config is linked

**Comment by xC0dex** [comment]
I'm not sure what is meant by “data url”?

**Comment by hanspagel** [comment]
Same :) @marclave

**Comment by marclave** [comment]
ah! this was fixed sorry @xC0dex @hanspagel ✨
