### ISSUE TITLE
Blurry API client popup

### ISSUE THREAD

**Issue by edorgeville** [scalar/scalar#1751]
### What happens?

After upgrading `scalar/fastify-api-reference` to `1.22.38`, the new API client popup stays blurry after finishing its animation.
Interestingly, toggling the device toolbar in devtools (Ctrl+Shift+M) seems to be doing something right, making everything sharp again. Possibly hardware acceleration related?  

https://github.com/scalar/scalar/assets/2685884/e7495672-c214-483d-a1b1-fbc2482a01c1

(the video doesn't carry well the blurriness, unfortunately...)

I think #1720 attempted to fix the issue but the issue remains.

### What did you expect to happen?

No blur 🔍 

### How can we reproduce the issue?

Windows 10 22H2, Chrome 124.0.6367.158

**Comment by cameronrohani** [comment]
Hey @edorgeville I took another stab at it

https://github.com/scalar/scalar/pull/1752

would you be able to check out the preview deploy and let me know if this fixes it?

I haven't been able to replicate it on my end

**Comment by edorgeville** [comment]
Still blurry here. It definetly comes from the `transform: translate3d` animation, toggling it on/off goes blurry / crisp. I'll keep digging on my side as well as reproduction is going to be a pain 😅

**Comment by cameronrohani** [comment]
thanks so much for looking in to this @edorgeville 

Let's remove the transform for the time being:

https://github.com/scalar/scalar/pull/1753

**Comment by cameronrohani** [comment]
Okay let's change the way I position the pop up! Will ping you when I have a PR ready

**Comment by cameronrohani** [comment]
@edorgeville check the preview let me know if this fixes it 🤞

https://2d8652d9-3e37-41a0-adfb-1ee529825f98--scalar-deploy-preview.netlify.app/

**Comment by edorgeville** [comment]
You nailed it! Not blurry anymore.
I see #1753 has been merged, I'll close the current issue after testing the next release 🚀

**Comment by edorgeville** [comment]
Just tested with `"@scalar/fastify-api-reference": "^1.22.43"`, the issue is fixed. Thank you Cameron!
