### ISSUE TITLE
When using parameterized server URL, parameter editor not displayed on first load

### ISSUE THREAD

**Issue by lirc571** [scalar/scalar#1755]
### What happens?

When there are variables in the server URL, the Base URL section does not show an editor for those variables on first load.

### What did you expect to happen?

The variable editor should be displayed.

### How can we reproduce the issue?

Go to <https://docs.scalar.com/swagger-editor>, import URL <https://raw.githubusercontent.com/gravitee-io/gravitee-api-management/master/gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/resources/openapi/openapi-apis.yaml>,  after loading, there is no parameter editor:

![image](https://github.com/scalar/scalar/assets/111728589/186ac324-9f64-4834-bb16-e6475fb9c671)

(The screenshot above also shows that issue #1035 still exists)

But if we click the format code button on the top right corner of the spec editor, the parameter editor will appear:

![image](https://github.com/scalar/scalar/assets/111728589/3da167c1-dad8-455b-98ce-9d3a0c1b13ea)

### Swagger/OpenAPI Example

https://raw.githubusercontent.com/gravitee-io/gravitee-api-management/master/gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/resources/openapi/openapi-apis.yaml

**Comment by hanspagel** [comment]
Can confirm, it’s still there! I’ll fix this.
