### ISSUE TITLE
text/plain of response not shown correctly

### ISSUE THREAD

**Issue by ad-on-is** [scalar/scalar#1758]
### What happens?

If a response returns a text/plain with an example, UI only shows "no Body"

### What did you expect to happen?

Body should show the example text

### How can we reproduce the issue?

```yml
post:
      summary: " (store)"
      description: "\n\n _app/controllers/test_controller.ts_ - **store**"
      parameters: []
      tags:
        - "BEST"
      responses:
        401:
          description: "Returns **401** (Unauthorized)"
        403:
          description: "Returns **403** (Forbidden)"
        404:
          content:
            text/plain:
              example: "Product not found"
          description: "Returns **404** (Not Found) as **text/plain**"
```
![image](https://github.com/scalar/scalar/assets/9553253/31cdcd08-50be-4a58-b791-dc48d4f8500b)

**Comment by hanspagel** [comment]
Thanks for reporting! Let me check this!

**Comment by ad-on-is** [comment]
Swagger UI for comparison

![image](https://github.com/scalar/scalar/assets/9553253/9a79a55e-deda-4567-a055-6430d27d169a)

**Comment by hanspagel** [comment]
Submitted a PR. :)
