### ISSUE TITLE
Client Libraries Icons Not Appearing from CDN

### ISSUE THREAD

**Issue by srilman** [scalar/scalar#1777]
### What happens?

When testing the docs generation on `https://docs.scalar.com`, I see that the client libraries section at the top contains a nice row of icons for each language.

But when I tried deploying docs to a local server via the CDN approach, the client libraries display looks very different:

<img width="634" alt="Screenshot 2024-05-17 at 9 44 08 PM" src="https://github.com/scalar/scalar/assets/17444967/75d47358-60c5-45d4-af5a-d01e9019a184">

Is there a setting that I am missing?

### What did you expect to happen?

I expect to see the icons seen from the official docs source, like so:

<img width="646" alt="Screenshot 2024-05-17 at 9 41 18 PM" src="https://github.com/scalar/scalar/assets/17444967/d2676b89-4673-4cb5-af77-6c82e0746e86">

### How can we reproduce the issue?

This is the HTML that the docs are based on:
```
<body>
	<script
		id="api-reference"
		data-url="/openapi-3.0.json"></script>
	<script>
		var configuration = {
		  theme: 'purple',
		  hideModels: true, 
		}
		document.getElementById('api-reference').dataset.configuration =
		  JSON.stringify(configuration)
	</script>
	<script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>
</body>
```

**Comment by cameronrohani** [comment]
Hey @srilman 

This was an intentional design decision around continuous feedback that the intro section:
- Had too much contrast
- Too much vertical space

If you'd like you can add the following custom CSS to make the intro section _closer_ to the original design:

```
.client-libraries-content {
  gap: 6px;
}
.client-libraries-content .client-libraries {
  flex-direction: column;
  padding: 9px 0 !important;
  color: white !important;
}
.client-libraries-content .client-libraries svg {
  max-width: 20px;
  max-height: 20px;
}
.client-libraries-content .client-libraries:nth-of-type(1) {
  background:  #000;
}
.client-libraries-content .client-libraries:nth-of-type(2) {
  background:   #D91405;
}
.client-libraries-content .client-libraries:nth-of-type(3) {
  background:   #83CD29;
}
.client-libraries-content .client-libraries:nth-of-type(4) {
  background:   #6081B6;
}
.client-libraries-content .client-libraries:nth-of-type(5) {
  background:   #316898;
}
.client-libraries-content .client-libraries:nth-of-type(6) {
  background:   var(--scalar-background-3);
  color: var(--scalar-color-3) !important;
}
.client-libraries-content .client-libraries__active {
  background-color: transparent !important ;
  color: var(--scalar-color-1) !important;
  box-shadow: var(--scalar-shadow-1)  !important;
}
.dark-mode .client-libraries-content .client-libraries__active {
  box-shadow: 0 0 0 1px var(--scalar-color-1) !important
}
```

That being said we're always open to change and feedback so if a lot of people prefer the old design it is something we can iterate upon :)

**Comment by srilman** [comment]
Thanks for the quick response @cameronrohani. Good point that the old design took up too much vertical space; that was something I was worried about in general and was working to trim down the text for. I do like the old design more visually, but I was really mostly concerned that I'd somehow gotten an older version of the package because all of the screenshots in the repo and the docs generator used the old design.
