### ISSUE TITLE
Api search redirection not working properly 

### ISSUE THREAD

**Issue by jatingajera31** [scalar/scalar#1785]
### What happens?

when I search api from search box first time it will redirect to me to the api, when I try same step second time it's not redirect to the api.

### What did you expect to happen?

when I search the api and select that api so need to move to the api documentation.

### How can we reproduce the issue?

1.Go to scalar and search for api and click on it. it will move to the api.
2. Go above and close all api dropdown then again search the api and click on it.(Try most last api in swagger docs).
3.see the video

https://github.com/scalar/scalar/assets/55544548/4994f8f6-e98f-4984-be9a-b78123298504

**Comment by hanspagel** [comment]
@amritk Do you know that’s going on here? 🤔

**Comment by amritk** [comment]
I think it might not be waiting until the element exists before scrolling. Might need a mutation observer here

**Comment by amritk** [comment]
Hi @jatingajera31 I believe we wait for the element to exist now! Please re-open if its still an issue on the latest version
