### ISSUE TITLE
add GitHub issue templates

### ISSUE THREAD

**Issue by hanspagel** [scalar/scalar#18]
Suggestion:

**Get Help**
If you can't get something to work the way you expect, open a question in our discussion forums.

**Feature Request**
Suggest any ideas you have using our discussion forums.

**Bug Report**
If you've already asked for help with a problem and confirmed something is broken, create a bug report.

**Comment by ATREAY** [comment]
Hey @hanspagel, can I work on this issue?

**Comment by marclave** [comment]
@ATREAY absokutely you can :)

**Comment by ATREAY** [comment]
Hey @marclave, can you give me some pointers on what the feature request and bug report issue templates should include?

**Comment by hanspagel** [comment]
Let’s use that for the bug reports:
https://github.com/stevemao/github-issue-templates/blob/master/simple/ISSUE_TEMPLATE.md

And maybe that for feature requests (but without the table):
https://github.com/stevemao/github-issue-templates/blob/master/emoji-guide/Feature_request.md

**Comment by ATREAY** [comment]
Sure thing, @hanspagel! I'll use these and get back to work.

**Comment by ATREAY** [comment]
Hey @hanspagel, I have incorporated the issue templates. Kindly review them at your convenience.
