### ISSUE TITLE
Docusaurus: toast style missing background

### ISSUE THREAD

**Issue by federicobond** [scalar/scalar#1836]
### What happens?

In a Docusaurus site, when copying the request code to the clipboard, the toast that comes up does not have a background.

<img width="521" alt="Captura de pantalla 2024-05-23 a la(s) 9 55 54 a  m" src="https://github.com/scalar/scalar/assets/138426/c41fc850-c491-42ad-809c-79a9821b2a07">

### What did you expect to happen?

I would expect it to look roughly like what I see in the Scalar website:

<img width="461" alt="Captura de pantalla 2024-05-23 a la(s) 9 58 42 a  m" src="https://github.com/scalar/scalar/assets/138426/892a40d7-bff4-4dbf-a923-c6ec61ade1d4">

### How can we reproduce the issue?

1. Setup a Docusaurus 3.3 site
2. Configure the Scalar plugin
3. Click on the clipboard icon in a request on the right sidebar

**Comment by cameronrohani** [comment]
Thanks for all these great reports @federicobond, will get to this when I have a chance over the next day or two 😄

**Comment by federicobond** [comment]
Thank you 😊
