### ISSUE TITLE
Ability to use two auth methods at the same time

### ISSUE THREAD

**Issue by marclave** [scalar/scalar#1848]
### Discussed in https://github.com/scalar/scalar/discussions/1439

<div type='discussions-op-text'>

<sup>Originally posted by **mattoni** April 15, 2024</sup>
![image](https://github.com/scalar/scalar/assets/5110855/17c5df5e-3e0f-4046-bc6e-5f57d367bd92)

I have an API that utilizes two required authorization methods at the same time (bearer token and a special header). It would be nice if this allowed me to use both at the same time without having to manually provide the custom header for each request.</div>

**Comment by hanspagel** [comment]
We can do this, but I wonder how the UI would look like then? (`@scalar/api-reference` and `@scalar/api-client`)

**Comment by thelinuxlich** [comment]
+1 for this, I want the user to see all available security schemes for the endpoint

**Comment by matthias-hausberger** [comment]
+1 here. Coming from Gitbook (which uses the scalar client?), and our authentication also requires to custom headers for auth, a key and a secret. The UI only lets me switch between the two, although both are required. According to the [OpenAPI documentation](https://swagger.io/docs/specification/authentication/), a "pair" of API keys can be defined.

<img width="665" alt="Screenshot 2024-07-25 at 13 55 59" src="https://github.com/user-attachments/assets/4fcb6c64-5114-40ad-bd37-251119f8b98d">

Our security part is basically a copy from the [Multiple API Keys](https://swagger.io/docs/specification/authentication/api-keys/) authentication section of the OpenAPI docs.

**Comment by marclave** [comment]
👋 @matthias-hausberger ! this is something we are working on now that we have released our new api client : ) 

i'd expect next week we should have this implemented : )

**Comment by matthias-hausberger** [comment]
@marclave Ah that's awesome, that would be just in time for publishing our docs! I did notice that things are changing (Request name is properly displayed, authentication displays apiKey,..) so, nice that there's some movement :)

**Comment by AiRev-SebastianBienert** [comment]
Hi guys, do you have any update on this?

**Comment by matthias-hausberger** [comment]
@marclave any updates on this? 😬

**Comment by marclave** [comment]
@matthias-hausberger this is in the latest release done by @amritk :)
