### ISSUE TITLE
Support for HTML abbr tags

### ISSUE THREAD

**Issue by marclave** [scalar/scalar#1850]
### Discussed in https://github.com/scalar/scalar/discussions/1378

<div type='discussions-op-text'>

<sup>Originally posted by **cpbr-dev** April  4, 2024</sup>
Would love to see support for [HTML abbreviation elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/abbr#providing_an_expansion), specifically support for the title attribute.
I'm currently reworking API documentation for better accessibility and multiple acronyms are being used there which could benefit from this.</div>

**Comment by hanspagel** [comment]
#1860 👀
