### ISSUE TITLE
Authentication section does not handle oauth2 securitySchemes properly

### ISSUE THREAD

**Issue by swimand** [scalar/scalar#1859]
### What happens?

I have configured the openapi scheme to include a oauth2 securityScheme. The Scalar UI however does not present the option to authenticate properly. The image below shows the output when i have oauth2 with a "password" flow.
![image](https://github.com/scalar/scalar/assets/91246428/37899291-312f-4c0c-9fe5-b12882c504cd)

### What did you expect to happen?

I expected the possibility of entering the same values as shown in Swagger UI. Here are images of the values that swagger presents with the same openapi scheme, within the same application: 
![image](https://github.com/scalar/scalar/assets/91246428/09d0e00a-8ddf-4b40-9aad-b53c14bf7df0)

### How can we reproduce the issue?

Use the following schema to replicate in sandbox: 
```
{
  "openapi": "3.1.0",
  "info": {
    "title": "Hello World",
    "version": "1.0.0"
  },
  "paths": {},
  "components": {
    "securitySchemes": {
      "auth": {
        "type": "oauth2",
        "flows": {
          "password": {
            "tokenUrl": " /v1/token",
            "scopes": {}
          }
        }
      }
    }
  }
}
```

or create a new python fastapi project with scalar and configure a schema with the following code: 

```
        openapi_schema["components"]["securitySchemes"] = {
            "auth": {
                "type": "oauth2",
                "flows": {
                    "password": {
                        "tokenUrl": api_config.path + "/v1/oauth2/token",
                        "scopes": {}
                    }
                }
            }
        }
```

**Comment by hanspagel** [comment]
You’re so right. Let’s add this feature! On it.

**Comment by hanspagel** [comment]
Can you try again and let me know if it works?

**Comment by hanspagel** [comment]
Closing it for now, but let me know if you face any issues and I’ll reopen it in a heartbeat. 👍

**Comment by swimand** [comment]
Looks great! Fast work! 🤩
However there are a few parameters missing for full support, such as client secret and Client Credentials Location. 

There is also a weird clipping occurring for the view password button and Authorize button: 

![image](https://github.com/scalar/scalar/assets/91246428/01c626e3-3c55-447c-b8d0-e8e7021e7fbb)

Is there a way to install this version on my application to also test out the actual login logic?
