### ISSUE TITLE
hiddenClients still defaults curl even when it is supposed be disabled

### ISSUE THREAD

**Issue by Lumca** [scalar/scalar#1861]
### What happens?

as mentioned here: https://github.com/scalar/scalar/issues/1250
I have setted:
`hiddenClients: { php: true, python: true, c: true, node: true, javascript: true, go: true, java: true, ruby: true, shell: true, clojure: true, csharp: true, kotlin: true, objc: true, swift: true, r: true, powershell: true, ocaml: true, curl: true, },
`
It still makes curl default:
![image](https://github.com/scalar/scalar/assets/4989415/29ed2518-17df-41a1-90a7-3406aa11da87)

and upon clicking there is only http
![image](https://github.com/scalar/scalar/assets/4989415/efcd3ebc-c18a-4cac-807a-7955025847d3)

thank you guys!

### What did you expect to happen?

show correct clients that is set in hiddenClients

### How can we reproduce the issue?

1. Set hiddenClients curl
2. Curl is still present

**Comment by hanspagel** [comment]
🙏 We’ll fix that
