### ISSUE TITLE
DELETE requests can have a body

### ISSUE THREAD

**Issue by gpsfl** [scalar/scalar#1876]
### What happens?

It's not possible to write a body for `DELETE` requests in the "Test Request" tool

### What did you expect to happen?

It should be possible, like for `POST` or `PUT` requests.

### How can we reproduce the issue?

1. Click on the `DELETE /test` operation
2. Click "Test request"

### OpenAPI Document

https://sandbox.scalar.com/e/Cxc-9

**Comment by antlio** [comment]
thanks @gpsfl for the issue 🙏
