### ISSUE TITLE
`@scalar/fastify-api-reference` requires ReferenceConfiguration type from `@scalar/api-reference`

### ISSUE THREAD

**Issue by Kalovelo** [scalar/scalar#1906]
### What happens?

When building a typescript node app without skipping library type-checking, build crashes as it cannot find `@scalar/api-reference`
![image](https://github.com/scalar/scalar/assets/45261205/fc0a5070-fbf5-4ac1-8f08-fa0847554652)

### What did you expect to happen?

Ability to build without setting `skipLibCheck` to true

### How can we reproduce the issue?

1. Create a fastify project with typescript
2. set `skipLibCheck: false`
3. Use `@scalar/fastify-api-reference` 
4. Try to build

**Comment by FrancoRATOVOSON** [comment]
Hi scalar team, I am facing the same issue, is there any solution ?

**Comment by amritk** [comment]
hello, we are currently working on a solution!
