### ISSUE TITLE
Nuxt: side menu basePath if set to '/' ignores host

### ISSUE THREAD

**Issue by laylatichy** [scalar/scalar#1942]
### What happens?

when pathRouting basePath is set to '/' main navigation redirects to 

https://tag/menu-element

instead of 

https://host/tag/menu-element

### What did you expect to happen?

correct redirect

### How can we reproduce the issue?

https://codesandbox.io/p/devbox/nuxt-playground-forked-32ms33

click on any menu item 
![image](https://github.com/scalar/scalar/assets/52243892/b3622613-f396-48a0-aa0f-ef7869e0543c)

edit: I actually see that codesandbox redirects almost correctly just // after host

![image](https://github.com/scalar/scalar/assets/52243892/0b2d4518-f069-49e6-a3c5-7226e80dd1cc)

nav link is still incorrect
![image](https://github.com/scalar/scalar/assets/52243892/95ef5b27-a96d-4b73-869c-091cfb3a8afb)

![image](https://github.com/scalar/scalar/assets/52243892/14087898-fbca-4c58-9cff-6edb2e48040e)

so that double / causes issue on localhost dev env unless we boot nuxt with custom host

edit2: culprit is here so with base path / it will be //id

https://github.com/scalar/scalar/blob/f82a76776be134c2f5263727fc912a287f8d330a/packages/api-reference/src/components/Sidebar/SidebarElement.vue#L48

**Comment by amritk** [comment]
lets do this a bit smarter!
