### ISSUE TITLE
Download Spec from original URL

### ISSUE THREAD

**Issue by hanspagel** [scalar/scalar#2003]
Currently, the Download Spec button downloads the content. It would have a few benefits to just make it a `<a href="…" download>` tag, though (if we have an URL for the specification):

* Copy the URL and use anywhere else
* View the content in the browser
* Get the original file, without any transformation

> Today you have a `Download API Spec` button for local downloads of the specification file.
> 
> That is great, but I see no way of getting the actual url of the JSON/YAML specification unless you view page source or ask the developer.
> 
> Can we make this visible on the documentation or change the download button to a link?
> 
> My use case is generating typescript types by pointing to the JSON/YAML specification
> 
> Thanks again.

_Originally posted by @michaelolof in https://github.com/scalar/scalar/discussions/1998_

> The default reference UI has a Download button, but it's a button element that prompts a download, I believe based on client-side information. If I supply a spec URL to run the reference page, I'd love to expose the URL of the `openapi.json` file so that API consumers can see/reference/use it as well.

_Originally posted by @tmcw in https://github.com/scalar/scalar/discussions/1911_

**Comment by Plasmadog** [comment]
I believe this issue was closed prematurely. The PR apparently just changes how the download button works, but it's still a download button, so it does nothing to address the first two of the bullet points:
- Copy the URL and use anywhere else
- View the content in the browser

**Comment by Rykuno** [comment]
Did this ticket ever get merged?
