### ISSUE TITLE
Can’t scroll to 2nd-level headings

### ISSUE THREAD

**Issue by hanspagel** [scalar/scalar#2004]
Initially, we only added the highest heading level (e.g. h1) to the sidebar. But at some point we changed it to show the two highest levels (e.g. h1 and h2) in the sidebar. 

Unfortunately, scrolling to the second level doesn’t work, because we’re only wrapping the highest level in a section.

> [Scalar sub-section.webm](https://github.com/scalar/scalar/assets/42624869/94bd24c9-133f-4444-a135-61193df48b6d)
> 
> When adding a H3 (###) to the description section, Scalar creates a sub-section in the left sidebar. However when the item menu is clicked, the page does not scroll to the selected sub-section.

_Originally posted by @Amorim33 in https://github.com/scalar/scalar/discussions/1954_

**Comment by tusharkaran** [comment]
@hanspagel  is this fixed ?

**Comment by hanspagel** [comment]
Submitted a PR. :)
