### ISSUE TITLE
Docusaurus: don't add routes automatically to the navbar

### ISSUE THREAD

**Issue by hanspagel** [scalar/scalar#2007]
### Discussed in https://github.com/scalar/scalar/discussions/1896

<div type='discussions-op-text'>

<sup>Originally posted by **kai687** May 29, 2024</sup>
Hi, 

I really like the Docusaurus plugin, but it seems like each API reference gets added automatically to the navbar. 

I would like to use this for a project with about 11 APIs, which you can imagine won't work so great. I like to manually control the navbar, so in this case, I want an "API reference" group and add all the APIs to this group. 

Would it be possible to change the behavior of the plugin?
I imagine, something like if the label is empty, no entry will be added to the navbar.
(Currently, an entry with 'scalar' gets added).</div>

**Comment by amritk** [comment]
We should allow an option to opt out

**Comment by mason-at-pieces** [comment]
@amritk I'd be down to help get this in if no one else has started on it

**Comment by amritk** [comment]
@mason-at-pieces sure I'm on vacation right now but it's a really easy change. Go ahead and take a stab at it!

**Comment by mason-at-pieces** [comment]
@amritk Here's the pr: https://github.com/scalar/scalar/pull/2763

**Comment by amritk** [comment]
Brilliant, thanks @mason-at-pieces !

closing https://github.com/scalar/scalar/pull/2763
