### ISSUE TITLE
Wrong HTTP header for security schema

### ISSUE THREAD

**Issue by sergeyzwezdin** [scalar/scalar#2030]
### What happens?

The following security schemas in the openapi spec:

```
    "securitySchemes": {
      "key": {
        "type": "apiKey",
        "name": "Authorization",
        "in": "header"
      },
      "token2": {
        "type": "apiKey",
        "name": "X-Api-Key",
        "in": "header"
      },
      "token3": {
        "type": "apiKey",
        "name": "X-ApiKey",
        "in": "header"
      },
      "token": {
        "type": "apiKey",
        "name": "X-Token",
        "in": "header"
      },
      "token5": {
        "type": "apiKey",
        "name": "X-Token5",
        "in": "header"
      }
    },
```

This displays correct selector in the UI:

![2024-06-12 at 07 20 10@2x](https://github.com/scalar/scalar/assets/800755/8f416e03-63d6-48e3-8e2e-17d14c51fa59)

Selecting `token` gives me `X-Token` header as expected.
Selecting anything else gives me `Authorization` header, which is a bug I guess.

### What did you expect to happen?

`key` → `Authorization`
`token2` → `X-Api-Key`
`token3` → `X-ApiKey`
`token` → `X-Token`
`token5` → `X-Token5`

### How can we reproduce the issue?

1. Create open api spec with a few security schema with api authorization
2. Try to run requests with different schemas

### OpenAPI Document

https://sandbox.scalar.com/e/t9hEH

**Comment by hanspagel** [comment]
We’re revamping the API Client, so I put this on hold and take another look once we upgrade to v2 of the API client. ✌️
