### ISSUE TITLE
Missing styling on markdown content

### ISSUE THREAD

**Issue by davidhu2000** [scalar/scalar#2134]
### What happens?

Updated to the latest version of `@scalar/api-reference-react@0.3.8`, and noticed that the `markdown` description of the spec no longer has any styles. 

The was working find in 0.2.x. 

0.2.5
![Screenshot 2024-06-17 at 2 38 09 PM](https://github.com/scalar/scalar/assets/15827041/02c1f0d7-a4df-4de8-83e6-ae207ef27c13)

0.3.8
![Screenshot 2024-06-17 at 2 37 16 PM](https://github.com/scalar/scalar/assets/15827041/a036078e-c7ae-4fb0-841a-e42767551fc8)

This appears to work in sandbox.scalar.com, maybe because that's the vue app? 

### What did you expect to happen?

Styles are applied to markdown content. 

### How can we reproduce the issue?

1. use `create-next-app` to initialize a new app
2. copy the following code into any `page.tsx`
3. see lack of styling on the intro section

```tsx
// docs/ui.tsx
"use client";

import { ApiReferenceReact } from "@scalar/api-reference-react";

export function UI({ spec }: { spec: any }) {
  return (
    <ApiReferenceReact
      configuration={{
        spec: { content: spec },
      }}
    />
  );
}

// docs/page.tsx
import { UI } from "./ui";

export default async function Page() {
  return (
    <UI
      spec={{
        openapi: "3.0.2",
        paths: {},
        info: {
          title: "API",
          version: "1.0.0",
          description: `

# Intro

The Scalar Galaxy is an example OpenAPI specification to test OpenAPI tools and libraries. It's a fictional universe with fictional planets and fictional data. Get all the data for all planets.

## Resources

* https://github.com/scalar/scalar
* https://github.com/OAI/OpenAPI-Specification
* https://scalar.com

## Markdown Support

All descriptions *can* contain ~~tons of text~~ **Markdown**. [If GitHub supports the syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax), chances are we’re supporting it, too.

<details>
  <summary>Examples</summary>

  **Blockquotes**

  > I love OpenAPI. <3

  **Tables**

  | Feature          | Availability |
  | ---------------- | ------------ |
  | Markdown Support | ✓            |

  **Accordion**

  \`\`\`html
  <details>
    <summary>Using Details Tags</summary>
    <p>HTML Example</p>
  </details>
  \`\`\`

  **Images**

  Yes, there’s support for images, too!

  ![Empty placeholder image showing the width/height](https://images.placeholders.dev/?width=1280&height=720)

</details>   
`,
        },
      }}
    />
  );
}
```

### OpenAPI Document

https://sandbox.scalar.com/e/qYxDo

**Comment by hanspagel** [comment]
Thanks for reporting! That seems off, we’ll investigate what’s wrong there.

**Comment by hanspagel** [comment]
Just tested Vite + React and this seems to work fine, but I just saw you’re using create-next-app. Will give this a try!

**Comment by davidhu2000** [comment]
yeah, maybe it's something specific to next. I'm using `"next": "14.2.3"`  with the app router. 

```
➜  my-app tree app
app
├── docs
│   ├── page.tsx
│   └── ui.tsx
├── favicon.ico
├── globals.css
├── layout.tsx
└── page.tsx

2 directories, 6 files
```

that's the app folder.

**Comment by hwkr** [comment]
Looks like this is an issue with the Scalar styles being overridden by the Tailwind preflight reset. We recently moved a bunch of are code into CSS layers and have been having some issues with this.

Currently working on removing some of that layer code and will try to get it merged ASAP.

**Comment by davidhu2000** [comment]
updated to 0.3.11, seems to work fine now

**Comment by hanspagel** [comment]
Awesome, thanks for letting us know!
