### ISSUE TITLE
Wrong example response for array with items that use allOf

### ISSUE THREAD

**Issue by macno** [scalar/scalar#2137]
### What happens?

The example response renders wrong objects in the array

### What did you expect to happen?

The example response is correct

### How can we reproduce the issue?

Use the provided example or clone this test repo https://github.com/macno/scalar-api-allOf-bug

### OpenAPI Document

https://sandbox.scalar.com/e/ZydCR

**Comment by antlio** [comment]
hey @macno thanks for the feedback! do you mind sharing a bit more about what would be your expectation in the response here? x

**Comment by macno** [comment]
Hi @antlio sure,

```
[
  {
    "eventName": "Australian Open",
    "eventType": "Sports",
    "eventSubType": "Tennis",
    "startDate": "2024-01-01",
    "endDate": "2024-01-05",
    "estimatedEventNumber": 100,
    "eventLocations": [
      {
        "locationId": "955",
        "label": "Stadium court"
      }
    ]
  }
]
```

also this is the output generated by swagger UI

<img width="724" alt="Screenshot 2024-06-18 at 11 14 53" src="https://github.com/scalar/scalar/assets/76600/d3251f8d-3eb3-4d60-891c-500adfbf5baf">

and by redoc
<img width="740" alt="Screenshot 2024-06-18 at 11 16 07" src="https://github.com/scalar/scalar/assets/76600/562bee4c-4c7b-4c64-aa77-0c6f1dc818c2">

**Comment by macno** [comment]
by the way I was looking at the source code to see if I can help with that, and I found [this](https://github.com/scalar/scalar/blob/main/packages/oas-utils/src/spec-getters/getExampleFromSchema.test.ts#L393) test which I'm not 100% sure it's correct. I'm doing some testing with other tools

**Comment by antlio** [comment]
awesome thanks for the infos, that what i thought. however this is what i seem to have from the scalar sandbox, am i missing something?

**Comment by macno** [comment]
In the sandbox I added 2 endpoints: the first one `/api/v1/locations/wrong` use the `allOf` definition and it is the one with the  issue.

the other one `/api/v1/locations/expected` uses a "flat" object, and it's there to show how it should render

**Comment by macno** [comment]
the example from the "wrong" endpoint looks like this:

```
[
  {
    "eventName": "Australian Open",
    "eventType": "Sports",
    "eventSubType": "Tennis",
    "startDate": "2024-01-01",
    "endDate": "2024-01-05",
    "estimatedEventNumber": 100
  },
  {
    "eventLocations": [
      {
        "locationId": "955",
        "label": "Stadium court"
      }
    ]
  }
]
```

**Comment by antlio** [comment]
omg yes, need more ☕ good catch

**Comment by macno** [comment]
the test I linked above use data like this
```
  Something:
      type: array
      items:
        allOf:
         - type: string
           example: foobar
         - type: string
           example: barfoo
```
which I really don't understand what would represent, but in other tools is rendered as:

```
[
  "barfoo"
]
```

so I guess the test is testing the wrong output

**Comment by antlio** [comment]
just open: https://github.com/scalar/scalar/pull/2140 as a proposal fix. regarding the test i'll let @hanspagel jump in!
