### ISSUE TITLE
Nuxt: `css` is unknown file extension

### ISSUE THREAD

**Issue by max06** [scalar/scalar#2141]
### What happens?

While rendering an openapi spec using scalar 0.2.8 in nuxt (3.12.1):

`Unknown file extension ".css" for /workspaces/nimbus/node_modules/@scalar/components/dist/style.css`

(Sorry for being here again 😂 )

### What did you expect to happen?

It should render the spec.

### How can we reproduce the issue?

1. Setup nuxt
2. Add scalar 0.2.8 with its config
3. Access rendered spec url (app links to that page are not working)

**Comment by hanspagel** [comment]
What’s this! 🫨 Thanks for the report. We’ll check what’s wrong there.

**Comment by eugenewere** [comment]
i also gor this error on nuxt module and api-refrence package

**Comment by marclave** [comment]
hi @eugenewere you get this for `@scalar/api-reference` outside of nuxt?

**Comment by eugenewere** [comment]
I am having issues with ssr being true in my project So i disabled it on my big project. I am guessing this nuxt module only works with ssr set to true. So i decided to download the api-reference package and handled it myself bt got the same error about css explained bt guy who posted this issue with same environment.

**Comment by eugenewere** [comment]
Just using nuxt

**Comment by marclave** [comment]
@eugenewere im investigating now!

**Comment by eugenewere** [comment]
@marclave  thank you

**Comment by platform-kit** [comment]
Also getting this error in Nuxt3. Node v22. Followed the docs on the module page exactly.

**Comment by Grawl** [comment]
Just faced this with Nuxt 4.
Then I found Nuxt 3 example in this repo, same. https://github.com/scalar/scalar/tree/main/examples/nuxt
