### ISSUE TITLE
Request always uses default value even if another value is provided

### ISSUE THREAD

**Issue by snigdha920** [scalar/scalar#2146]
### What happens?

Even if we provide a different value in the url params, the test request always the default value. 

https://github.com/scalar/scalar/assets/62167899/8b645647-2639-43e3-9e34-f693f8bd4350

### What did you expect to happen?

Use the value provided in the UI. 

### How can we reproduce the issue?

1. Clone https://github.com/snigdha920/swagger-ui-default-values-bug
2. Follow the steps in the readme: 

1. Comment out `default: 'world'` in the index.ts, and then try out the request on http://localhost:3000/swagger, the parameter `name` will not have a default value.
  
2. Put the `default: 'world'` back in the index.ts, and then try out the request on http://localhost:3000/swagger, the parameter `name` will always have a default value, even if another value is provided

**Comment by hanspagel** [comment]
I’ve tested this today and I can reproduce it in your setup, but not in our @scalar/api-reference core package. I’m a bit confused. But I’m on it. :)

**Comment by marclave** [comment]
hi @snigdha920 good news this is fixed in latest version of scalar! @scalar/api-reference@1.24.51

i cloned your repo and did a hard refresh and this worked : )


https://github.com/user-attachments/assets/62b5e2e0-9a81-42f3-ada7-dccb413c2561
