### ISSUE TITLE
pageTitle and JWT token are not set

### ISSUE THREAD

**Issue by TheSmartMonkey** [scalar/scalar#2158]
### What happens?

 In Hono Scalar pageTitle and JWT token are not set

### What did you expect to happen?

 In Hono Scalar pageTitle and JWT token are set

### How can we reproduce the issue?

1. Create a hono project : ` npm create hono@latest my-app`
2. Select cloudflare-workers and npm
3. `npm i`
4. Install packages : `npm i @hono/swagger-ui @hono/zod-openapi @scalar/hono-api-reference zod`
5. Add this code in `src/index.ts`

```ts
import { OpenAPIHono, createRoute, z } from '@hono/zod-openapi';
import { apiReference } from '@scalar/hono-api-reference';

const app = new OpenAPIHono();

app.doc('/public/api-json', {
  info: {
    title: 'An APIs test',
    version: 'v1',
  },
  openapi: '3.1.0',
});

app.get(
  '/public/api',
  apiReference({
    pageTitle: 'Create Hono Cloudflare Workers REST API',
    hideDownloadButton: true,
    authentication: {
      http: {
        basic: { username: '', password: '' },
        bearer: { token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.Fzyj62HwBhH2bNZkd9x1fd2s8TIuzUO8JmDMLAcPALY' },
      },
    },
    spec: {
      url: '/public/api-json',
    },
  }),
);

app.openapi(
  createRoute({
    method: 'get' as any,
    path: '/hello',
    responses: {
      200: {
        description: 'Respond a message',
        content: {
          'application/json': {
            schema: z.object({
              message: z.string(),
            }),
          },
        },
      },
    },
  }),
  (c) => {
    return c.json({
      message: 'hello',
    });
  },
);

export default app;
```

6. Run the server : `npm run dev`
7. Go to `http://127.0.0.1:8787/public/api`
8. Scalar pageTitle and JWT token are not set

**Comment by hanspagel** [comment]
You're right! I think #2085 will fix this. ✌️

**Comment by hanspagel** [comment]
Tested with the latest versions and both issues seem to be fixed. 🤝

**Comment by TheSmartMonkey** [comment]
I've just tested it's fixed for pageTitle but authentication with JWT is still not working

My repo if you want to test : https://github.com/TheSmartMonkey/create-hono-cloudflare-workers-rest-api
