### ISSUE TITLE
OpenAPI 3.1 webhooks are not displayed if x-tagGroups are used

### ISSUE THREAD

**Issue by hkosova** [scalar/scalar#2172]
### What happens?

Given an OpenAPI 3.1 file that contains both `x-tagGroups` (implemented in #1174) and `webhooks`, the webhooks are not displayed in the Scalar sidebar. This happens even if the webhooks use `tags` listed in `x-tagGroups`.

Without `x-tagGroups`:
<img width="271" alt="Screenshot 2024-06-19 at 16 51 09" src="https://github.com/scalar/scalar/assets/8576823/ddfc1fd0-746f-4d9e-99d0-9a53238c4f61">

With `x-tagGroups`:
<img width="274" alt="Screenshot 2024-06-19 at 16 52 29" src="https://github.com/scalar/scalar/assets/8576823/423347a5-e8a0-481e-a11e-bc86c533d2b3">

### What did you expect to happen?

The sidebar should still have the "Webhooks" category/group with a list of defined webhooks.

I think webhooks should always be displayed in `x-tagGroups` scenarios even if the webhooks themselves don't have `tags`.

### How can we reproduce the issue?

1. Go to https://sandbox.scalar.com.
2. Paste the text from
https://gist.githubusercontent.com/hkosova/e1b6ce4d72a3ec722ad4802d77f7e3e4/raw/fa790231d345af0c4779b01f6e81a7937a229030/webhooks-tag-groups.json
into the editor.
3. Examine the sidebar in the preview.

### OpenAPI Document

https://gist.githubusercontent.com/hkosova/e1b6ce4d72a3ec722ad4802d77f7e3e4/raw/fa790231d345af0c4779b01f6e81a7937a229030/webhooks-tag-groups.json

**Comment by hanspagel** [comment]
Thanks for the report! On it. :)

**Comment by hanspagel** [comment]
Submitted a PR: #2172 :)
