### ISSUE TITLE
Schema with anyOf section that contains two objects is rendered invalid

### ISSUE THREAD

**Issue by ItsEthra** [scalar/scalar#2218]
### What happens?

I have tried this schema(https://sandbox.scalar.com/e/1T1zN) for a path response. It has an `anyOf` section which consists of two objects and a normal property.

```json
{
  "title": "Foo",
  "type": "object",
  "anyOf": [
    {
      "type": "object",
      "required": [
        "a"
      ],
      "properties": {
        "a": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
    {
      "type": "object",
      "required": [
        "b"
      ],
      "properties": {
        "b": {
          "type": "string"
        }
      }
    }
  ],
  "required": [
    "c"
  ],
  "properties": {
    "c": {
      "type": "boolean"
    }
  }
}

```

The rendered model has only field `c` and don't show that there should be either field `a` or `b`. In request example it also shows extra `mode` and `omitEmptyAndOptionalProperties` fields for some reason, but does provide `a` field.
![image](https://github.com/scalar/scalar/assets/107059409/a52bb607-70c9-4ece-a547-eee5ae3192df)
If `anyOf` section is removed then `mode` and `omitEmptyAndOptionalProperties` fields disappear.

I stumbled upon this when generating docs from rust structures(I don't know much about json schemas and openapi spec) using `serde` and `schemars`. This may be common when you want to deserialize into a struct that can have one of two fields.
```rust
#[derive(Debug, Deserialize, JsonSchema)]
#[serde(untagged)]
enum Bar {
    A { a: i32 },
    B { b: String },
}

#[derive(Debug, Deserialize, JsonSchema)]
struct Foo {
    #[serde(flatten)]
    v: Bar,
    c: bool,
}
```

### What did you expect to happen?

I expected model to have a `c` field and show normal `anyOf` section to document that either `a` or `b` field must be present. I also expected request example to not have `mode` and `omitEmptyAndOptionalProperties` fields.

### How can we reproduce the issue?

1. Open https://sandbox.scalar.com/e/1T1zN
2. There are extra fields in the request example and fields `a`, `b` are missing from model definition.

### OpenAPI Document

https://sandbox.scalar.com/e/1T1zN

**Comment by hanspagel** [comment]
Thanks for the report! That’s one for me! 😁

**Comment by kevinand11** [comment]
Just noticed this now.. Thank God there is an issue opened already

**Comment by ItsEthra** [comment]
@hanspagel hey I might be wrong but I don't think this is fully fixed though, the fix only appears to remove extra example fields but docs for the model and path itself still do not include anyOf section for the fields a, b. (all using sandbox link in the original post)

![image](https://github.com/user-attachments/assets/6b5a8faf-1cc7-42db-8e39-83ac8eb71296)
![image](https://github.com/user-attachments/assets/dddad8f6-2bfe-4961-b56a-21005783b58f)
