### ISSUE TITLE
Styling of server inputs is missing

### ISSUE THREAD

**Issue by hanspagel** [scalar/scalar#2238]
When a server object has vairables, inputs are rendered. They lack the styling.

**Example**

https://sandbox.scalar.com/e/729nl

**Screenshot**

<img width="443" alt="Screenshot 2024-06-25 at 10 33 00" src="https://github.com/scalar/scalar/assets/1577992/a149e334-4e5c-4bc1-a7d9-9c3fad83b8c0">

**Comment by antlio** [comment]
fixed by  #2243 + bonus #2253
