### ISSUE TITLE
Enums do not render properly variables

### ISSUE THREAD

**Issue by MRocholl** [scalar/scalar#2260]
### What happens?

Enum components are not properly rendered in the scalar-api-client url-form-input component as variables.

Given the following simple FastAPI app:
```py
from enum import StrEnum, auto

from fastapi import FastAPI
from scalar_fastapi import get_scalar_api_reference


class MyEnum(StrEnum):
    test = auto()


app = FastAPI()


@app.get("/bla/{my_enum}")
async def get_enum(my_enum: MyEnum):
    return my_enum


@app.get("/scalar", include_in_schema=False)
async def scalar_html():
    return get_scalar_api_reference(
        openapi_url=app.openapi_url,
        title=app.title + " - Scalar",
    )
```
And the resulting openapi.json:
[openapi.json](https://github.com/user-attachments/files/15986106/openapi.json)

```json
  "paths": {
    "/bla/{my_enum}": {
      "get": {
        "summary": "Get Enum",
        "operationId": "get_enum_bla__my_enum__get",
        "parameters": [
          {
            "name": "my_enum",
            "in": "path",
            "required": true,
            "schema": {
              "$ref": "#/components/schemas/MyEnum"
            }
          }
        ],
        ...
    "components": {
    "schemas": {
      "MyEnum": {
        "type": "string",
        "enum": [
          "test",
          "other"
        ],
        "title": "MyEnum"
      },
```
The variable is not properly treated as a variable in the URI. 
![image](https://github.com/scalar/scalar/assets/11485472/507919e9-cc69-4581-a2d1-09e26c7cfa72)

### What did you expect to happen?

The URI should properly render the path as the variable. 

i.e. 
Instead of:
```
http://127.0.0.1:8000/bla/test
```
it should be:
```
http://127.0.0.1:8000/bla/{my_enum}
```

### How can we reproduce the issue?

See the above scenario.

### OpenAPI Document

see above

**Comment by antlio** [comment]
thanks for the feedback @MRocholl 🙏 , closing this as it should be resolved now the new api client is in, feel free to reply if you still encounter this issue

**Comment by MRocholl** [comment]
@antlio I can confirm that it is gone. Thank you!
