### ISSUE TITLE
bug: all query parameters are being sent when sending request

### ISSUE THREAD

**Issue by lrstanley** [scalar/scalar#2328]
### What happens?

It looks like `1.24.22` isn't loadable from NPM, however, all versions `1.24.23` to `1.24.25` or `api-reference` now auto-select all known query parameters, and always send them during test requests:
- even if you don't override the default
- even if they are blank

Video example: https://cdn.liam.sh/share/2024/06/firefox_PPQwc0Rcof.mp4

The same does not happen with `1.24.21`

### What did you expect to happen?

I expected:
- all query parameters with a default (without change), the request doesn't actually send with those query parameters.
- all optional query parameters/parameters without a default value are not sent to the backend by default, unless values are specified.

### How can we reproduce the issue?

1. Go to an operation which has query parameters, e.g. `List users`, and run a test request
2. See that it is sending all query parameters.

### OpenAPI Document

https://cdn.liam.sh/share/2024/06/openapi.json

**Comment by marclave** [comment]
hi @lrstanley ! i have great news!

we fixed it here :) 

and i confirmed it worked! release coming out soon
<img width="1512" alt="image" src="https://github.com/scalar/scalar/assets/6176314/b9d175a5-6d9c-4628-9dfe-b1bd2ef4f142">

**Comment by marclave** [comment]
https://github.com/scalar/scalar/pull/2330

**Comment by marclave** [comment]
@lrstanley this is released and fixed in @scalar/api-reference@1.24.26

**Comment by lrstanley** [comment]
LGTM, thanks!
