### ISSUE TITLE
Displaying large responses crashes the tab

### ISSUE THREAD

**Issue by DenuxPlays** [scalar/scalar#2333]
### What happens?

When scalar displays large payloads the browser tab crashes.
This happens with json and html. I also tested it using yaml but this works completely fine.

Responses was between 30kb and 80kb in size.

For example swagger-ui does struggle too but does not crash the tab.

### What did you expect to happen?

Display them normally without crashing the browser.

### How can we reproduce the issue?

1. add a endpoint that returns a lot of data
2. try it out in scalar

**Comment by marclave** [comment]
fixed this! ✨ :)
