### ISSUE TITLE
bug: path-scoped parameters are not shown/included in `Test Request` functionality

### ISSUE THREAD

**Issue by lrstanley** [scalar/scalar#2334]
### What happens?

Path-level parameters are not rendered as an available input option when using the `Test Request` functionality, however, they are rendered within the documentation itself.

### What did you expect to happen?

I would expect `PathItem` level parameters to show up in `Test Request`, just like method/operation parameters.

Most of the time, parameters are defined within each individual operation. However, OpenAPI 3.0+ allows for providing "common" parameters that are shared across all methods of the same path to be stored at the path level.

Ref: https://swagger.io/docs/specification/describing-parameters/#common-for-path

### How can we reproduce the issue?

1. Use the provided spec.
2. Go to a operation which requires a path parameter, e.g. `Retrieve a pet`
3. Hit `Test Request`
4. See that there is no option to provide `petID` (despite it showing in the documentation correctly).

Shows in documentation correctly:
![](https://cdn.liam.sh/share/2024/06/firefox_vsBblgIN5X.png)

However, in the `Test Request` window, path parameters aren't an option:
![](https://cdn.liam.sh/share/2024/06/firefox_Gj9zha0LQH.png)

When defined in the operation/method, they do show up, however.

### OpenAPI Document

https://cdn.liam.sh/share/2024/06/openapi.json

**Comment by marclave** [comment]
@lrstanley thanks for reporting this! I got a fix here :) you can test it in the deploy preview too, but you can see it working with the spec you shared in the screenshot ✨ 

https://github.com/scalar/scalar/pull/2335
