### ISSUE TITLE
Deep schema is not fully shown in example responses

### ISSUE THREAD

**Issue by soulchild** [scalar/scalar#2337]
### What happens?

I have a somewhat unusual, very deeply nested schema and noticed that everything below level five in the hierarchy is displayed as `null` in the example response. A limit of five suggests that this was a deliberate decision (not a bug, but a feature). Is this something which can be configured somewhere?

### What did you expect to happen?

Example response goes all the way down 😉 

### How can we reproduce the issue?

See [sandbox](https://sandbox.scalar.com/e/lZPDb). `level6` underneath `theAbyss` is rendered as `null`, but should be another object containing a property `foo` of type `number`. The actual schema is shown correctly when switching to it.

### OpenAPI Document

https://sandbox.scalar.com/e/lZPDb

**Comment by heinrichunbekannt** [comment]
I noticed the same behaviour some days ago.

**Comment by Jean-Regis** [comment]
We are also having the same issue. 
Is there any workaround ?

**Comment by hanspagel** [comment]
This was a deliberate decision to deal with circular references I think!

I think the easiest solution is to increase the limit, probably to 10 or something. But maybe we can do better than that.

**Comment by Jean-Regis** [comment]
10 would cover any (sane) use-case. That would be great !

**Comment by manuteam** [comment]
> This was a deliberate decision to deal with circular references I think!
> 
> I think the easiest solution is to increase the limit, probably to 10 or something. But maybe we can do better than that.

Thank you! We have faced with this issue also.

**Comment by hanspagel** [comment]
Taken care of in #3114 :)
