### ISSUE TITLE
`@scalar/api-client` switches from light to dark mode when hitting send request

### ISSUE THREAD

**Issue by hanspagel** [scalar/scalar#2344]
### What happens?

I’m a little bit confused. When I’m using the play-button and hit send request, it switches from light mode to dark mode. 😅

https://github.com/scalar/scalar/assets/1577992/54f78a75-2fed-4e50-bb31-b3e8cdce6715

### What did you expect to happen?

I think it should initially be set to dark mode, because that’s my system setting.

### How can we reproduce the issue?

```bash
# checkout https://github.com/scalar/scalar/pull/2343 if it’s not merged already
cd examples/cdn-api-reference
pnpm run dev
open http://127.0.0.1:3173/play-button-local.html
```

**Comment by TanishqSingla** [comment]
Facing similar issue, while using `api-reference-react` the dev server as well as the local build works fine. As soon as I deploy my code this thing happens
