### ISSUE TITLE
Leaks global styles to rest of application

### ISSUE THREAD

**Issue by ascott18** [scalar/scalar#2359]
### What happens?

- Per documentation, `import "@scalar/api-reference/style.css";`
- Observe that other styles across my application are overwritten. For example, a plain `h1` has its font-size and font-weight overridden by scalar.
- 
![image](https://github.com/scalar/scalar/assets/5017521/f6d6e4fd-583a-44cd-891b-6623f97387df)

### What did you expect to happen?

Styles are specific to `scalar` and its components and don't affect the rest of my application's styling

### How can we reproduce the issue?

- Import `@scalar/api-reference/style.css`
- Go to a different page that uses a plain HTML element like `h1`
- Observe that scalar overrides the styles of that element.

**Comment by hanspagel** [comment]
Oh, dang! Would you mind to check you’re already on the latest version?

**Comment by ascott18** [comment]
This was on `1.24.21`, the latest version that I can actually run due to #2358

**Comment by niwsa** [comment]
We also noticed this issue in our recent updates for `@scalar/docusaurus` plugin (v0.4.23).
1. In the below case the max-height from the plugin causes the image to appear stretched (https://f9fc097d.website-d9q.pages.dev/docs/jackson/overview)
<img width="348" alt="Screenshot 2024-07-03 at 12 26 49 AM" src="https://github.com/scalar/scalar/assets/3107922/8d160069-79fd-4ab3-84d5-5812f24d4e57">

2. Also the prismjs theme styles gets overridden in code blocks through our documentation. (https://cefe6436.website-d9q.pages.dev/guides/jackson/frameworks/nextjs)

**Comment by amritk** [comment]
@hwkr is on the case!

**Comment by deepakprabhakara** [comment]
@hwkr Thank you so much for the quick turnaround, could you please advise which version of `@scalar/docusaurus` will have this fix?

**Comment by hwkr** [comment]
Fixed in #2363
