### ISSUE TITLE
Configuration Incorrectly Generated In .Net Package

### ISSUE THREAD

**Issue by Adepta** [scalar/scalar#2368]
### What happens?

When using the .Net Package and adding in configuration options an additional { is generated in the outputed HTML which results in an error and the inability to use Scalar Options. 

```csharp
app.MapScalarApiReference(c =>
{
    c.Theme = "purple";
    c.EndpointPathPrefix = "docs";
    c.SearchHotkey = "?";
});
```

This then produces the following HTML 

```html
<!doctype html>
<html>
<head>
    <title>Scalar API Reference -- v1</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
</head>
<body>
    <script id="api-reference" data-url="/openapi/v1.json"></script>
    <script>
    var configuration = {
        {
  "theme": "purple",
  "searchHotkey": "?"
}
    }

    document.getElementById('api-reference').dataset.configuration =
        JSON.stringify(configuration)
    </script>
    <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>
</body>
</html>
```

### What did you expect to happen?

The configuration should only have one bracket. 
This would then allow for the configuration to be loaded correctly.

### How can we reproduce the issue?

1. Create a New .Net Project with Scalar Support
2. Add Configuration Options such as Theme 
3. Run Project and Direct over to Document
4. Theme will fail to load

**Comment by hanspagel** [comment]
Oh, yes! Submitted a PR: #2369
