### ISSUE TITLE
URL parameters are not editable 

### ISSUE THREAD

**Issue by sidwebworks** [scalar/scalar#2376]
### What happens?

URL parameters mentioned in the openapi.yml are not editable in the UI - inspecting the DOM shows that `contenteditable=false`. The same issue does not happen in the Scalar Swagger editor. 

<img width="859" alt="image" src="https://github.com/scalar/scalar/assets/58144379/1d8cf67d-df90-454b-a2f8-06996aa3e14a">

### What did you expect to happen?

It should be editable

### How can we reproduce the issue?

It can be reproduced via CDN link (I am using it with Go) and the Online Sandbox 

### OpenAPI Document

https://sandbox.scalar.com/e/t0Ca7

**Comment by antlio** [comment]
hey @sidwebworks thanks for the feedback! it's been added by design in the new api client, however i'd love to get some more about your use case here, is that something you'd like to see back?

nb. the new api client is not yet running in the editor 🔜

**Comment by sidwebworks** [comment]
@antlio Oh okay - what does this design solve? infact I have a really confusing experience with this as I could not test the apis using the send request panel - how am I suppose to inject param values in this new design? Are there any documentation or PR notes I can see?

All in all - I really found the previous functionality user friendly and pretty much obvious as that is how it works in things like insomnia and postman. I might not be seeing what the design is aiming to do which I am happy to learn more about.

**Comment by antlio** [comment]
thanks for the quick reply! you should be normally able to do that by updating the value in the path variable table. however i'll investigate as it doesn't seem to be showing up in your case. 

regarding the url, we wanted here to strictly reflect the informations from the specification when navigating within the reference, while keeping fully autonomous testing capabilities from the workspace (which is coming very soon!).

does that make sense? however nothing cast in stone so I'll share your feedback with the team!

**Comment by sidwebworks** [comment]
@antlio that makes a ton of sense - cool I am in the favour of that.  Thanks hoping to see this fixed soon. Let me know if I can help in any way.

**Comment by antlio** [comment]
i gave it a look and path variable should be displayed and be updated [here an example](https://sandbox.scalar.com/e/x-fcK) where i added parameters to endpoints:

<img width="1106" alt="image" src="https://github.com/scalar/scalar/assets/14966155/04e95fe1-8b67-43a4-a095-f240f303e3ab">

**Comment by sidwebworks** [comment]
Cool looks like an issue with the generated open api - Will see how to fix it. Thanks
