### ISSUE TITLE
Internal links to anchors do not work unless the section the anchor is in is already expanded

### ISSUE THREAD

**Issue by mpminardi** [scalar/scalar#2386]
### What happens?

Intra-page links to anchors do not work unless the section being linked to is already expanded. For example, clicking on the "test link to model" link in https://sandbox.scalar.com/e/3j6TU will not auto expand the models section and jump to the model, whereas a direct link of https://sandbox.scalar.com/e/3j6TU#model/listapp does

### What did you expect to happen?

Intra-page links auto expand sections / work with any anchor that exists on the page.

### How can we reproduce the issue?

1. Go to https://sandbox.scalar.com/e/3j6TU
2. Click on the "test link to model" link in the description
3. Verify that the anchor is not navigated to

### OpenAPI Document

https://sandbox.scalar.com/e/3j6TU

**Comment by hwkr** [comment]
This was / is fixed in #2604 (and #2793).
