### ISSUE TITLE
examples for params

### ISSUE THREAD

**Issue by hanspagel** [scalar/scalar#2387]
### What happens?

can we add support for parameter examples?

### What did you expect to happen?

![image](https://github.com/scalar/scalar/assets/1577992/da9385e8-15eb-4aab-a4bb-f6172371cff9)

![image](https://github.com/scalar/scalar/assets/1577992/2909f187-bb99-4aff-a5a8-62a98b9b02b7)

### How can we reproduce the issue?

Add example values to params?

**Comment by jpjpjp** [comment]
@hanspagel, I am curious if this is moving into the active backlog (or if there is a way to get visibility into that).

From my perspective, being unable to easily try an API request using parameter values from the examples in the spec is a big enough deal that it would prevent us from moving from stoplight to scalar.

**Comment by hanspagel** [comment]
I think this was added already! :)

**Comment by pedro** [comment]
oo, interested in this! can you share a link to docs/example/PR with more? 👌 

thank you!

**Comment by jpjpjp** [comment]
@hanspagel I don't see this in the documentation that I generate using "@scalar/express-api-reference": "0.4.133".   The only values populated in dropdowns are for parameters that have enum values or boolean.  No examples.

Do I need to do something to enable this?

**Comment by pedro** [comment]
ahh, you can see example requests in the sample Galaxy API:

<img width="480" alt="377948397-90f9fbab-45f3-4369-9687-f201c7fe6d00" src="https://github.com/user-attachments/assets/7a3dfd6e-6980-4e66-8dcd-77bd9da54eb0">

the corresponding spec:

https://github.com/scalar/scalar/blob/0706bc41b5f5d3c73d7be12f1cba8b5845399e05/packages/galaxy/src/specifications/3.1.yaml#L276-L286

response examples are supported too
