### ISSUE TITLE
Theming no longer works in the React wrapper

### ISSUE THREAD

**Issue by jacando-timo-zimmermann** [scalar/scalar#2392]
### What happens?

After switching to the latest version `0.3.29` of `@scalar/api-reference-react` themes no longer work. You can switch between light and dark mode, but themes like `kepler` no longer load. There seems to be no error message, it just falls back to the default.

### What did you expect to happen?

I would expect the themes to load according to the documentation by providing the theme name as prop.

### How can we reproduce the issue?

The following does not show the Kepler theme as it used to with an older version. The last version with working themes I found is `0.3.19`.

```TypeScript
import React from 'react';
import { ApiReferenceReact } from "@scalar/api-reference-react";

import styling from './Docs.module.scss';

import '@scalar/api-reference-react/style.css';

type Props = {
    spec: Record<string, any>;
};

const Docs = ({ spec }: Props): React.ReactElement => {
    return (
        <>
            <div className={styling.preview}>
                For preview purposes only
            </div>

            <ApiReferenceReact
                configuration={{
                    spec: {
                        content: spec
                    },
                    theme: 'kepler',
                    hideDownloadButton: true,
                    hideModels: true,
                    darkMode: true
                }}
            />
        </>
    );
};

export default Docs;
```

**Comment by hanspagel** [comment]
Thanks for reporting. Tested this in a fresh project and it seems to work (again)! 👏 Let me know if you still experience this with the latest version.
