### ISSUE TITLE
API client not forwarding query parameters

### ISSUE THREAD

**Issue by vini-hoseki** [scalar/scalar#2453]
### What happens?

We have an endpoint which accepts pagination config via query parameters, but they aren't being sent to our API. 
<img width="783" alt="image" src="https://github.com/scalar/scalar/assets/157767030/a06fa9d7-b5c3-4523-b7ef-2b2a6956906b">

The query params only work if we send them one at a time, if more than one is sent, Scalar's API client will trim them and keep only one. It seems `ending_before` takes precedence over `limit` and `limit` takes precedence over `starting_after`.

Current behavior examples:

GET `/v1/connect/accounts/{id}/records` without query params
```json
{
  "data": [
    {
      "id": "rec_3P1ZaW5dYF5PJB6APKAZL",
      ...
    },
    {
      "id": "rec_BmMU2zJQqk5k8nBIslun0",
      ...
    },
    {
      "id": "rec_5Nq9jI4xR10tkifHBTF7i",
      ...
    }
}
```

GET `/v1/connect/accounts/{id}/records`
query params: `starting_after=rec_3P1ZaW5dYF5PJB6APKAZL`
```json
{
  "data": [
    {
      "id": "rec_BmMU2zJQqk5k8nBIslun0",
      ...
    },
    {
      "id": "rec_5Nq9jI4xR10tkifHBTF7i",
      ...
    }
}
```

GET `/v1/connect/accounts/{id}/records`
query params: `limit=2` and `starting_after=rec_3P1ZaW5dYF5PJB6APKAZL`
```json
{
  "data": [
    {
      "id": "rec_3P1ZaW5dYF5PJB6APKAZL",
      ...
    },
    {
      "id": "rec_BmMU2zJQqk5k8nBIslun0",
      ...
    }
}
```

GET `/v1/connect/accounts/{id}/records`
query params: `limit=2`
```json
{
  "data": [
    {
      "id": "rec_3P1ZaW5dYF5PJB6APKAZL",
      ...
    },
    {
      "id": "rec_BmMU2zJQqk5k8nBIslun0",
      ...
    }
}
```

### What did you expect to happen?

GET `/v1/connect/accounts/{id}/records`
query params: `limit=2` and `starting_after=rec_3P1ZaW5dYF5PJB6APKAZL`
```json
{
  "data": [
    {
      "id": "rec_BmMU2zJQqk5k8nBIslun0",
      ...
    },
    {
      "id": "rec_5Nq9jI4xR10tkifHBTF7i",
      ...
    }
}
```

### How can we reproduce the issue?

1. Load and Open API file describing at least one GET endpoint that accepts multiple query parameters
2. Send a GET request to that endpoint with only one query parameter checked in the UI and with some value in it
3. See the results appearing correctly
4. Send a GET request to the same endpoint but with two query parameters checked and with some value
5. Check the endpoint not receiving both query parameters in the request

### OpenAPI Document

https://api.hoseki.app/openapi.json

**Comment by antlio** [comment]
hey @vini-hoseki thanks for bringing this up! do you mind sharing your version, integration in usage? the recent release of the new api client might get your issue resolved

**Comment by vini-hoseki** [comment]
hey @antlio. We are hosting the Guide and Reference in Scalar, so I'm assuming it's the latest version.
We are feeding the API Reference in the panel using OpenAPi linked URL (the same URL at the end of my first post here).

![image](https://github.com/scalar/scalar/assets/157767030/d2678a8a-5968-496f-915d-fdef6601e6d5)

The actual documentation https://docs.hoseki.app/reference

**Comment by marclave** [comment]
@vini-hoseki this should be fixed if you redeploy :)

**Comment by vini-hoseki** [comment]
Hey guys, the API client is behaving as expected now, thanks for your support!
