### ISSUE TITLE
Dropdown field for boolean values

### ISSUE THREAD

**Issue by Rahul-kalsha** [scalar/scalar#2455]
### What happens?

In the Swagger UI, boolean values are always displayed as a dropdown with options 'true' or 'false'. However, in the Scalar documentation UI, boolean fields do not appear as dropdowns. Instead, they are displayed as input fields.

### What did you expect to happen?

In the Scalar documentation UI, we expect boolean values to be displayed as dropdowns, similar to how they are presented in the Swagger UI.

![image](https://github.com/scalar/scalar/assets/56481473/be44ee0c-c044-480a-9b18-0afc72a66ab8)

### How can we reproduce the issue?

1. Go to the Scalar documentation page.
2. Click on the API "Test Request" button.
3. Observe the left side section of the popup for boolean type value fields.

**Comment by hwkr** [comment]
Thanks @Rahul-kalsha! I think this should be pretty doable, I'll let @cameronrohani and @hanspagel weigh in though :)

**Comment by antlio** [comment]
hey @Rahul-kalsha, it's just been added in #2456 in order to have a select displayed automatically on boolean type, let us know if that matches your expectation here!

**Comment by Rahul-kalsha** [comment]
Thanks @antlio and @hwkr. Input select for enum looks perfect. Let me know when it will up so we can update version.

**Comment by marclave** [comment]
@Rahul-kalsha this is in the latest version! : ) let us know if it works for you ✨

**Comment by Rahul-kalsha** [comment]
It working as expected. Thank you for great work @marclave and team.
