### ISSUE TITLE
Examples for dictionaries of objects are wrong

### ISSUE THREAD

**Issue by jordi-petit** [scalar/scalar#2457]
### What happens?

Dear authors,

For schemas that represent dictionaries of objects indexed by string keys, the examples are wrong, in the sense they have a bad structure that only shows that internal entries.

For instance, with this schema

<img width="446" alt="Captura de pantalla 2024-07-11 a les 10 39 43" src="https://github.com/scalar/scalar/assets/2351822/5ba4de25-2274-4efb-bf77-4fc61f09a046">

the example is

<img width="426" alt="Captura de pantalla 2024-07-11 a les 10 39 52" src="https://github.com/scalar/scalar/assets/2351822/b12623a6-906c-44a5-9eba-921009a35119">

### What did you expect to happen?

For the same schema, Swagger shows a correct example with meaningful structure:

<img width="1169" alt="Captura de pantalla 2024-07-11 a les 10 40 21" src="https://github.com/scalar/scalar/assets/2351822/7cdb4bcf-61ba-45bd-bc02-3163f40dc4b5">

Something similar should be achieved.

### How can we reproduce the issue?

Use this schema:

```
{
  "schema": {
    "type": "object",
    "additionalProperties": {
      "type": "object",
      "properties": {
        "a": {
          "type": "string"
        },
        "b": {
          "type": "number"
        }
      },
      "required": [
        "a",
        "b"
      ]
    }
  }
}
```

**Comment by hanspagel** [comment]
Oh, yes! Thanks for reporting!
