### ISSUE TITLE
Blank values treated as strings in scalar UI causing request payload issues

### ISSUE THREAD

**Issue by Rahul-kalsha** [scalar/scalar#2470]
### What happens?

In the Scalar UI, when a blank value is entered, it is treated as a type of string. This behavior is different from Postman and Swagger, where a blank value is not included in the request payload. As a result, the new UI fails to handle blank values correctly, leading to issues in processing requests.

### What did you expect to happen?

I expected the Scalar UI to handle blank values consistently with how Postman and Swagger do, by excluding them from the request payload. This would ensure that the application processes blank values correctly without any issues.

Swagger UI (Blank Value Excluding from the request payload): **Working**
![Swagger UI](https://github.com/user-attachments/assets/9b64cd31-abd9-40c7-b823-577a84638ba8)

Scalar UI (Blank Value is being treated as a type of string): **Not Working**
![Scalar UI](https://github.com/user-attachments/assets/5108a64f-4971-4459-9f0a-ca404b997b9a)

### How can we reproduce the issue?

1. Go to the Scalar documentation page.
2. Click on the API "Test Request" button.
3. Open the popup.
4. Enter a blank value in any input field that will be sent in the request payload.
5. Observe that the blank value is included as a string in the payload.

**Comment by hanspagel** [comment]
Good catch, thanks for reporting!

**Comment by marclave** [comment]
fixed in https://github.com/scalar/scalar/pull/2483 :)
