### ISSUE TITLE
Latest Nuxt module not built

### ISSUE THREAD

**Issue by danielroe** [scalar/scalar#2471]
### What happens?

Checking, it seems the published version wasn’t built:

https://unpkg.com/browse/@scalar/nuxt@0.2.39/dist/module.mjs

The latest working version is https://unpkg.com/browse/@scalar/nuxt@0.2.27/dist/module.mjs

### What did you expect to happen?

Should be built. Likely a very simple fix in publishing process.

### How can we reproduce the issue?

Visit link

**Comment by hanspagel** [comment]
😳 Let’s look into this!

**Comment by hanspagel** [comment]
This should fix it: https://github.com/scalar/scalar/pull/2472

**Comment by antlio** [comment]
thanks for the catch @danielroe!

**Comment by marclave** [comment]
@danielroe released in `@scalar/nuxt@0.2.40` <3

**Comment by danielroe** [comment]
Amazing - thank you 🙏
