### ISSUE TITLE
Cannot read properties of null (reading 'useRef')

### ISSUE THREAD

**Issue by lys623** [scalar/scalar#2482]
### What happens?

![image](https://github.com/user-attachments/assets/7762a53f-f012-44c1-a849-5945ef30fb5d)

### What did you expect to happen?

run success

### How can we reproduce the issue?

// src/App.jsx
import { ApiReferenceReact } from '@scalar/api-reference-react'
import '@scalar/api-reference-react/style.css'
import React, { useState } from 'react';

function App() {
  return (
    <ApiReferenceReact
      configuration={{
        spec: {
          url: 'https://cdn.jsdelivr.net/npm/@scalar/galaxy/dist/latest.yaml',
        },
      }}
    />
  )
}

export default App

--------
I just use demo code to run , but throw error;

 "dependencies": {
    "@ant-design/icons": "^5.3.6",
    "@docusaurus/core": "^3.1.1",
    "@docusaurus/preset-classic": "^3.1.1",
    "@mdx-js/react": "^3.0.0",
    "@scalar/docusaurus": "0.4.44",
    "antd": "^5.16.1",
    "clsx": "^2.0.0",
    "fs-extra": "^11.2.0",
    "prism-react-renderer": "^2.3.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },

**Comment by lys623** [comment]
There is no problem running the demo alone, but if it is used together with docusaurus, this error will be reported

**Comment by marclave** [comment]
@lys623 would you be able to share a minimal reproducible repository so we can help debug ✨ :)

**Comment by mpminardi** [comment]
For what its worth I think I've seen this error (or something similar) when I've ended up with multiple versions of react in a project's lockfile, with the solution being de-duplicating the dependency to ensure there is only one version.

**Comment by lys623** [comment]
> For what its worth I think I've seen this error (or something similar) when I've ended up with multiple versions of react in a project's lockfile, with the solution being de-duplicating the dependency to ensure there is only one version.

So how do you do that? Writing a dead react version in package.json won't fix it @mp

**Comment by lys623** [comment]
> [scalar/api-reference-react ](/scalar/scalar/labels/package%3A%20%40scalar%2Fapi-reference-react)

https://github.com/lys623/scalar-api-reference-react-demo   a minimal reproducible repository , pls help to check @marclave

**Comment by mpminardi** [comment]
> > For what its worth I think I've seen this error (or something similar) when I've ended up with multiple versions of react in a project's lockfile, with the solution being de-duplicating the dependency to ensure there is only one version.
> 
> So how do you do that? Writing a dead react version in package.json won't fix it @mpminardi

Changing the [react dependency in package.json](https://github.com/lys623/scalar-api-reference-react-demo/blob/main/package.json#L45) to 18.3.1 (or ^18.3.1) to match what [@scalar/api-reference-react](https://github.com/scalar/scalar/blob/main/packages/api-reference-react/package.json#L55) currently has in its package.json and doing a `yarn install` solves this for me locally and gets rid of the duplicate version in [yarn.lock](https://github.com/lys623/scalar-api-reference-react-demo/blob/main/yarn.lock#L8868-L8880).

**Comment by davidhu2000** [comment]
my 2-cents are that `react` should be a `peerDependency` instead of dependency, and the versions should be as loose as possible ^18.0.0 instead of ^18.3.1 (unless there is a reason why 18.1 or 18.2 doesn't work?)

I can't imagine a scenario where an app that installs @scalar/api-reference-react do not already have `react` as a dependency.

**Comment by snigdha920** [comment]
I'm still facing this issue, I have: 

```json
"react": "18.3.1",
"@scalar/api-reference-react": "0.3.47",
``

but when I downgrade to "@scalar/api-reference-react": "0.3.44" I don't have it anymore. 

With both 0.3.44, and 0.3.47 I do have two versions of react in my pnpm lockfile: 
```
  react@16.14.0:
    dependencies:
      loose-envify: 1.4.0
      object-assign: 4.1.1
      prop-types: 15.8.1

  react@18.3.1:
    dependencies:
      loose-envify: 1.4.0
```

but the react 16.14.0 comes from `"@playwright/test": "1.45.2",` (also in my package.json) and i do need that package. 

What can I do to fix this?

**Comment by davidhu2000** [comment]
i upgraded and faced this same issue on 0.3.47

took a look at the difference between 0.3.47 and 0.3.44

https://yarnpkg.com/package?q=%40scalar%2Fapi&name=%40scalar%2Fapi-reference-react&file=%2Fdist%2Findex.js&version=0.3.47

https://yarnpkg.com/package?q=%40scalar%2Fapi&name=%40scalar%2Fapi-reference-react&file=%2Fdist%2Findex.js&version=0.3.44

.44 only has `react-jsx-runtime.production.min.js` and `react-jsx-runtime.development.js`

seems like in .47, `react.production.min.js` and ``react.development.min.js`` is also bundled into the dist/index.js

i don't think any of these react code should be part of the final dist files.
