### ISSUE TITLE
Content-Type header with empty body

### ISSUE THREAD

**Issue by inyourtime** [scalar/scalar#2486]
### What happens?

My API in Swagger does not have a body, as shown in the example below:
```
{
  "openapi": "3.0.3",
  "info": { "title": "My Fastify App", "version": "1.0.0" },
  "components": {
    "securitySchemes": {
      "apiKey": { "type": "apiKey", "name": "apiKey", "in": "header" }
    },
    "schemas": {}
  },
  "paths": {
    "/example-route/{id}": {
      "put": {
        "summary": "qwerty",
        "tags": ["user", "code"],
        "description": "post some data",
        "parameters": [
          {
            "schema": { "type": "string" },
            "in": "path",
            "name": "id",
            "required": true,
            "description": "user id"
          }
        ],
        "responses": {
          "201": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "description": "Successful response",
                  "type": "object",
                  "properties": { "hello": { "type": "string" } }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

So, the body of the example request is set to none. However, when I change it to JSON, the request header is not set to application/json.

<img width="662" alt="Screenshot 2567-07-15 at 11 39 33" src="https://github.com/user-attachments/assets/018ea9c4-d291-4155-9ec2-57887f0b8c35">
<img width="562" alt="Screenshot 2567-07-15 at 11 38 57" src="https://github.com/user-attachments/assets/b4d2abf2-0a56-4615-9a1d-3a7a22ce623e">

### What did you expect to happen?

It should set the header correctly.

### How can we reproduce the issue?

1. Add a Swagger file with an example request that does not have a body.
2. Change the body to JSON.
3. Send the request.

**Comment by marclave** [comment]
fixed in https://github.com/scalar/scalar/pull/2526 : O
