### ISSUE TITLE
Disable the Powered By Scalar.com in Footer as Configuration

### ISSUE THREAD

**Issue by vbasky** [scalar/scalar#2495]
### What happens?

<img width="217" alt="image" src="https://github.com/user-attachments/assets/6d94d252-5edb-48de-b64e-865e198a7ca2">

<img width="781" alt="image" src="https://github.com/user-attachments/assets/613325e9-abfd-44e2-ae5b-02a86440b6ef">

I wish to customise the footer to not show powered by scalar.com if possible.

### What did you expect to happen?

Hide the Powered by Scalar.com branding

### How can we reproduce the issue?

All default documentation has the branding

**Comment by hanspagel** [comment]
Hey, we’re building this tool for free and - for us - it feels so great to see the “powered by”. That said, if you want to get rid of it, you can add some custom CSS. 🥲
