### ISSUE TITLE
iOS Dark Mode white status bar

### ISSUE THREAD

**Issue by elliotnash** [scalar/scalar#2496]
#### On safari on iOS, the collapsed navigation bar shows as white when in dark mode on the default theme.

I assume this is the case on all themes.

#### On the kepler theme, both the navigation bar and status bar appear white.

---

default                | kepler
:----------------:|:----------------:
![92AFA735-3653-4ADA-A608-42DF6E4E870B_1_102_o](https://github.com/user-attachments/assets/aa6eb218-4257-40dd-9943-28f4a364ab26) | ![435F3893-7B38-4D89-ADC7-FDE03E4AE85D_1_102_o](https://github.com/user-attachments/assets/497cf0bb-8467-45fb-a175-4d9dc3dfcbbe)

---

### Workaround
This seems to be caused by the fact that background-color is not set. By adding custom css
```css
body {
  background-color: var(--scalar-background-1);
}
```

we can achieve the following output (which fixes the issue on all themes I've tested)

---

kepler
:-------:
![477A153D-3319-4317-BE83-7DF25E4CF927_1_102_o](https://github.com/user-attachments/assets/ddf7e794-7159-41fa-bab4-d3b31c4aa39c)

---

### Environment

@scalar/hono-api-reference@^0.5.107

### Steps

1. Add a basic scalar reference route
```ts
app.get("/docs", apiReference({
  spec: {
    url: SPEC_URL,
  },
});
```
2. Navigate to that route using Safari on an iOS device
3. Scroll down and observe the collapsed navigation bar is white

### OpenAPI Document

https://forestpark.cecs.pdx.edu/staging/v1/openapi

**Comment by hwkr** [comment]
Thanks for filing this @elliotnash! Fix in #2517 :)
