### ISSUE TITLE
Base URL spacing is off

### ISSUE THREAD

**Issue by hanspagel** [scalar/scalar#2501]
The padding of the base URL is missing/off. Once hovered, the padding is added, but then there’s a scrollbar.

I’ve seen it in our Hono example and here: https://www.getoutline.com/developers
Both use CDN latest.

**Initial**

<img width="582" alt="Screenshot 2024-07-16 at 10 27 21" src="https://github.com/user-attachments/assets/96fbc9c1-c411-4b37-88dd-351beb23534d">

<img width="557" alt="Screenshot 2024-07-16 at 11 07 55" src="https://github.com/user-attachments/assets/5b09a2fe-3f56-4891-b408-6e06c50112f3">

**After hover**

<img width="582" alt="Screenshot 2024-07-16 at 10 27 30" src="https://github.com/user-attachments/assets/dc19d020-af23-4388-9e34-c5c30fbbd5af">

**Comment by marclave** [comment]
@hanspagel this was fixed in some PR earlier this week
