### ISSUE TITLE
Freeze when performing a test request

### ISSUE THREAD

**Issue by clement4saunier** [scalar/scalar#2503]
### What happens?

Whenever I send a test request, the whole UI freezes forever. I have pretty heavy routes but even with smaller ones it still happens to some degree. 

https://github.com/user-attachments/assets/207e1453-f6ec-489e-b3a6-8f9a5bc1bf08

### What did you expect to happen?

When trying with swagger, there is a non-blocking loading state and the json ends up showing in little time. Due to it being completely stuck it's hard to tell what's going on, but I was once able to make a performance test and it showed the whole blocking time was UI rendering, the response from the api is also pretty quick

### How can we reproduce the issue?

Use `elysia` with `@elysiajs/swagger` on the latest version, scalar is the default provider.
Return 700kb of data on the request, run test request on scalar UI.

**Comment by clement4saunier** [comment]
I love how modern scalar feels, but this is really a deal breaker

**Comment by hanspagel** [comment]
Bummer! We recently revamped our API client, but I don’t think we did perf testing already. There might be some low hanging fruits here. 🤔

**Comment by clement4saunier** [comment]
> Bummer! We recently revamped our API client, but I don’t think we did perf testing already. There might be some low hanging fruits here. 🤔

Yeah I've seen that you've been iterating quite a lot ! I went through some previous versions to test the same thing and had no luck finding one that was working fine, but I definitely seen big positive ui changes. Do you know of any previous versions that could have more stable requests ?

**Comment by marclave** [comment]
> > Bummer! We recently revamped our API client, but I don’t think we did perf testing already. There might be some low hanging fruits here. 🤔
> 
> Yeah I've seen that you've been iterating quite a lot ! I went through some previous versions to test the same thing and had no luck finding one that was working fine, but I definitely seen big positive ui changes. Do you know of any previous versions that could have more stable requests ?

hey @clement4saunier ! im working on this perf issue rn, you can go back to 1.20 and it should be good.

we do some stuff with codemirror, so i might remove the "preview" feature for now : ) will update this thread in time!

**Comment by marclave** [comment]
@clement4saunier after some serious debugging i found a bunch of performance issues:
- headless ui is causing re-render's way too much
- our ScalarCodeBlock is not performant at all for highlighting large (>500KB) responses
- I need to remove some `v-if`'s to `v-show`s :) 
going to be a ton of small PRs to improve this, but today im going to swap out ScalarCodeBlock to use CodeMirror (which does virtualization) really well and get a PR up : ) 

Appreciate your patience and I totally understand this is a deal breaker, it is for me too.

I unfortunately had not hit APIs with large responses yet but it will be fixed now <3

**Comment by marclave** [comment]
fixing in here https://github.com/scalar/scalar/pull/2573
