### ISSUE TITLE
JSON Request Body Sent as FormData

### ISSUE THREAD

**Issue by jeffAntonis** [scalar/scalar#2511]
### What happens?

When testing the request, selecting the JSON type for the request body results in the data being sent as FormData instead of JSON. This leads to unexpected behavior in the API and makes it difficult to test JSON endpoints properly.

Version: 
"@scalar/fastify-api-reference": "^1.24.46"

### What did you expect to happen?

The request should be sent with the body formatted as JSON.

### How can we reproduce the issue?

Steps to Reproduce:

1. Navigate to the request testing interface.
2. Select the request type as JSON.
3. Enter a JSON object in the request body.
4. Send the request.

### OpenAPI Document

`
    "/auth/login": {
      "post": {
        "operationId": "auth_login",
        "summary": "Login",
        "tags": ["auth"],
        "security": [{ "noAuth": [] }],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": { "type": "string", "format": "email", "description": "The email address of the user." },
                  "password": { "type": "string", "description": "The password of the user in plain-text." }
                },
                "required": ["email", "password"]
              }
            }
          }
        },`

**Comment by hanspagel** [comment]
This should fix it: #2526

**Comment by marclave** [comment]
I think we need this in first, cause im dealing with a pesky codeinput race condition https://github.com/scalar/scalar/pull/2569
