### ISSUE TITLE
activate query params by default only if required

### ISSUE THREAD

**Issue by hanspagel** [scalar/scalar#2558]
> The API Playground client seems to set all the query parameters as "on" by default.  (See checkboxes in screenshot). 
>
> In my opinion I think that, unless the parameter is defined as required, it would be better to default to the parameters being unchecked, unless a value is explicitly entered into the value field.
>
> ![image](https://github.com/user-attachments/assets/f24a5b50-c5ee-4805-8071-f52fd01fd263)

_Originally posted by JP in https://github.com/scalar/scalar/discussions/1710_</div>

**Comment by marclave** [comment]
this was driving me nuts https://github.com/scalar/scalar/pull/2569
