### ISSUE TITLE
Latest changes broke testing base URL

### ISSUE THREAD

**Issue by dnlsndr** [scalar/scalar#2566]
### What happens?

With the recent releases, the testing functionality in the api-reference does not utilize the correct base-url anymore. In my case, it doesn't utilize the application port, even though it's displayed in the api-reference sample request.

Here you can see the sample request from the api-reference, correctly utilizing `http://localhost:3000` as a base URL:
<img width="996" alt="Screenshot 2024-07-20 at 15 28 52" src="https://github.com/user-attachments/assets/26c8bec5-ad01-4850-bc2b-b2ff4e47cf61">

But when clicking on the "Test Request" button, it does not utilize that `http://localhost:3000` base URL anymore:
<img width="1450" alt="Screenshot 2024-07-20 at 15 43 11" src="https://github.com/user-attachments/assets/c22e2e84-fbb5-4230-8937-4bd297bc0221">

When hovering over that pill in the URL, it gives me a tooltip saying "Variable not found"

I've searched through the docs, but I couldn't find any mention of such a variable that needs to be configured.
This used to work completely fine, until the most recent release, which I believe was yesterday.

Here's the HTML that I use for the api-reference:
```
<!DOCTYPE html>
            <html>
              <head>
                <title>{title}</title>
                <meta charset="utf-8" />
                <meta
                  name="viewport"
                  content="width=device-width, initial-scale=1" />
                <style>
                  body {{
                    margin: 0;
                  }}
                </style>
              </head>
              <body>
                <script
                  id="api-reference"></script>
                <script>
                  var configuration = {{
                    theme: 'default',
                    spec: {{
                        url: '{spec_url}'
                    }}
                  }}

                  var apiReference = document.getElementById('api-reference')
                  apiReference.dataset.configuration = JSON.stringify(configuration)
                </script>
                <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>
              </body>
            </html>
```

where the `spec_url` is a path to the local openapi doc, e.g. "/docs/private/api.json" (I'm using Rust btw and copied the configuration from the aide crate)

### What did you expect to happen?

The request testing functionality should correctly utilize the base URL, that's also displayed in the sample request of the api-reference interface

### How can we reproduce the issue?

1. Open the linked OpenAPI json in the newest api-reference version, that can be found under https://cdn.jsdelivr.net/npm/@scalar/api-reference
2. Notice the above described issue

### OpenAPI Document

https://sandbox.scalar.com/e/jslqL

**Comment by cursefroge** [comment]
Same here - using the Elysia integration

**Comment by marclave** [comment]
i'll look into this this morning :) sorry about this bug!

**Comment by marclave** [comment]
fix in here! https://github.com/scalar/scalar/pull/2568
