### ISSUE TITLE
Search is very slow to open

### ISSUE THREAD

**Issue by tnrich** [scalar/scalar#2586]
### What happens?

I'd expect hitting Cmd+K to open the Search box nearly instantaneously for my API. 

### What did you expect to happen?

Instead it's taking ~2-3 seconds to open. 

### How can we reproduce the issue?

Go to - https://sandbox.scalar.com/e/korOI

Enter preview mode. Hit `Cmd + K`. See how long it takes to show up. Also pressing the esc key doesn't close the search box until the 2nd time you press it. See attached screen recording: 

https://github.com/user-attachments/assets/e0cdb712-6884-4fd9-aa90-f3e2a9f981ea

Perhaps there is a way to have an empty search box come up instead of a pre-populated one? 

Thanks! Would love to use scalar for our docs but the slow search response time is a bit of a non-starter..

### OpenAPI Document

https://sandbox.scalar.com/e/korOI

**Comment by hanspagel** [comment]
Thanks for reporting! I submitted a fix in #2586. :)

**Comment by tnrich** [comment]
@hanspagel awesome thanks for the fix! Can't wait for this to land :) !

**Comment by tnrich** [comment]
@hanspagel looks like there's been a recent regression. 

Hitting Cmd+K several times after loading the sandbox  https://sandbox.scalar.com/e/korOI seems to bring up the search menu twice, the second time with a message saying no results.

Please see screencast below:

https://github.com/user-attachments/assets/d5e03f95-47f8-40b7-9942-fb74af34d6f9

**Comment by hanspagel** [comment]
Oh, damn! Opened a new issue, investigating.

**Comment by tnrich** [comment]
@hanspagel thanks for seeing to that issue being fixed. I have one last thing that is bothering me with the docs that hopefully will be an easy fix. I thought that cmd+k to toggle the search box was breaking some of the time but it turns out you need to lift your finger from the cmd key to retrigger it. I made an issue for it here. Would greatly appreciate it if you could take a look. Thanks!! - https://github.com/scalar/scalar/issues/2740

**Comment by tnrich** [comment]
@hanspagel I lied, there is one more bug I noticed 😆 

https://github.com/scalar/scalar/issues/2741
