### ISSUE TITLE
Servers override in configuration does not update the API Client URL

### ISSUE THREAD

**Issue by cpbr-dev** [scalar/scalar#2595]
### What happens?

When setting a server in the configuration, the URL used by the API Client is not updated and is the base URL of where Scalar is hosted.
```js
<script>
  var configuration = {
    theme: "default",
    servers: [
      {
        url: "https://test-server.com",
        description: "Server for testing override"
      },
    ],
  };
  document.getElementById("api-reference").dataset.configuration =
    JSON.stringify(configuration);
</script>
```
Here's what is shown in Base URL :
![image](https://github.com/user-attachments/assets/e171badd-9bd1-4004-aa29-c963a2cafaae)

Here's what is shown under an endpoint :
![image](https://github.com/user-attachments/assets/f21678b3-38d5-4070-9639-b0a95cc56050)

Here's what the API Client uses :
![image](https://github.com/user-attachments/assets/8ac8d230-316e-4cc6-b943-a7aec7428f98)

Additionally, hovering over the URL displays "Variable not found"

### What did you expect to happen?

The URL used for testing requests should change to the one defined in the `servers` parameter, or the one in the OpenAPI Spec provided if no override is done.

### How can we reproduce the issue?

Here's what I used :

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Test file</title>
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1" name="viewport" />
  </head>

  <body>
    <script
      id="api-reference"
      data-url="https://petstore.swagger.io/v2/swagger.json"></script>

    <script>
      var configuration = {
        theme: "default",
        servers: [
          {
            url: "https://test-server.com",
            description: "Server for testing override"
          },
        ],
      };
      document.getElementById("api-reference").dataset.configuration =
        JSON.stringify(configuration);
    </script>

    <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>
  </body>
</html>
```

**Comment by cpbr-dev** [comment]
https://sandbox.scalar.com/e/2fpJw

Trying it in the sandbox with the Swagger Pet Shop spec, it seems it always uses the base URL of the page :

![image](https://github.com/user-attachments/assets/fcadf4f6-bda0-4e42-9b04-c6c4b860588c)

**Comment by hanspagel** [comment]
Damn! Yes, that used to work but this part requires some work anyway. Definitely need to go over this again.

**Comment by cpbr-dev** [comment]
After trying some older versions, it seems the issue started with Scalar version 1.24.50.
v1.24.49 works as expected

**Comment by cpbr-dev** [comment]
Any updates on this issue ? The API Client seems to be unusable on versions past 1.24.49 because of this.

**Comment by antlio** [comment]
hey @cpbr-dev! sorry about that, we are actively working on this, won't miss to keep you updated here!

**Comment by antlio** [comment]
should be fixed by #2766

**Comment by jillxuu** [comment]
is the fix already released?

**Comment by marclave** [comment]
yes @jillxuu :)

**Comment by jillxuu** [comment]
I tested last good version is still 49Sent from my iPhoneOn Aug 27, 2024, at 10:55 AM, Marc Laventure ***@***.***> wrote:﻿
yes @jillxuu :)

**Comment by hanspagel** [comment]
It might be fixed with one of the PRs labelled as `on-hold`.

**Comment by amritk** [comment]
This should work now, please wait for next release then re-open if it isn't fixed! :) 

https://github.com/scalar/scalar/pull/3138

**Comment by Carrena-JW** [comment]
Cool 😎

**Comment by nikhildigde** [comment]
Issue still persists with the fastapi plugin

**Comment by omarmhaimdat** [comment]
> Hi, I'm using the scalar-fastapi plugin to use scalar and the issue still persists. Any updates on this?

Still the same issue
