### ISSUE TITLE
nuxt: Cannot read properties of null (reading 'isCE')

### ISSUE THREAD

**Issue by max06** [scalar/scalar#2596]
### What happens?

@scalar/nuxt@0.2.52 fails to load.

```
Cannot read properties of null (reading 'isCE')
```

![image](https://github.com/user-attachments/assets/727e1748-c494-4c60-8ec3-9b5502d64b63)

### What did you expect to happen?

Scalar should not fail to load

### How can we reproduce the issue?

Setup nuxt v3.12.4
Add @scalar/nuxt@0.2.52
Configure as described
Access rendered frontend using direct url.
See error.

**Comment by hanspagel** [comment]
Thanks for reporting! I think the `isCE` is an inidication for multiple vue versions. We’ll look into it.

**Comment by amritk** [comment]
This one was fixed! The latest version 0.2.74 should be out shortly
