### ISSUE TITLE
app adds the @scalar/galaxy example on every start

### ISSUE THREAD

**Issue by hanspagel** [scalar/scalar#2627]
When I reload the app, the content is restored from the local storage, but it also seems to add the @scalar/galaxy example every time I open it.

<img width="743" alt="Screenshot 2024-07-25 at 13 19 51" src="https://github.com/user-attachments/assets/d11b464d-324d-4ec4-a585-8dd06ab3dae4">

**Comment by amritk** [comment]
Hey I fixed this one yesterday! Which app still has it

**Comment by hanspagel** [comment]
You’re right! Can’t reproduce anymore.

**Comment by hanspagel** [comment]
Found it. :)
