### ISSUE TITLE
No config option to disable proxy

### ISSUE THREAD

**Issue by lukaw3d** [scalar/scalar#2634]
### What happens?

The default scalar configuration uses proxy.scalar.com to make requests to avoid CORS issues. I want to avoid using it for a server that allows CORS.

https://github.com/scalar/scalar/blob/1c5e9241b2232410178ef227f733430652e23a30/packages/api-reference/README.md?plain=1#L46-L50
> You can remove the `data-proxy-url` attribute if you don’t need it.

Removing the attribute or setting it to `data-proxy-url=""` does not remove the default
https://github.com/scalar/scalar/blob/1c5e9241b2232410178ef227f733430652e23a30/packages/api-reference/src/standalone.ts#L90-L93

https://github.com/scalar/scalar/blob/1c5e9241b2232410178ef227f733430652e23a30/packages/api-client/src/libs/create-client.ts#L103

### What did you expect to happen?

Document how to avoid using a proxy

### How can we reproduce the issue?

Without `data-proxy-url` https://codepen.io/luka-oasis/pen/abgmQzB?editors=1000
- click <kbd>Test Request</kbd> on `/planets`
- click <kbd>Send</kbd>
- see network request to https://proxy.scalar.com/?scalar_url=https%3A%2F%2Fgalaxy.scalar.com%2Fplanets%3Flimit%3D10%26offset%3D0

`data-proxy-url=""` https://codepen.io/luka-oasis/pen/KKjgrwO?editors=1000 still makes a request to https://proxy.scalar.com/?scalar_url=https%3A%2F%2Fgalaxy.scalar.com%2Fplanets%3Flimit%3D10%26offset%3D0

By reverse engineering [packages/api-reference/src/standalone.ts#L90-L93](https://github.com/scalar/scalar/blob/1c5e9241b2232410178ef227f733430652e23a30/packages/api-reference/src/standalone.ts#L90-L93) you can come up with `data-proxy-url="   "` https://codepen.io/luka-oasis/pen/bGPwQdz?editors=1000. This finally disables the proxy and requests https://galaxy.scalar.com/planets?limit=10&offset=0

**Comment by amritk** [comment]
Thanks for the ultra detailed ticket @lukaw3d! made this super easy, PR incoming

**Comment by thedewpoint** [comment]
@marclave @amritk how do i pull in this change? I tried updating my package json but I'm still seeing the issue as the old version is coming from the CDN
https://cdn.jsdelivr.net/npm/@scalar/api-reference

**Comment by marclave** [comment]
hey @thedewpoint , we released it this morning and the CDN (jsdelivr) just got purged, should be ready on latest version in the next 15 minutes :)
