### ISSUE TITLE
ReferenceError: process is not defined

### ISSUE THREAD

**Issue by MihaiVoinea** [scalar/scalar#264]
Hi,

I tried to use the `ApiReference` in a new Vue project, but I'm getting. `ReferenceError: process is not defined`.

Reproduction steps:
- Create a new Vue project: `npm create vue@latest`.
- Install dependencies: `npm install`.
- Add `@scalar/api-reference`: `npm install @scalar/api-reference`
- Replace the contents of `App.vue` with:
```vue
<script setup>
import { ApiReference } from '@scalar/api-reference'
</script>

<template>
  <ApiReference spec-url="https://petstore.swagger.io/v2/swagger.json" />
</template>
```
- Start the project: `npm run dev`.
- Open the page & check the console.

Initially, I tried to do it in my existing project and got this error, so I thought maybe I'll try with a brand new project but it was still not working. I followed the exact steps above.

I can provide a reproduction repo if needed.

I'm on Node v18.17.1.

**Comment by MihaiVoinea** [comment]
Yup, that seems to be it.

Got it working with the polyfills. Thanks Hans!

**Comment by hanspagel** [comment]
We can remove the need for the polyfills

**Comment by hanspagel** [comment]
Wait, this if fixed already. :) We switched to our own parser, which doesn’t require polyfills anymore: #1131
