### ISSUE TITLE
improve non api related errors 

### ISSUE THREAD

**Issue by marclave** [scalar/scalar#2705]
### What happens?

Currently when a user makes a request that doesnt actually send an http request, we throw no error and it silently fails

### What did you expect to happen?

we should showcase the error in the response section!

### How can we reproduce the issue?

send a request to localhost:1234

**Comment by antlio** [comment]
@hwkr is your work on #2764 fix this by any chance?

**Comment by hwkr** [comment]
> @hwkr does your work on #2764 is fixing this by any chance?

Yep! We should show all errors now :)
