### ISSUE TITLE
Nuxt module returns 500 after 8 seconds

### ISSUE THREAD

**Issue by ThomasWT** [scalar/scalar#2735]
### What happens?

8 seconds after the page loading, It seems like jsonpointer.js is looking for a default export and then returns a 500. Seems like an issue with parse5. Happens every refresh

### What did you expect to happen?

Not returning a 500 after 8 seconds

### How can we reproduce the issue?

https://stackblitz.com/edit/nuxt-starter-cw3k7f?file=nuxt.config.ts

log here:
[parse5.log](https://github.com/user-attachments/files/16459791/parse5.log)

**Comment by amritk** [comment]
Alright wanna try it again on version 0.2.74? it should be out shortly

**Comment by amritk** [comment]
Awesome! Mind closing the issue? I know there's a couple more minor bugs we can clean up but it works for the most part now

**Comment by ThomasWT** [comment]
yes for sure! Thank you a lot!!
