### ISSUE TITLE
Can't share scalar sandbox link?

### ISSUE THREAD

**Issue by tnrich** [scalar/scalar#2739]
### What happens?

Here's the exception that is eventually thrown when I press the Share button at the top right of the https://sandbox.scalar.com/ after pasting in my own swagger spec: 

[swagger.json](https://github.com/user-attachments/files/16462557/swagger.json)

 <img width="1368" alt="image" src="https://github.com/user-attachments/assets/b3c552cf-c062-41e1-a91f-fbbed73adc27">

### What did you expect to happen?

I expected something to pop up with info about how to share the scalar demo page 

### How can we reproduce the issue?

See above

**Comment by hanspagel** [comment]
Hm … I could only reproduce something similar in Safari. I’ve deployed a fix which works in Safari. Could you try again in Chrome?

**Comment by tnrich** [comment]
Nice, looks fixed, thanks @hanspagel !
