### ISSUE TITLE
Webhooks section anchor doesn't work

### ISSUE THREAD

**Issue by lephuongbg** [scalar/scalar#2774]
### What happens?

It looks like there is no anchor for Webhooks section yet (looking at the generated HTML), even though the sidebar link for the Webhooks section is pointing to `#webhooks`.

### What did you expect to happen?

There should be anchor for the Webhooks section. All of following should work:

1. Clicking on "Webhooks" in the sidebar should scroll to the Webhooks section.
2. Directly open the docs's URL with `#webhooks` appended should scroll to the Webhooks section.
3. Internal links to `#webhooks`  should scroll to the Webhooks section

### How can we reproduce the issue?

Go to sandbox link https://sandbox.scalar.com/e/usHBk

Case 1:

1. Try clicking on "Webhooks" in sidebar
2. Page doesn't scroll to Webhooks section

Case 2:

1. Try clicking "list of possible events" link in description for `Webhooks` tag.
2. Page doesn't scroll to Webhooks section

Case 3:

1. Open sandbox link with `#webhooks`: https://sandbox.scalar.com/p/usHBk#/webhooks
2. Page doesn't scroll to Webhooks section

### OpenAPI Document

https://sandbox.scalar.com/e/usHBk

**Comment by hanspagel** [comment]
Fix is in the PR pipeline :)
