### ISSUE TITLE
Unexpected `/` added to hash

### ISSUE THREAD

**Issue by hwkr** [scalar/scalar#2791]
### What happens?

It seems like our change to using the WebRequestRouter in #2597 added a `/` to the beginning of the hash on the navigate which is causing a number of comparisons to fail.

This is making tags not expand / collapse properly and making sidebar items not collapse correctly.

### What did you expect to happen?

There shouldn't be a `/` in the id on navigate.

### How can we reproduce the issue?

Click on any of the sidebar items or tags.

**Comment by hanspagel** [comment]
Ah, damn!

**Comment by hwkr** [comment]
> Ah, damn! Only affects the app, right?

No this is on references 😓

**Comment by hwkr** [comment]
Update: after a lot of debugging I've narrowed this down to the import of [`createWebHashHistory`](https://github.com/scalar/scalar/pull/2597/files#diff-11ea48608d091949763e6ad1e97645b6909990e889bba4c0c9b2b3a6c42d0b8eR6) which seems to somehow add that slash as a side effect of being imported... 😮‍💨
