### ISSUE TITLE
base url is missing

### ISSUE THREAD

**Issue by bpreston-asti** [scalar/scalar#2806]
### What happens?

![image](https://github.com/user-attachments/assets/eb7252c0-2cd7-4613-931b-b110ac7be020)

### What did you expect to happen?

I expected the request to be sent without issue.

### How can we reproduce the issue?

I am using .NET and am encluding the following html in a mapping.

<!doctype html>
<html>
<head>
    <title>Scalar API Reference -- {title}</title>
    <meta charset=""utf-8"" />
    <meta name=""viewport"" content=""width=device-width, initial-scale=1"" />
</head>
<body>
    {adminApiLink}
    <script id=""api-reference"" data-url=""swagger/v1/swagger.json"" data-proxy-url=""https://api.scalar.com/request-proxy""></script>
    <script src=""https://cdn.jsdelivr.net/npm/@scalar/api-reference""></script>                
</body>
</html>

**Comment by bpreston-asti** [comment]
I should note that everything was working prior to today, 8-7-24, it seems.

**Comment by hanspagel** [comment]
Thanks for the report! What does the URL in the address bar look like though? This toast should only pop up if you omit the http protocol or something like that.

And one other note: You’re using our old proxy, can you replace `https://api.scalar.com/request-proxy` with `https://proxy.scalar.com`? It does the same, but way better.

**Comment by bpreston-asti** [comment]
It looks like the following:
![image](https://github.com/user-attachments/assets/f2b88ec7-e0db-44b5-aa3c-8834d13e5278)

I didn't notice before that it wasn't correct. If I hover over '/v1/shop/' it says 'Variable not found.' Any ideas why the URL isn't being replaced with the actual URL to send the request to? Fwiw, if I replace it manually with the URL, it works fine.

**Comment by hanspagel** [comment]
Ok, yeah, the base URL is missing for some reason. Here is minimal example where it works:

https://sandbox.scalar.com/e/FR2nU

Are you able to share what’s in the `servers` key of the OpenAPI document (`swagger/v1/swagger.json`) you’re using? 

If you’re using a Swagger document (`"swagger": "2.0"`), we need the `host`, `basePath`, `schemes` keys.

You can replace the actual domain with something similar, just trying to reproduce the behaviour you’re seeing.

**Comment by bpreston-asti** [comment]
Figured it out. The server configuration option wasn't being set properly. Got it working now. Thanks so much for your help in leading me down the right path to fixing it!
