### ISSUE TITLE
changes to the base url in the reference don’t update the client

### ISSUE THREAD

**Issue by hanspagel** [scalar/scalar#2830]
When I change the base URL in the reference, it doesn’t change in the api client. That used to work. 🤔

Be aware that #2825 moves the relevant files. Maybe wait until this is merged. :)

**Sandbox**

https://sandbox.scalar.com/e/Tpnn8

**Screenshots**

![Screenshot 2024-08-09 at 21 29 18](https://github.com/user-attachments/assets/08abe238-cdd2-4653-95e8-f371c93c91ed)
![Screenshot 2024-08-09 at 21 29 23](https://github.com/user-attachments/assets/effbee52-8bbd-4759-ae7e-7fb2326cea70)

**Comment by amritk** [comment]
I think @antlio was working on this cc @marclave

**Comment by amritk** [comment]
But also the relevant code is still in there commented out if we need it

**Comment by antlio** [comment]
waiting for #2931 finalization

**Comment by hanspagel** [comment]
Good news: It’s solved already! Will release today/tomorrow. :)

**Comment by hanspagel** [comment]
Hopefully fixed forever in #3287
