### ISSUE TITLE
https://docs.scalar.com/ doesn't load

### ISSUE THREAD

**Issue by kantuni** [scalar/scalar#2842]
### What happens?

https://docs.scalar.com/ doesn't load

Console
```
Uncaught DOMException: Failed to construct 'WebSocket': The URL's scheme must be either 'ws' or 'wss'. 'https' is not allowed.
    at n (https://docs.scalar.com/assets/main-ByfvpMDr.js:189:19890)
    at H2e (https://docs.scalar.com/assets/main-ByfvpMDr.js:189:21742)
    at mst (https://docs.scalar.com/assets/main-ByfvpMDr.js:189:29270)
    at https://docs.scalar.com/assets/main-ByfvpMDr.js:2064:7942
```

### What did you expect to happen?

For it to work properly

### How can we reproduce the issue?

1. Go to https://docs.scalar.com/

**Comment by marclave** [comment]
hey @kantuni are you uploading a spec and its not loading? :)

**Comment by kantuni** [comment]
@marclave weird - the website just doesn't load in Arc (0.90.0) and Safari (16.6.1) - but it works perfectly well in Firefox (129.0.1)

**Comment by marclave** [comment]
hey @kantuni would you  mind sharing the error message in the console for arc/safari and we can look into it :)

works on 17+ for safari :)

<img width="1496" alt="image" src="https://github.com/user-attachments/assets/4657d853-0c89-4094-b73b-dc3466d115cc">

**Comment by kantuni** [comment]
It's the one I've shared above

> Console
> 
> ```
> Uncaught DOMException: Failed to construct 'WebSocket': The URL's scheme must be either 'ws' or 'wss'. 'https' is not > > allowed.
>     at n (https://docs.scalar.com/assets/main-ByfvpMDr.js:189:19890)
>     at H2e (https://docs.scalar.com/assets/main-ByfvpMDr.js:189:21742)
>     at mst (https://docs.scalar.com/assets/main-ByfvpMDr.js:189:29270)
>     at https://docs.scalar.com/assets/main-ByfvpMDr.js:2064:7942
> ```

**Comment by kantuni** [comment]
Here are a few screenshots

<img width="1440" alt="Screen Shot 2024-09-09 at 6 22 04 AM" src="https://github.com/user-attachments/assets/6f5efd51-6a01-40ca-a5bd-e9bbcdf96026">

<img width="1440" alt="Screen Shot 2024-09-09 at 6 23 28 AM" src="https://github.com/user-attachments/assets/bd509a64-c351-4027-b6da-372bf123b78a">

**Comment by antlio** [comment]
hey @kantuni thanks for the issue and feedbacks, this is currently in progress and will patch it in the upcoming days, will notify here as soon as it is!

**Comment by kantuni** [comment]
Thanks a ton, @antlio!

**Comment by kantuni** [comment]
@marclave This issue hasn't been resolved. Why is being it marked as "completed"?

**Comment by antlio** [comment]
sorry @kantuni automatic workflow 😄 almost there!

**Comment by marclave** [comment]
hey @kantuni this has been fixed :)

**Comment by kantuni** [comment]
Works perfectly 🎉
Thank you!
