### ISSUE TITLE
No more commonjs support for hono-api-reference

### ISSUE THREAD

**Issue by flipvh** [scalar/scalar#2910]
### What happens?

It seems that after this change: 
https://github.com/scalar/scalar/commit/9b2125164855473dfebf927d9b622175ce088cb0#diff-9eb87f7dee17b0fdf06e24c55a0cc8b2a2f82a57a195e3462554c571b161eb66R29

Our codebase - which unfortunately atm runs on CommonJS - complains about 

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in ../cella/backend/node_modules/@scalar/hono-api-reference/package.json
```

Is CommonJS not supported by scalar? Thnk you! 

### What did you expect to happen?

That hono-api-reference also has a .cjs build in dist folder and that it is mentioned in package.json exports.

### How can we reproduce the issue?

Good question. Import the hono-api-reference in a CommonJS project. I can try to figure out how to make this reproducable in a simple way if that is necessary.

**Comment by flipvh** [comment]
This was a good excuse to simply find out why I was still using CommonJS. I managed to switch my entire project to ESM, so perhaps we can close this issue

**Comment by amritk** [comment]
haha yea we don't officially support commonjs but we do have support on a few of the packages. Upgrading to ESM is definitely the way to go 👍🏾
