### ISSUE TITLE
Test Request with "Form URL Encoded" is sent with Content-Type: "multipart/form-data"

### ISSUE THREAD

**Issue by yvzn** [scalar/scalar#2918]
### What happens?

When setting "Form URL Encoded" for the type of body in the "Test Request" window, the request is sent to the server with Content-Type: "multipart/form-data; boundary=...." instead of "application/x-www-form-urlencoded"

Despite the fact that the "Headers" section displays "Content-Type": "application/x-www-form-urlencoded"

### What did you expect to happen?

The request to the server is sent with "Content-Type": "application/x-www-form-urlencoded"

### How can we reproduce the issue?

1. Go to https://sandbox.scalar.com/e/_wHkn
2. Click on "Test Request" of the first route
3. Select "Form URL Encoded" in the Body section
4. Click on "Send"
5. Inspect the request in the DevTools, it is sent with the wrong content-type

### OpenAPI Document

https://sandbox.scalar.com/e/_wHkn

**Comment by yshrsmz** [comment]
@hanspagel Hi, I still see the same issue.
See https://sandbox.scalar.com/e/M67H7 for the repro. reproduction step is the same as the OP.
