### ISSUE TITLE
scrollbar-test is causing incorrect layout

### ISSUE THREAD

**Issue by emilio-toledo** [scalar/scalar#2924]
### What happens?

The following file:

https://github.com/scalar/scalar/blob/a792002867dc0785c5fb1736b1451c2295f7073d/packages/themes/src/utilities/hasObtrusiveScrollbars.ts#L14

is messing with the layout:

https://github.com/user-attachments/assets/829d98f4-54d1-4ced-8f3b-5ec0c73a64f3

### What did you expect to happen?

A correct layout as shown in previous versions (tested with `@scalar/fastify-api-reference@1.25.3`)

https://github.com/user-attachments/assets/6aa104f1-77c8-4044-b2d5-e71703c876dd

### How can we reproduce the issue?

1. Create a new fastify app
2. Install `@fastify/swagger` and `@scalar/fastify-api-reference@1.25.4` (latest at this point in time)
3. Make an example project:
```ts
import fastify from "fastify";
import swagger from "@fastify/swagger";
import scalar from "@scalar/fastify-api-reference";

export const app = fastify({ logger: true });

app.register(swagger, {
	openapi: {
		openapi: "3.1.0",
		info: {
			title: "Example API",
			description: "Example api documentation",
			version: "1.0.0",
		},
	},
});

app.register(scalar, {
	routePrefix: "/reference",
	configuration: {
		theme: "none",
		spec: {
			content: () => app.swagger(),
		},
	},
});

app.listen({ port: 8080 }, (err, address) => {
	if (err) {
		console.error(err);
		process.exit(1);
	}

	app.log.info(`Server listening at ${address}`);
});
```
4. The incorrect layout should now be visible.

### OpenAPI Document

_No needed_

**Comment by hwkr** [comment]
Hey @emilio-toledo, sorry about that! That test div is supposed to be removed after the test runs. Opened a PR with a fix.

**Comment by emilio-toledo** [comment]
No problem @hwkr, thank you for the fast response!

I have just downgraded to 1.25.3 in the meantime.
