### ISSUE TITLE
Nuxt error scalar doesn't load correctly

### ISSUE THREAD

**Issue by ProjectBetelgeuse** [scalar/scalar#2927]
### What happens?

When I add scalar ad a module to the nuxt setting file. the webpage didn't load. Even the root path fail to load. 
This error showed up in the console. 

```
[nuxt] `#imports` should be transformed with real imports. There seems to be something wrong with the imports plugin.
[Vue Router warn]: No match found for location with path "/"
``` 

### What did you expect to happen?

The root path should be what ever I put in the app.vue and /scalar or /doc should show the scalar doc page. 

### How can we reproduce the issue?

https://codesandbox.io/p/devbox/rough-resonance-46kd6c

Create a nuxt project, add the scalar module in the config file.

**Comment by Mdev303** [comment]
any update on this ?

**Comment by amritk** [comment]
Hey @Mdev303 theres a couple minor hydration errors, but it seems to be working for me, check out this repo

https://github.com/amritk/nuxt-test
```
bun i
bun dev
```
and visit [http://localhost:3000/docs](http://localhost:3000/docs)
