### ISSUE TITLE
Headers is not visible in documentation

### ISSUE THREAD

**Issue by LWJerri** [scalar/scalar#2939]
### What happens?

I just noticed I can't find headers that return with a response in Scalar docs, but in Swagger docs this headers available (visible).

1. Scalar docs:
![image](https://github.com/user-attachments/assets/989f5f42-c9d7-4b71-b5b5-c0aa5caa65cb)

2. Swagger docs:
![image](https://github.com/user-attachments/assets/54bf2333-63f0-4e24-aaae-023f71157560)
that

### What did you expect to happen?

Headers that come with a response should be visible in docs.

### How can we reproduce the issue?

1. Create simple NestJS route.
2. Add Swagger decorators:
```ts
  @ApiOkResponse({
    type: GetStructureResponseDto,
    isArray: true,
    description: REQUEST_RESPONSES.OK,
    headers: {
      [CACHE_HEADER]: {
        description: "Indicates if the data is cached.",
        schema: {
          type: "string",
          example: CACHE_HEADER_STATUS.CACHED,
        },
      },
    },
  })
  @Header(CACHE_HEADER, CACHE_HEADER_STATUS.CACHED)
```
3. Open Scalar docs page and try to find response header :shipit: 

### OpenAPI Document

https://sandbox.scalar.com/e/UtW5o

**Comment by hanspagel** [comment]
Yess, they are still hidden! We need to fix the layout for responses with a lot of headers.
