### ISSUE TITLE
Nuxt-module - Cannot find ~/src/types' 

### ISSUE THREAD

**Issue by Cry0nicS** [scalar/scalar#2944]
### What happens?

With `"@scalar/nuxt": "^0.2.84",` I run into the following, when running the development server:

```
Cannot find module '~/src/types' or its corresponding type declarations.
../node_modules/@scalar/nuxt/dist/runtime/components/ScalarApiReference.vue:5:36

    3 | import { ModernLayout, parse } from '@scalar/api-reference'
    4 | import { reactive, ref, toRaw } from 'vue'
  > 5 | import type { Configuration } from '~/src/types'
      |                                    ^^^^^^^^^^^^^
    6 |
    7 | const props = defineProps<{
    8 |   configuration: Configuration

[vue-tsc] Found 1 error. Watching for file changes.
```

### What did you expect to happen?

I'd expect this to not be an error.

### How can we reproduce the issue?

Install nuxt module with `npx nuxi module add @scalar/nuxt`

Added the following to `nuxt.config.ts`
```
    nitro: {
        experimental: {
            openAPI: true
        }
    },
    scalar: {
        darkMode: true,
        theme: "nuxt",
        metaData: {
            title: "API Documentation by Scalar"
        }
    }
```

Run `npm run dev`

**Comment by hanspagel** [comment]
Bummer! We need to look into this.

**Comment by amritk** [comment]
Ah we need to use the new types package! On it 🫡

**Comment by amritk** [comment]
Hmm I tried re-producing and I could not. Also our latest nuxt fixes haven't been released yet. Let me get those out then lets see if this is still an issue

**Comment by amritk** [comment]
@Cry0nicS could you try again with version `0.2.85` and if it still doesn't work, wanna make a minimal reproducible example?

**Comment by Cry0nicS** [comment]
@amritk I've tried to reproduce it in a sandbox, but I couldn't.
Locally, I still run into the same issue. I am also getting
```
Failed to resolve dependency: @scalar/nuxt > ajv-draft-04, present in 'optimizeDeps.include'  
```

Since I cannot reproduce it in a sandbox, i guess you can close this?

**Comment by amritk** [comment]
Yea those dependency warnings won't affect it. Sorry but ya I couldn't replicate it either

**Comment by holwech** [comment]
Hi @amritk @hanspagel, we're experiencing the same issue when running `nuxi typecheck`:

```
node_modules/@scalar/nuxt/dist/runtime/components/ScalarApiReference.vue:9:36 - error TS2307: Cannot find module '~/src/types' or its corresponding type declarations.

9 import type { Configuration } from '~/src/types'
                                     ~~~~~~~~~~~~~


Found 1 error in node_modules/@scalar/nuxt/dist/runtime/components/ScalarApiReference.vue:9
```

Looking at `node_modules`, it seems like the `src` folder doesn't exist?

![image](https://github.com/user-attachments/assets/7abd44a6-e4bf-49cc-90e6-c58f12b73235)

This is with Scalar `0.2.141`. Tried to clean the build/cache folders and delete `node_modules` and build it again, but no luck so far.
