### ISSUE TITLE
No "exports" main defined

### ISSUE THREAD

**Issue by hanspagel** [scalar/scalar#2994]
When using the `@scalar/hono-api-reference` with tsx it seems to throw the following error:

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /node_modules/@scalar/hono-api-reference/package.json

More context: #2993

**Comment by thibaultleouay** [comment]
I also have this issue when I run 
> build with tsup 
> start with node dist/index.js

**Comment by johntrinhcode** [comment]
For anyone coming across this thread, here's a workaround with `pnpm` to [patch](https://pnpm.io/cli/patch) the package in the meantime.

1. Run `pnpm patch @scalar/hono-api-reference@<version>`. You'll be given a temp patch directory to start making changes.
2. Update `package.json` in the patch directory.
```jsonc
     // <temp-patch-dir>/package.json
     ...
     ".": {
       "import": "./dist/index.js",
       "types": "./dist/index.d.ts",
       "default": "./dist/index.js", // add this
     }
```
3. Commit your patch with `pnpm patch-commit <temp-patch-dir>`
4. A new `patch` directory should be created at your project root, your project will begin referencing these changes when running this lib.
5. Run your project, should work now. Check back for a fix on this lib so you can remove the patch in the future.
