### ISSUE TITLE
e.headers.getSetCookie is not a function

### ISSUE THREAD

**Issue by kantuni** [scalar/scalar#3050]
### What happens?

When I click the "Send" button in the "Test request" modal, I get a toast message that says

```
e.headers.getSetCookie is not a function
```

### What did you expect to happen?

It should successfully send the request

**Comment by hanspagel** [comment]
Any chance you can share your OpenAPI document? I’m not sure this happens with all documents.

**Comment by amritk** [comment]
GetSetCookie should be a part of headers. I don't think it has to do with the spec, but with the environment.

**Comment by hanspagel** [comment]
Interesting! Where do you see this error? @kantuni

**Comment by kantuni** [comment]
> Interesting! Where do you see this error? @kantuni

<img width="1440" alt="Screen Shot 2024-09-08 at 12 34 41 AM" src="https://github.com/user-attachments/assets/71a4620d-07b2-49d8-9466-9d3f98749c63">

**Comment by kantuni** [comment]
> GetSetCookie should be a part of headers. I don't think it has to do with the spec, but with the environment.

Oh, it looks like `getSetCookie` is only supported in Chrome 113+ (according to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Headers/getSetCookie)).

Would you be against a [polyfill](https://github.com/mswjs/headers-polyfill) to support older browsers? I'm happy to send the PR if that helps!

**Comment by hanspagel** [comment]
I’d prefer to have this as part of the build process. Vite recommends to use Cloudflare polyfills:

> Note that by default, Vite only handles syntax transforms and does not cover polyfills. You can check out https://cdnjs.cloudflare.com/polyfill/ which automatically generates polyfill bundles based on the user's browser UserAgent string.

Not a big fan of adding another external asset, though. 🤔

**Comment by kantuni** [comment]
I'm not sure you can handle this specific scenario in the build process.

I believe `pnpm install headers-polyfill` should get you halfway there.

It looks like there is only [1 instance](https://github.com/scalar/scalar/blob/6bb85a510c2690ee2219eaa72ba337713cf03d24/packages/api-client/src/libs/sendRequest.ts#L87) of `getSetCookie`, so it shouldn't be too much work. I'm happy to send the PR – I understand this is not a "priority" item.

**Comment by amritk** [comment]
Oh thats my mistake, I didn't realize it was so new! Instead of a polyfill we can just check for `'getSetCookie' in headers` I have it done in the refactor branch

**Comment by hanspagel** [comment]
Nice!

**Comment by kantuni** [comment]
Thanks, @amritk!
