### ISSUE TITLE
`@scalar/fastify-api-reference` should expose an endpoint for the OpenAPI document

### ISSUE THREAD

**Issue by danwithabox** [scalar/scalar#3065]
### What happens?

I am using `@fastify/swagger` and am investigating swapping from `@fastify/swagger-ui` to `@scalar/fastify-api-reference`.

Scalar is much nicer, thank you for making it, but I've hit a roadblock:
Some of my tooling fetches the OpenAPI spec JSON file from a URL provided by `@fastify/swagger-ui`.

With `@scalar/fastify-api-reference`, it seems no such URL exists, despite https://github.com/scalar/scalar/pull/2947

Is there no endpoint I can fetch that would result in the spec JSON file?

### What did you expect to happen?

Be able to fetch the spec JSON for use in external tooling, but no endpoint exists to grab it from

**Comment by hanspagel** [comment]
Ah, `@scalar/fastify-api-reference` does the rendering only. You can use `@fastify/fastify-swagger` to generate your OpenAPI document, and expose and an endpoint for it and pass that endpoint to `@scalar/fastify-api-reference`.

Does that help? I should make this more clear in the README.

**Comment by danwithabox** [comment]
Cheers for the fast response, I will look into the suggestion.

I've mostly followed this documentation: https://github.com/scalar/scalar/tree/main/packages/fastify-api-reference
It does say 

> Actually, we’re picking it up automatically, so this would be enough:
> ```ts
> await fastify.register(require('@scalar/fastify-api-reference'), {
>   routePrefix: '/reference',
> })
>```

That made me assume it would be a drop-in replacement of `@fastify/fastify-swagger`, and it was, except for the download link issue.
I scrolled through https://www.npmjs.com/package/@scalar/fastify-api-reference for extra hints, to no avail.

Now though, I do see the NPM doc linking to this: https://github.com/scalar/scalar/blob/main/documentation/integrations/fastify.md#set-up-fastify-swagger-optional
Which in turn has this in its depths:
```ts
// Serve an OpenAPI file
fastify.get('/openapi.json', async (request, reply) => {
  return fastify.swagger()
})
```

Coming solely from `@fastify/swagger-ui`, I assure you this is the first time I saw `@fastify/fastify-swagger` used like that 😄

I would assume most people who come from `@fastify/swagger-ui` are in the same boat as me, and would save us digging through a few scattered docs and make the switch to Scalar trivial, if `@scalar/fastify-api-reference` would expose an endpoint by default.

For reference, `@fastify/swagger-ui`'s download link seems to point to`${routePrefix}/json`

And for the record, the only other incompatibility is that `@fastify/swagger-ui` seems to overbearingly have Fastify's ```ignoreTrailingSlash: true``` set somewhere, had me scratching my head for 2 minutes as to why Scalar won't load with my old links. Might warrant a mention in the docs?

I will try these changes a bit later and report back.

**Comment by danwithabox** [comment]
I exposed the docs, and it does work, but whereas the swagger-ui config was a one-liner:
```ts
const routePrefix = `/reference`;

await fastify.register(fastifySwaggerUi, { routePrefix, });
```
such elegance is now gone:
```ts
const routePrefix = `/reference`;
const routePostfix = `/json`;

fastify.get(`${routePrefix}${routePostfix}`, { schema: { hide: true, }, }, async () => {
    return fastify.swagger();
});

await fastify.register(fastifyScalar, {
    routePrefix,
    configuration: {
        spec: {
            url: `${routePrefix}${routePostfix}`,
        },
    },
});
```
Note the `hide: true` in `schema`, without this the exposed endpoint would end up in the spec.

Definitely a step back from the _"Actually, we’re picking it up automatically, so this would be enough"_ minimal example over at: https://github.com/scalar/scalar/tree/main/packages/fastify-api-reference

And as for the trailing slash, that is handled weirdly by `@fastify/swagger-ui`, it is not a redirect, whereas here I can solve it with one, but I elected not to.

So yes, if the minimal config of
```ts
await fastify.register(fastifyScalar, { routePrefix, })
```
would handle exposing `/reference/json`, that would be a kind change for folks moving over from `@fastify/swagger-ui`, keeping it a one-liner! 😄

**Comment by hanspagel** [comment]
Nice! That’s awesome feedback. If you don’t find time to make PR leave a short note and I’ll submit one. :)

**Comment by hanspagel** [comment]
Hey, this was done in #3098!
