### ISSUE TITLE
cmd+k doesn’t work in the API client modal

### ISSUE THREAD

**Issue by hanspagel** [scalar/scalar#308]
When the API client modal is open, cmd+k doesn’t work.

**Comment by Mohib834** [comment]
Hey @hanspagel, could you add the step to reproduce the issue please? I would like to contribute to this issue.

**Comment by marclave** [comment]
@Mohib834 @hanspagel I was unable to reproduce this on the CDN version of Scalar, or any of the integrations.

@hanspagel are you able to provide a codesandbox or some small reproducibility cause it appears this is fixed

**Comment by Mohib834** [comment]
> @Mohib834 @hanspagel I was unable to reproduce this on the CDN version of Scalar, or any of the integrations.
> 
> @hanspagel are you able to provide a codesandbox or some small reproducibility cause it appears this is fixed

To me, it also appears to be fixed. Couldn't reproduce it.

**Comment by hanspagel** [comment]
Can’t reproduce it either. Awesome! 🫶
