### ISSUE TITLE
Long description on API are cut off with no way to see the hidden content

### ISSUE THREAD

**Issue by davidhu2000** [scalar/scalar#3081]
### What happens?

if the description on an API is long, the string is automatically cut off without a way to view the hidden content

![Screenshot 2024-09-11 at 8 24 10 PM](https://github.com/user-attachments/assets/480dc153-ac8f-400b-a873-11d43961ed72)

this issue was introduced when i upgraded 

```diff
- "@scalar/api-reference-react": "0.3.85",
+ "@scalar/api-reference-react": "0.3.86",
```

Reverting to 0.3.85 fixed the issue

### What did you expect to happen?

All the description text are visible 

### OpenAPI Document

https://sandbox.scalar.com/e/P_lI9

**Comment by amritk** [comment]
@hwkr did you do something similar recently?

**Comment by hwkr** [comment]
I think it should be fixed in #3077! Just hasn't been release yet, feel free to reopen if the next release doesn't fix it

**Comment by davidhu2000** [comment]
looks like `0.3.87` did fix this issue.

**Comment by hwkr** [comment]
> looks like `0.3.87` did fix this issue.

Awesome!!
