### ISSUE TITLE
JavaScript fetch example code can't be generated

### ISSUE THREAD

**Issue by cybercoder-naj** [scalar/scalar#3094]
### What happens?

The "JavaScript fetch" version of the code can't be generated. The "Shell cURL" works as expected.

![image](https://github.com/user-attachments/assets/6da51250-fdea-4ca2-b335-fbba140c5b93)

![image](https://github.com/user-attachments/assets/21fa37e9-405b-452f-8bc9-72cbbb3034b1)

### Additional info

All of the other JavaScript flavours produce the same output. E.g. XHR, jQuery have the same output

![image](https://github.com/user-attachments/assets/88c8919b-2b40-4a3b-9c77-3ec30549c0d0)

### What did you expect to happen?

Correctly generate the example code for the JavaScript flavours.

**Comment by hanspagel** [comment]
Oh, great report! That’s one for me

**Comment by Obsidianninja11** [comment]
`HTTP HTTP/1.1` is also empty, and the "JavaScript flavours produce the same output" as the Author stated applies to other languages as well.

**Comment by hanspagel** [comment]
Taken care of in #3113! Thanks for the great reports!
