### ISSUE TITLE
SectionHeader uses h1 for all headings, use different levels

### ISSUE THREAD

**Issue by hanspagel** [scalar/scalar#310]
The SectionHeader uses h1 everywhere. We should only use h1 for the spec title, and h2 + h3 for the rest.

**Comment by ATREAY** [comment]
hey @hanspagel,  I would like to work on this issue if it's open.
Additionally, could you provide a link or reference to the location of this issue?

**Comment by hanspagel** [comment]
Awesome! The `Section` component renders a `<h1>`. I’d prefer it to have an optional `level` prop with default of `1` and render the heading accordingly.

https://github.com/scalar/scalar/blob/main/packages/api-reference/src/components/Section/SectionHeader.vue#L12C2-L17

**Comment by ATREAY** [comment]
Hey @hanspagel, I have implemented the necessary modifications. 
Could you please inform me if there are any further actions or tasks I need to undertake?
