### ISSUE TITLE
[Scalar.AspNetCore] Settings Dark mode by default isn't working

### ISSUE THREAD

**Issue by maximeozenne** [scalar/scalar#3104]
### What happens?

Hello,

I added this code to configure the default behaviour of `Scalar` inside my API :

```
app.MapScalarApiReference(options =>
{
    options
        .WithTheme(ScalarTheme.Default)
        .WithDarkMode(true)
        .WithDefaultHttpClient(ScalarTarget.CSharp, ScalarClient.HttpClient)
        .WithPreferredScheme("Http");
});
```

Every settings are working except the Dark Mode.

Any modification I can add on other settings are working. For example, if I add `.WithSidebar(false)`, the Sidebar disappear as expected. 

### What did you expect to happen?

I was expecting the UI to be in Dark Mode by default, but the UI is loading in Light Mode everytime. I have to use the toggle to switch to Dark Mode.

**Comment by maximeozenne** [comment]
My bad, I had to use the `.WithForceThemeMode(ThemeMode.Dark)`.

Thanks for your amazing work !

**Comment by xC0dex** [comment]
Hey @maximeozenne,

It was actually a bug, but it's fixed now! So you don't have to force the theme mode anymore.

**Comment by maximeozenne** [comment]
Thank you!!
