### ISSUE TITLE
API Client: Basic Auth credentials not properly encoded when password is empty

### ISSUE THREAD

**Issue by dbrkv** [scalar/scalar#3124]
### What happens?

When using the built-in API client with Basic Authentication and providing only a username with an empty password, an Authorization header is incorrectly generated. 
The current behaviour produces a Bearer token instead of the expected Basic Auth format.

I am using package `@scalar/hono-api-reference ^0.5.146`

### What did you expect to happen?

The API client's Authorization header should be prefixed with "Basic"
Credentials (username:password) should be Base64 encoded, even when the password is empty

**Comment by hanspagel** [comment]
True!

**Comment by inyourtime** [comment]
I can make PR for this 👀

**Comment by hanspagel** [comment]
This seems to be fixed already, but it’s not released yet.

Preview: https://client.scalar.com/

**Comment by dbrkv** [comment]
Almost there :)
Checked version 0.5.150 today. Authorization scheme is correct, but there's still an issue with the format of the credentials:
When a password isn't provided, the credentials divider `:` is missing.
So, the decoded credentials come out as just `username` instead of `username:`.
