### ISSUE TITLE
your demo does not work in chrome

### ISSUE THREAD

**Issue by LukasGoTom** [scalar/scalar#3128]
### What happens?

open
https://docs.scalar.com/swagger-editor

﻿
swagger-editor:1 Uncaught DOMException: Failed to construct 'WebSocket': The URL's scheme must be either 'ws' or 'wss'. 'https' is not allowed.
    at n (https://docs.scalar.com/assets/main-BddZxNko.js:189:19890)
    at wye (https://docs.scalar.com/assets/main-BddZxNko.js:189:21742)
    at Xat (https://docs.scalar.com/assets/main-BddZxNko.js:189:29302)
    at https://docs.scalar.com/assets/main-BddZxNko.js:1835:7498

stuck forever in 

![image](https://github.com/user-attachments/assets/d2c059bb-cbcf-4b71-9f6e-60fe37f62433)

works in firefox

### What did you expect to happen?

that it works under chrome

**Comment by antlio** [comment]
fixed by [#1907](https://github.com/scalar/scalar-org/pull/1907)
