### ISSUE TITLE
Python requests - still showing http.client (on 1.25.11)

### ISSUE THREAD

**Issue by Theodlz** [scalar/scalar#3131]
### What happens?

When select `python/requests`, it actually still shows me the code snippet for `python/http.client`. This happens even with the provided example for HTTP.

PS: It seems to be working just fine when I use the interactive editor, so I suspect this is a HTTP integration-specific problem? 

### What did you expect to happen?

When instead, it should show the code snippet using python's pip-installable `requests` package, that I suspect almost everyone using Python will be familiar with, when `http.client` is much less common as the go-to for API calls.

This is definitely a big blocker to transition from redoc/swagger to scalar. That aside, I'm in love with this :) The UI is so clean!

### PS: **This problem does not happen when using @scalar/api-reference@1.25.10, it is introduced in version 1.25.11**

**Comment by hanspagel** [comment]
Sorry, this is fixed already, but not released! The release pipeline is blocked rn, but we’ll be able to unblock it today/tomorrow it seems.

Preview:
https://scalar-deploy-preview.netlify.app/standalone-api-reference

**Comment by Theodlz** [comment]
> Sorry, this is fixed already, but not released! The release pipeline is blocked rn, but we’ll be able to unblock it today/tomorrow it seems.
> 
> Preview: https://scalar-deploy-preview.netlify.app/standalone-api-reference

Awesome, thanks!!!

**Comment by Theodlz** [comment]
looks like it was fixed now! Closing, and thanks again
