### ISSUE TITLE
Clicking on any endpoint on the search modal don't do anything

### ISSUE THREAD

**Issue by thelinuxlich** [scalar/scalar#314]
### Expected Behavior

When clicking any endpoint link on the search modal, user should navigate to the desired link

### Actual Behavior

Nothing happens

### Reproduction steps

```bash
1. Go to https://docs.scalar.com/swagger-editor
2. Click on the Petstore example
3. Click on the Search text input, so the modal appears, click on any endpoint
4. Nothing happens
```

### Version

latest

### What browsers are you seeing the problem on?

Chrome

**Comment by marclave** [comment]
@thelinuxlich thanks for reporting this! I got a fix here :) https://github.com/scalar/scalar/pull/317

Will wait for review and then will get this in asap
