### ISSUE TITLE
Example request adds "content-type: application/json" header in GET request

### ISSUE THREAD

**Issue by subzero10** [scalar/scalar#3142]
### What happens?

I have two endpoints which are almost identical in the openapi.json file (GET /api/client and GET /api/account).
GET /api/account works as expected, but GET /api/client is causing my backend to throw an exception because the request is sent with "Content-Type: application/json" and my backend is trying to deserialize the non-existent body the request.

I can't share the full openapi.json file, but here's an excerpt of the two endpoints:
```
"/api/client": {
  "get": {
    "tags": [
      "Client"
    ],
  "summary": "Get clients",
  "operationId": "ApiEndpointsClientIndex",
  "parameters": [...],
  "responses": {...}
  },
},
"/api/account": {
  "get": {
    "tags": [
      "Account"
    ],
    "summary": "Get accounts",
    "operationId": "ApiEndpointsAccountIndex",
    "parameters": [...],
    "responses": {...}
  },
}
```

When testing an example request for GET /api/account, it does not add the header and I get a valid response.
![CleanShot 2024-09-19 at 10 30 36@2x](https://github.com/user-attachments/assets/151faae7-7de7-4120-bb7b-2a9046d016f1)

When testing an example request for GET /api/client, the Content-Type: application/json header is added which which causes the exception on my backend.
![CleanShot 2024-09-19 at 10 31 14@2x](https://github.com/user-attachments/assets/793c4e19-1138-43fe-a380-24e96c4813e9)

### What did you expect to happen?

I would expect to either both requests to have the included Content-Type header by default, or none of them to have it, since they have almost identical definitions in the json file.

**Comment by amritk** [comment]
Hello! If you update the client, you will find that we no longer set any content type and leave it up to the user!

**Comment by subzero10** [comment]
Hey @amritk, unfortunately I can't use the latest version of the client - it's crashing the UI. I've reported the issue here #3165.

**Comment by subzero10** [comment]
@amritk, I just tested this with 1.25.17 and it seems that the issue is resolved.
Thanks!

**Comment by jonasfroeller** [comment]
This still happens to me using `v1.25.58`.

**Comment by wegylexy** [comment]
How to eliminate the `Content-Type` header by default? The `Test Request` dialog says `This is a readonly property and you can not modify it! If you want to change it you have to override it or disable it using the checkbox` but I don't want to click the checkbox every time. I am at `@scalar/fastify-api-reference:1.48.0`.
