### ISSUE TITLE
`data-proxy-url` completely ignored in 1.25.12

### ISSUE THREAD

**Issue by Stealthmate** [scalar/scalar#3152]
### What happens?

Pretty much the title. At first I thought I was running into #2634, but this time it's impossible to set the proxy to _anything_, let alone disable it. E.g. even if I do `data-proxy-url="asd"`, the client still sends requests to `https://proxy.scalar.com`.

This is not an issue in 1.25.11, which leads me to think the problem might be because `api-reference` bumped it's `api-client` version to 2.1.0. But since I also need the fixes from #3138 and AFAIK those are only available in 1.25.12, I'm kind of bummed right now :disappointed: 

### What did you expect to happen?

`data-proxy-url` being reflected in client (and disabled if field is missing).

### OpenAPI Document

N / A

**Comment by marclave** [comment]
hey @Stealthmate im investigating right now :)

**Comment by marclave** [comment]
fix in here @Stealthmate https://github.com/scalar/scalar/pull/3154

will comment once it's released ❇️ 

we did a huge refactor in #3148 and this got lost, apologies

**Comment by marclave** [comment]
@Stealthmate fixed in latest patch :)

**Comment by Evoolo** [comment]
Hi, i think this issue is back again :)

**Comment by marclave** [comment]
hi @Evoolo! yes this was a recent bug, good news this is fixed in latest release :)
