### ISSUE TITLE
C# package missing some methods

### ISSUE THREAD

**Issue by enricoroselino** [scalar/scalar#3156]
### What happens?
1. options method missing from example [program.cs](https://github.com/scalar/scalar/blob/main/packages/scalar.aspnetcore/playground/Scalar.AspNetCore.Playground/Program.cs)

![image](https://github.com/user-attachments/assets/28bc08cb-8a32-49f6-b9bc-c00b2f5605a8)

2. the MapScalarApiReference option darkMode not set dark mode as initial theme mode, wether i set it true / false.

also not working using the builder pattern
![image](https://github.com/user-attachments/assets/b093dfd1-85ff-404f-8fb7-c59fb1eb7774)

C# .NET 9 using scalar package

### What did you expect to happen?

should be dark mode at initial page opening
![image](https://github.com/user-attachments/assets/45a336bc-2812-4e30-a952-23f298a09d8f)

**Comment by enricoroselino** [comment]
or its not intended as example in the fist place ?

**Comment by xC0dex** [comment]
Hey @enricoroselino,

Thanks for the bug report.

> 1. options method missing from example [program.cs](https://github.com/scalar/scalar/blob/main/packages/scalar.aspnetcore/playground/Scalar.AspNetCore.Playground/Program.cs)

These methods are not part of the `Scalar.AspNetCore` package. The NuGet only contains anything that is required to set up Scalar. The extension methods you are looking for are part of [`APIWeaver.OpenApi`](https://github.com/xC0dex/APIWeaver/blob/main/docs/Getting-Started.md#apiweaveropenapi) package that I build for .NET 9.

> 2. the MapScalarApiReference option darkMode not set dark mode as initial theme mode, wether i set it true / false.

You're right. I was able to reproduce this issue. I'll fix it 👍.
