### ISSUE TITLE
Missing `Content-Type: application/json`

### ISSUE THREAD

**Issue by rhea-so** [scalar/scalar#3157]
### What happens?

Request header content-type is missing when send json data.

<img width="673" alt="image" src="https://github.com/user-attachments/assets/867e8645-3b05-4096-8f74-ecaeeb2a9032">

<img width="741" alt="image" src="https://github.com/user-attachments/assets/f1578241-2d77-465f-a9c7-0829276427e3">

https://cdn.jsdelivr.net/npm/@scalar/api-reference@1.25.12 and   
https://cdn.jsdelivr.net/npm/@scalar/api-reference@1.25.13 has a problem.

https://cdn.jsdelivr.net/npm/@scalar/api-reference@1.25.11 is works.

### What did you expect to happen?

Add request header content-type like this.

<img width="686" alt="image" src="https://github.com/user-attachments/assets/993cdff5-c10a-40b7-b5d4-37f11ce99815">

### OpenAPI Document

https://sandbox.scalar.com/e/EM18V

**Comment by amritk** [comment]
Ah yes I removed the automatic content type header to allow users more control. Actually when sending something with a boundary (like a file) setting a header will actually break it and we were deleting it anyway.

**Comment by Ripwords** [comment]
I would also like to have the default back, instead of having to manually set the header during testing
