### ISSUE TITLE
In `@scalar/nestjs-api-reference`, `express` should be under `devDependencies` instead of `dependencies`

### ISSUE THREAD

**Issue by darekaze** [scalar/scalar#3159]
### What happens?

Hi, first of all thank you for this amazing project.

I was checking the npm of `@scalar/nestjs-api-reference` and I noticed that `express` is under the dependencies list. Then I went through the source code in the repo and check its usage, which turns out it's only used for type references similar to `fastify`.

As `fastify` is already in `devDependencies`, why not `express` as well?

### What did you expect to happen?

`express` should be listed under `devDependencies` instead of `dependencies`

**Comment by darekaze** [comment]
I can submit a PR for this

**Comment by hanspagel** [comment]
Yes, submit a PR! :)
