### ISSUE TITLE
Weird rendering on Arc Browser

### ISSUE THREAD

**Issue by alinalihassan** [scalar/scalar#3166]
### What happens?

I'm using Scalar with one of the support frameworks, [ElysiaJS](https://elysiajs.com/) and the API docs look weird on Arc Browser, which I didn't expect since it's based on Chromium. I've tested it with no extensions and it looks the same. No errors reported in the console.

<img width="1512" alt="Screenshot 2024-09-20 at 17 31 56" src="https://github.com/user-attachments/assets/a24eae3f-c387-40fa-92e4-190c35c4b43b">

### What did you expect to happen?

To see the normal looking API docs. The same page with Chrome looks like this. The main difference is the top left and bottom left.
<img width="1512" alt="Screenshot 2024-09-20 at 17 35 49" src="https://github.com/user-attachments/assets/b8223e82-8dc6-4f2d-b838-a48bde265cd5">

**Comment by elliotnash** [comment]
This seems to be introduced in 1.22.0, although I have only tested using @scalar/fastify-api-reference.

| @scalar/fastify-api-reference: 1.21.0  | @scalar/fastify-api-reference: 1.22.0 |
| ------------- | ------------- |
| ![Screenshot 2024-09-21 at 6 32 47 PM](https://github.com/user-attachments/assets/e7e3a477-e969-464f-8d74-c902d4468247) | ![Screenshot 2024-09-21 at 6 33 08 PM](https://github.com/user-attachments/assets/e71647c3-3421-428a-a5ff-31f36a0c609a) |

**Comment by NotReallyPrince** [comment]
![image](https://github.com/user-attachments/assets/d5969d0d-db9a-42a8-90f2-b8416872465e)


did you get any solution @alinalihassan in arc browser scalar is weird rendering 
docs web: https://api.kellyai.pro

**Comment by hanspagel** [comment]
Does that issue still exist? Sorry, I don’t have Arc and can’t test.

**Comment by antlio** [comment]
tested and it seems ok on my end, i'll close however @alinalihassan feel free to re-open it and ping me if you still encounter that issue
