### ISSUE TITLE
API Key Not Set When Pasting into Authorization Header Field

### ISSUE THREAD

**Issue by EvandroVV93** [scalar/scalar#3168]
### What happens?

When attempting to paste an API key into the default API key field for the authorization header, the value is not properly set. The only way to input the API key successfully is by typing it manually, letter by letter.

Steps to Reproduce:
Navigate to the default authorization header field.
Copy any text.
Paste the text into the field.
Observe that the value is not registered.
Now try typing the same text manually, letter by letter.
Observe that the text is sent in the request header.
![image](https://github.com/user-attachments/assets/62a16666-7cf0-4f52-92e1-e7041c00527d)
![image](https://github.com/user-attachments/assets/fcb92520-02f3-4f75-b596-0906189f592b)

### What did you expect to happen?

I expected the API key to be successfully set in the authorization header field when pasted, just as it is when typed manually, and for the API key to be recognized without any further issues.

**Comment by amritk** [comment]
Just wrapping up a feature then will tackle all of these after

**Comment by amritk** [comment]
hi @EvandroVV93 unfortunately I was unable to replicate this issue. Could you let me know what I'm missing?

[auth.webm](https://github.com/user-attachments/assets/3e7bf255-14f3-4865-ba66-e93ea340a3fa)

**Comment by wildsonc** [comment]
Now it only happens to me when I pass the token via settings `{ "api_key": {"token": ...} }`

https://github.com/user-attachments/assets/22414ef1-2efb-4472-9fee-ec52f57bceb9

**Comment by EvandroVV93** [comment]
@amritk I forgot to mention that this only happened when using the .NET package, when I used the cdn version it worked just fine!

**Comment by amritk** [comment]
@EvandroVV93 let me know if its still an issue after this next release in the next hour or so

**Comment by amritk** [comment]
@EvandroVV93 I believe we fixed this one the other day! Please re-open if its still an issue

**Comment by EvandroVV93** [comment]
> @EvandroVV93 I believe we fixed this one the other day! Please re-open if its still an issue

It's fixed!
Thank you so much!
