### ISSUE TITLE
Auth type selection is empty (Scalar.AspNetCore)

### ISSUE THREAD

**Issue by olegsavelos** [scalar/scalar#3179]
### What happens?

The auth type selection does not show any items.
![image](https://github.com/user-attachments/assets/edc86d41-5a52-46e5-bd4f-420021cffca0)
An error appears in browser debugger
![image](https://github.com/user-attachments/assets/85a80497-3b2c-4a46-a71e-5c3268fd1d8a)
![image](https://github.com/user-attachments/assets/9d844312-f07f-42e6-8160-3600bdd6e1d0)

Generated schema
[v1 (9).json](https://github.com/user-attachments/files/17083014/v1.9.json)

### What did you expect to happen?

Auth type selection present define methods.

**Comment by amritk** [comment]
Hi @olegsavelos which version were you on? We just fixed a similar bug earlier today, it should be in the latest version.

**Comment by marclave** [comment]
![image](https://github.com/user-attachments/assets/10c5c54a-2b4d-40d6-ad54-8dab5821b931)


purged :)

**Comment by olegsavelos** [comment]
@amritk 1.2.3 it seems :)

**Comment by amritk** [comment]
Give it another try!

**Comment by olegsavelos** [comment]
@amritk there is no new nuget packages published so far

**Comment by amritk** [comment]
Is it this one?

https://www.nuget.org/packages/AspNetCore.Scalar/1.1.6#supportedframeworks-body-tab

I'm seeing version 1.1.6 from 11 days ago

**Comment by olegsavelos** [comment]
@amritk this one https://www.nuget.org/packages/Scalar.AspNetCore, i think @marclave is maintainer :)
I have compiled from source and it seems that the bug is fixed so it only remains for @marclave to push new version to nuget.

**Comment by amritk** [comment]
Awesome thanks for checking @olegsavelos. @marclave it's all urs, can we automate the .net deployment?

**Comment by ZUOXIANGE** [comment]
bug is fixed? Scalar.AspNetCore 1.2.4 still has the same problem

**Comment by marcos930807** [comment]
1.2.9 still has the same problem.
