### ISSUE TITLE
UI is broken in `@scalar/hono-api-reference` on `v0.5.147`

### ISSUE THREAD

**Issue by omarkhatibco** [scalar/scalar#3182]
### What happens?

Hi, 
This has been reported on other packages as well and it seems it was fixed, but unfortunaly not in hono package I assume.

I tried to revert back to `v0.5.146` and `v0.5.146` but there were broken as well.

see the sidebar or tri to click test request, you should see a blank screen.

### What did you expect to happen?

the test request screen should work

**Comment by omarkhatibco** [comment]
a quick fix for now is to pin the scalar version to `1.25.11` 

```ts
app.get(
	'/swagger',
	apiReference({
		cdn: 'https://cdn.jsdelivr.net/npm/@scalar/api-reference@1.25.11',
		spec: {
			url: '/openapi.json',
		},
	}),
)

```

**Comment by NotReallyPrince** [comment]
![image](https://github.com/user-attachments/assets/f91685e3-fff6-4882-bcc9-d77e01fd8ddb)

**Comment by marclave** [comment]
hey @omarkhatibco @NotReallyPrince wouod you be able to share a link to your docs or your openapi spec? :) 

can also dm it to me marc@scalar.com

**Comment by omarkhatibco** [comment]
Hi @marclave,

Just sent you an email with the links, thanks for your help

**Comment by NotReallyPrince** [comment]
Hi @marclave,

Just sent you an email with the links, thanks for your help
