### ISSUE TITLE
form parameters are not added to the request

### ISSUE THREAD

**Issue by hanspagel** [scalar/scalar#3222]
Looks like form data parameters aren't added to the API client request.

> Note: Currently, form data parameters aren’t upgraded at all, I’ve tested it in #3219 and I’ve used https://petstore.swagger.io/v2/swagger.json but set the form data parameters to `required: true`.

**Required form data parameters**
<img width="1194" alt="Screenshot 2024-09-24 at 11 19 36" src="https://github.com/user-attachments/assets/5fa8b03b-5c46-4afe-89aa-4309a91ae0c7">

**Nothing appears in the API client**
<img width="692" alt="Screenshot 2024-09-24 at 11 19 42" src="https://github.com/user-attachments/assets/753c3b43-6b5c-450e-9849-f3c48a25541d">

**Comment by MrPranav101** [comment]
Would love a resolution of this issue :)
