### ISSUE TITLE
new workspaces don’t use the configured proxy

### ISSUE THREAD

**Issue by hanspagel** [scalar/scalar#3225]
The API client `./playground/app` doesn’t add the proxy for new workspaces. This is how we initialize it:

```ts
createApiClientApp(document.getElementById('scalar-client'), {
  proxyUrl: 'https://proxy.scalar.com',
})
```

And the default workspace has the proxy url, that’s fine. But new workspaces don’t:

```ts
activeWorkspace.value.proxyUrl
// undefined
```

**Comment by amritk** [comment]
Do we want to default the proxy to on?

**Comment by hanspagel** [comment]
I think that’s fixed already.
