### ISSUE TITLE
Multiple auth methods bug

### ISSUE THREAD

**Issue by Zaf97** [scalar/scalar#3231]
### What happens?

In my API doc, I have some endpoints that work with Basic authentication, while others work with Bearer token. Until now Scalar was giving me both options in the auth tab, but today it only gives me the bearer option. 

![Screenshot 2024-09-24 at 1 53 07 PM](https://github.com/user-attachments/assets/3d27b836-d685-421c-8347-d3618b1c75de)

The same openapi JSON seems to work fine in Swagger.
![Screenshot 2024-09-24 at 1 53 15 PM](https://github.com/user-attachments/assets/63a1fb3f-1bf2-4dc6-9f42-f647dbb5a35b)

I found this option at the beginning of the Scalar docs, but even when I am trying to select basic auth here, in the test request I am still getting only the bearer option.

![Screenshot 2024-09-24 at 1 59 22 PM](https://github.com/user-attachments/assets/aadfeab1-2e43-46fb-9537-88f810abd1c9)

### What did you expect to happen?

I would expect to be able to choose between bearer and basic auth in the faith tab of the test request.
Otherwise, I would expect to find either beare or basic (depending on what I chose in the beginning of the Scalar options, in the dark select menu of the attached screenshot) in the auth tab of the test request

**Comment by amritk** [comment]
Hey @Zaf97 could you please provide your spec if it is public? If not, a similar spec that would cause the same error?

**Comment by Zaf97** [comment]
Hi @amritk! Any specs with the following securitySchemes should raise the same issue.

`
"components": {
"securitySchemes": {
      "Bearer": {
        "type": "apiKey",
        "description": "JWT Authorization header using the Bearer scheme (Example: 'Bearer 12345abcdef')",
        "name": "Authorization",
        "in": "header"
      },
      "Basic": {
        "type": "http",
        "description": "Basic Authentication header using the Basic scheme (Example: 'Basic dGVzdDp0ZXN0MQ==')",
        "scheme": "Basic"
      }
    }
    }
`

**Comment by amritk** [comment]
Done and [done](https://github.com/scalar/scalar/pull/3232)
