### ISSUE TITLE
Renaming workspace doesn’t work

### ISSUE THREAD

**Issue by hanspagel** [scalar/scalar#3238]
I tried to rename my workspace but it doesn’t work. I put in a new name and click Save, but it doesn’t update the name.

https://client.scalar.com/

<img width="488" alt="Screenshot 2024-09-25 at 10 43 39" src="https://github.com/user-attachments/assets/d09ab26b-ca45-4504-8fef-7d43eb3aef42">

**Comment by Rahul-28** [comment]
hi @hanspagel, I would like to work on this can you assign this to me?

**Comment by hanspagel** [comment]
Awesome! 🤟

**Comment by Rahul-28** [comment]
@hanspagel  I've raised a PR, please review it

**Comment by Rahul-28** [comment]
looks like this issue has been solved by #3250

**Comment by hanspagel** [comment]
Yes! It is. :) Thanks to both of you!
