### ISSUE TITLE
Remove `@scalar/themes` from the dependencies of `@scalar/types`

### ISSUE THREAD

**Issue by inyourtime** [scalar/scalar#3241]
### What happens?

The `@scalar/types` package currently imports some types from the `@scalar/themes` package. To reduce dependencies, we need to remove the reliance on `@scalar/themes` by refactoring those types or just copy that type to `@scalar/types`.

### What did you expect to happen?

we will eliminate the `@scalar/themes` dependency from `@scalar/types`, making it more self-contained and reducing external package dependencies.

**Comment by hanspagel** [comment]
That’s a great suggestion! Would you submit a PR?

**Comment by inyourtime** [comment]
Sure, I will submit a PR for this.
