### ISSUE TITLE
Body not filling with example values

### ISSUE THREAD

**Issue by Nikkoro** [scalar/scalar#3242]
### What happens?

![image](https://github.com/user-attachments/assets/bedcd7e5-a52e-4c7a-be14-63de29e2ea8b)
Using `Scalar.AspNetCore@1.2.4`, for some reason example values are not being filled.

### What did you expect to happen?

![image](https://github.com/user-attachments/assets/702f9907-db90-494d-a048-467cfd719521)

This is how it looks at scalar editor, example values are properly filled.

**Comment by Nikkoro** [comment]
I checked few versions and last one that has this feature working is `1.25.11`.

Also I noticed that pressing Enter inside Body editor introduces weird behaviours, changing to other methods by itself.

**Comment by Nikkoro** [comment]
Any update on that?

**Comment by marclave** [comment]
hi @Nikkoro really sorry on the delay here, we will make this a priority this week!

**Comment by AZCodingAccount** [comment]
> hi @Nikkoro really sorry on the delay here, we will make this a priority this week!

is there any new progress?

**Comment by maximeozenne** [comment]
Hello, maybe @marclave has some news about this issue? I Have the same problem on my side.

Thanks for your work!

**Comment by antlio** [comment]
hey all thank you for reporting this, @Nikkoro does the issue remain? 

cc @maximeozenne @AZCodingAccount

**Comment by Nikkoro** [comment]
> hey all thank you for reporting this, @Nikkoro does the issue remain?
> 
> cc @maximeozenne @AZCodingAccount

Unfortunately I had to drop Scalar for now due to amount of small bugs like this and not supporting multiple OpenApi docuements, but a quick check indeed has shown me that it's working correctly now. This issue can be closed then, great job! 🙌.

I found another bug tho which you can track at -> #4206

**Comment by marclave** [comment]
hey @Nikkoro ! sorry to hear you had to drop scalar cause of our bugs!

hopefully once we get these fixed you can give us another try :) 

we have some good news! @cameronrohani and i are working on the header as we speak to support multiple specs! 

we will update the discussion  once we have made progress!

**Comment by Nikkoro** [comment]
Hey @marclave! Awesome news! I check in on the progress from time to time and I really believe you'll get there. Gotta trust the process 😎
