### ISSUE TITLE
Hitting 'Enter' in any input field resets the url path

### ISSUE THREAD

**Issue by Nikkoro** [scalar/scalar#3245]
### What happens?

Pressing Enter inside any input field, trims the url from 
`http://localhost:5000/scalar/api#tag/accesskey/DELETE/api/accesskey/{id}`
to `http://localhost:5000/scalar/api#tag/accesskey`

### What did you expect to happen?

Enter should send cursor to the beginning of the next line (new entry for key: values, new line inside body etc)

**Comment by dominicmallo** [comment]
Additionally, it seems this same "jumping" bug appears when selecting an "Auth Type" from the input field in the web client.

Steps to Reproduce:
1. Run Scalar example HTML posted under "Quickstart" here: https://github.com/scalar/scalar?tab=readme-ov-file#quickstart
2. Navigate to any authenticated request
3. Click "Test Request"
4. Select the "Auth Type" drop down
5. Notice the screen behind the web client "jumps" to the top

Attached is a video demonstrating this bug.

https://github.com/user-attachments/assets/d86af827-822d-4096-b276-11510990da04

**Comment by amritk** [comment]
Alright I found the issue, it was due to a bunch of global listeners. I will remove them all give me a few 🪓

**Comment by hwkr** [comment]
The background jumping issue seems to be a different cause, I have a fix here https://github.com/scalar/scalar/pull/3275
