### ISSUE TITLE
Get request adds content-type json header by default when using scalar from CDN.

### ISSUE THREAD

**Issue by josesoaresif** [scalar/scalar#3261]
### What happens?

When selfhosting using the CDN, and adding an endpoint with GET method, it adds header content-type of json by default, on the other hand, the same specification file displays without that header in the scalar online editor.
The image shared, is a print of selfhosted with CDN.
![image](https://github.com/user-attachments/assets/3e52a8a1-1267-4990-b75c-f60a6fd878e4)

### What did you expect to happen?

I would expect it to not set content-type by default just like scalar online editor.

**Comment by marclave** [comment]
hi @josesoaresif , this has been fixed in the latest release of Scalar :) 

check the CDN or https://client.scalar.com

**Comment by josesoaresif** [comment]
> hi @josesoaresif , this has been fixed in the latest release of Scalar :)
> 
> check the CDN or https://client.scalar.com

I have checked and indeed it is corrected, thank you.

**Comment by jonasfroeller** [comment]
I have this issue in `v1.25.58`. Everything worked fine in `1.17.16`.
