### ISSUE TITLE
“Import successful”, even if it’s not

### ISSUE THREAD

**Issue by hanspagel** [scalar/scalar#3263]
For https://client.scalar.com/: When I import the Stripe OpenAPI document it says Import successful, but there’s no collection added and no error in the console.

In the branch I’m working, maybe that’s outdated:

I tried to import the Stripe OpenAPI document and it worked, but after reload I’ve had a black screen and a console error.

https://github.com/stripe/openapi/blob/master/openapi/spec3.yaml

<img width="657" alt="Screenshot 2024-09-26 at 14 58 05" src="https://github.com/user-attachments/assets/f2e79b03-5b31-4789-870b-1db3f2beb971">

**Comment by amritk** [comment]
I loaded it with `https://raw.githubusercontent.com/stripe/openapi/refs/heads/master/openapi/spec3.yaml` and no issues. Is that the url you were using 😉

**Comment by hanspagel** [comment]
Yep! Recorded on client.scalar.com:

https://github.com/user-attachments/assets/93a40bf2-174d-4ace-955c-7a6a774419d9

**Comment by hanspagel** [comment]
Ah, it does work! But I can reproduce it with an invalid URL (missing the h):

`https://raw.githubusercontent.com/stripe/openapi/refs/heads/master/openapi/spec3.yaml`

It doesn’t work (which is expected), but the toast says `Import successful`.
