### ISSUE TITLE
preferredSecurityScheme Is Not Working

### ISSUE THREAD

**Issue by dominicmallo** [scalar/scalar#3264]
### What happens?

When attempting to configure Scalar to use any `preferredSecurityScheme`, the security schema is not chosen by default in the "Test Request" web client.

This results in the user needing to select a security schema from the available list before sending each-request.

Here is my code:
```html
<!doctype html>
<html>
  <head>
    <title>Scalar API Reference</title>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1" />
  </head>
  <body>
    <script
      id="api-reference"
      data-url="https://cdn.jsdelivr.net/npm/@scalar/galaxy/dist/latest.yaml"></script>

    <script>
      const configuration = {
        isEditable: false,
        authentication: {
          preferredSecurityScheme: "oauth2",
          oAuth2: {
            clientId: "test"
          }
        }
      };
      const apiReference = document.getElementById("api-reference");
      apiReference.dataset.configuration = JSON.stringify(configuration);
    </script>

    <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>
  </body>
</html>
```

### What did you expect to happen?

Setting `preferredSecurityScheme` with a value matching one of the `components.securitySchemes` keys (defined in the Open API YAML), should result in that security schema being selected by default in the "Test Request" web client.

### OpenAPI Document

https://cdn.jsdelivr.net/npm/@scalar/galaxy/dist/latest.yaml

**Comment by hanspagel** [comment]
True, great catch!
