### ISSUE TITLE
OAuth 2.0 Password (oauth2) Not Working

### ISSUE THREAD

**Issue by dominicmallo** [scalar/scalar#3268]
### What happens?

When authenticating with OAuth2 (Password) from the home panel, a console error is displayed after clicking "Authorize" & the network request to retrieve a token is not made.

```
TypeError: Cannot read properties of undefined (reading 'join')
    at standalone.js:17069:44
    at Xr.setup.e.value.zo.default.e.value.type.zo.default.zo.default.Xo.default.Wo.onClick.h.<computed>.h.<computed> (standalone.js:17062:9)
    at Wn (standalone.js:537:40)
    at Xn (standalone.js:538:40)
    at HTMLButtonElement.n (standalone.js:1276:53)
```

Likewise, after authenticating from a "Test Request" web client - there is no visual indicator in the home panel that the authentication was successful (i.e. showing the Access Token).

Here is the Open API YAML used to produce the error (using latest version 1.25.21)

```yaml
openapi: 3.1.0
info:
  title: Example
paths:
  /example:
    post:
      summary: Example Post
      responses:
        '204':
          description: No Content
      security:
        - oauth2: [ ]
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        password:
          scopes: {}
          tokenUrl: http://my-server
```

Screenshot of issue:
![scalar-bug-oauth2-console-error](https://github.com/user-attachments/assets/e78ec25e-f673-4d29-b4e3-517a30e80267)

Sandbox Editor: https://sandbox.scalar.com/p/AXv7r

### What did you expect to happen?

After providing an OAuth2 username & password, the login flow from the home panel should work as expected without console errors. Likewise, after authenticating from either the home panel or a "Test Request" web client - a visual indicator of authentication should be given in both places.

### OpenAPI Document

https://sandbox.scalar.com/files/ptO1_/openapi.yaml

**Comment by amritk** [comment]
I'm actually not sure we support password oauth in the reference. This should all work when you open the client though and do it there. 

@hanspagel is it about time to use the client auth in the references?

**Comment by hanspagel** [comment]
Sure, let’s do it!

**Comment by dominicmallo** [comment]
I think it would also be nice if there could be a loading animation after clicking "Authorize" for the OAuth 2 password widget. Currently, after clicking "Authorize" the screen sits idle while the network request is made.

**Comment by amritk** [comment]
Hello @dominicmallo this works in the test client so I will close this ticket in favor of this one where we move the test client auth out

https://github.com/scalar/scalar/issues/3686

You can track this here
