### ISSUE TITLE
Deleting env var braces causes extra rows to be added

### ISSUE THREAD

**Issue by amritk** [scalar/scalar#3272]
### What happens?

starting to add an env var with `{{` then deleting the braces causes extra rows to be added
![image](https://github.com/user-attachments/assets/b1d32f89-f1ef-45ae-935e-bb0ee1037a71)

### What did you expect to happen?

No extra rows

**Comment by antlio** [comment]
might be caused when environment variables are empty and throwing errors

**Comment by marclave** [comment]
@amritk @antlio fixed in latest client.scalar.com
