### ISSUE TITLE
Cross Site Scripting Issue in Scalar Client

### ISSUE THREAD

**Issue by dominicmallo** [scalar/scalar#3286]
### What happens?

From the Scalar Client (https://client.scalar.com/), making a request to a page that returns javascript causes the script to be executed on `client.scalar.com`. This is a security issue, because it could allow an attacker to exfiltrate data from the user's session.

![image](https://github.com/user-attachments/assets/ab24b48a-1052-4974-802c-acc070e7a46c)

### What did you expect to happen?

The Scalar Client should not permit executing scripts.

**Comment by hwkr** [comment]
So I looked into this a bit and it looks like (unfortunately) `blob:` urls aren't well isolated by the browser. It seems like for now it makes the most sense to disable our previews for XSS vulnerable MIME types until we can figure out a good way to isolate the blob data (cool proposal here https://github.com/shhnjk/Safe-Blob-URL).

**Comment by hwkr** [comment]
Alright, turns our `client.scalar.com` didn't have a `Content-Security-Policy` like the electron app does.

I opened a PR to add a CSP to `client.scalar.com` and to lock down our `Content-Security-Policy` for `blob:`s: #3289
