### ISSUE TITLE
"Hello World" Teleport

### ISSUE THREAD

**Issue by arkhvoid** [scalar/scalar#3292]
### What happens?

Previous commit accidentally pushed a test ui "Hello World". [RequestAuth.vue#L215-L219](https://github.com/scalar/scalar/blob/1b4656474109721937fde882af5d2d05987cafc6/packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuth.vue#L215-L219).

### What did you expect to happen?

should not display the test ui.

**Comment by marclave** [comment]
😅 haha nice catch, let's fix this
