### ISSUE TITLE
Configuration properties 'preferredSecurityScheme' and 'servers' are not working as expected

### ISSUE THREAD

**Issue by xC0dex** [scalar/scalar#3295]
### What happens?

Using the latest api reference `https://cdn.jsdelivr.net/npm/@scalar/api-reference` in the `Scalar.AspNetCore` package, I encountered that `preferredSecurityScheme` and `servers` properties are not working as expected.

**preferredSecurityScheme**
This bug was already reported #3264; however, it's not fixed on my end. Instead of preselecting the `ApiKey` scheme, its set to none.
![image](https://github.com/user-attachments/assets/9b64c310-671a-4d51-b125-bcde00748f7b)

**servers**
This property only sets the Base URL in the overview. But when you click the `Test Request` button, it ignores this property and uses the values from the OpenAPI document.

The overview:
![image](https://github.com/user-attachments/assets/693a0424-2db1-4d11-957d-cea72c39de0b)

The api client:
![image](https://github.com/user-attachments/assets/e8a3d0f9-aa18-407f-b800-95738e142d02)

### What did you expect to happen?

When using a custom CDN Url with version `1.25.10` `https://cdn.jsdelivr.net/npm/@scalar/api-reference@1.25.10` both properties start working again:

**preferredSecurityScheme**
![image](https://github.com/user-attachments/assets/1cd1f5d2-ca08-4f10-a7aa-cc4873910487)

**servers**
![image](https://github.com/user-attachments/assets/2222d895-3d1b-4d17-8603-e329f1ad0258)

### OpenAPI Document

```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "Scalar.AspNetCore.Playground | v1",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://localhost:7201"
    },
    {
      "url": "http://localhost:5056"
    }
  ],
  "paths": {
    "/weatherforecast": {
      "get": {
        "tags": [
          "Scalar.AspNetCore.Playground"
        ],
        "operationId": "GetWeatherForecast",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/WeatherForecast"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized - Access token is missing or invalid."
          }
        },
        "security": [
          {
            "ApiKey": []
          }
        ]
      }
    }
  },
  "components": {
    "schemas": {
      "WeatherForecast": {
        "required": [
          "date",
          "temperatureC",
          "summary"
        ],
        "type": "object",
        "properties": {
          "date": {
            "type": "string",
            "format": "date"
          },
          "temperatureC": {
            "type": "integer",
            "format": "int32"
          },
          "summary": {
            "type": "string",
            "nullable": true
          },
          "temperatureF": {
            "type": "integer",
            "format": "int32"
          }
        }
      }
    },
    "securitySchemes": {
      "ApiKey": {
        "type": "apiKey",
        "name": "X-Api-Key",
        "in": "header"
      }
    }
  },
  "tags": [
    {
      "name": "Scalar.AspNetCore.Playground"
    }
  ]
}
```

This bug is reproducible in the `Scalar.AspNetCore.Playground` project.

**Comment by xC0dex** [comment]
Update:

It looks like the `preferredSecurityScheme` property partially started working again. Now the scheme will be selected, but I experience the same issue as described in https://github.com/scalar/scalar/issues/3377.

**Comment by tnrich** [comment]
Also seeing the `servers` overrides not working. Are there no tests for that? I'm a little confused by how something like that can break..

**Comment by xC0dex** [comment]
Relates to https://github.com/scalar/scalar/issues/3476

**Comment by amritk** [comment]
@tnrich this is true we need a lot of tests for our store. I have a ticket open for it, will get to it after this auth stuff!

**Comment by tnrich** [comment]
Awesome thanks @amritk !
