### ISSUE TITLE
Too many models (200) freeze the reference

### ISSUE THREAD

**Issue by hanspagel** [scalar/scalar#330]
Showing all models (~200) for large specs freezes the reference.

~~We should probably lazy render the models when they become visible.~~

We should add virtual scroll.

**Comment by marclave** [comment]
yeah, looks like i spoke too soon saying we don't need virtualization just yet.

@amritk and I chatted and he's going to be adding virtualization

**Comment by hanspagel** [comment]
This looks great:
https://github.com/TanStack/virtual

**Comment by hanspagel** [comment]
Work in progress: #979

**Comment by hanspagel** [comment]
I think this is fixed with #979 :)
