### ISSUE TITLE
PATCH test request's method is `patch` (lower case)

### ISSUE THREAD

**Issue by yshrsmz** [scalar/scalar#3303]
### What happens?

When I send a PATCH test request from UI, its request method is `patch`(lower case), and that seems to cause bad request error in my environment. But when I send a GET test request, its method is `GET`(upper case).

### What did you expect to happen?

According to the Fetch API spec, the request method is actually case-sensitive, and we should use upper-cased `PATCH`.
https://fetch.spec.whatwg.org/#methods

### OpenAPI Document

https://sandbox.scalar.com/e/GcxDQ

**Comment by marclave** [comment]
youre absolutely correct @yshrsmz !

let me fix that

https://www.rfc-editor.org/rfc/rfc7231#section-4.1

**Comment by marclave** [comment]
@yshrsmz fix is here, just need the team to review and then can get released!

https://github.com/scalar/scalar/pull/3305/files
