### ISSUE TITLE
can't import basic openapi spec into api client app

### ISSUE THREAD

**Issue by marclave** [scalar/scalar#3304]
### What happens?

i import this string as a collection

```
{
  "openapi": "3.1.0",
  "info": {
    "title": "Hello World",
    "version": "1.0.0"
  },
  "paths": {
    "/test": {
      "patch": {},
      "get": {}
    }
  }
}
```

### What did you expect to happen?

see the PATCH request :) 

### OpenAPI Document

https://sandbox.scalar.com/e/GcxDQ

**Comment by hanspagel** [comment]
You’re doing this? 

<img width="672" alt="Screenshot 2024-09-30 at 15 10 22" src="https://github.com/user-attachments/assets/da48b19e-fdda-49a6-b41c-67ec1d04f3c2">

**Comment by antlio** [comment]
> You’re doing this?
> 
> <img alt="Screenshot 2024-09-30 at 15 10 22" width="672" src="https://private-user-images.githubusercontent.com/1577992/372097123-da48b19e-fdda-49a6-b41c-67ec1d04f3c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3MTE5NjgsIm5iZiI6MTcyNzcxMTY2OCwicGF0aCI6Ii8xNTc3OTkyLzM3MjA5NzEyMy1kYTQ4YjE5ZS1mZGRhLTQ5YTYtYjQxYy02N2VjMWQwNGYzYzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MzBUMTU1NDI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjA1MmM2YmJjMjVkMTM5ZjdmODgwMjk1NmNkYzQxY2Y2NzNmZGJmNjY1NGFhYzg1Y2NkOWMzNjAxZWFmNTEwNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.3T3usSxoDG5BFh1CwzBbxAfbe5GHwIdoi8rFvl7AXEA">

it is a bit confusing maybe we should support that as well (and enhance display when detected)

**Comment by marclave** [comment]
yeah @antlio we should defs format on paste :) great idea!
