### ISSUE TITLE
Auth Type select hidden behind box in `1.25.26`.

### ISSUE THREAD

**Issue by jonasfroeller** [scalar/scalar#3348]
### What happens?

![image](https://github.com/user-attachments/assets/f1918fc2-7902-4719-93e0-4084a685c9a6)

### What did you expect to happen?

Being able to select an auth type, if I click on the select.

**Comment by amritk** [comment]
Ah I don't think its hidden, I think it might be empty. Mind sharing the spec if its public, or a reproducible example spec?

also how should we handle empty dropdown @cameronrohani ?

**Comment by jonasfroeller** [comment]
@amritk Ah, okay. I think you could select all of them in the past, even if they were not in the openapi spec. I will have to look into this.

**Comment by amritk** [comment]
Yea I mean its still probably a bug that they aren't showing up!

**Comment by jonasfroeller** [comment]
@amritk I am not sure, how to define this.  
https://github.com/scalar/scalar/blob/main/documentation/configuration.md

I am using elysiajs. I put this in my `scalarConfig`:
```
authentication: {
    preferredSecurityScheme: "BearerAuth",
}
```

and this in `detail`, at the endpoint:
```
detail: {
    security: [
	    {
		    BearerAuth: []
	    }
    ]
},
```

But I still do not get any auth types in the ui.
I am going back to `1.17.16` for now, because I used that before and it worked fine.

**Comment by amritk** [comment]
Do you think you could give me an example spec that shows this bug? Then I should be able to fix it pretty handily!

**Comment by jonasfroeller** [comment]
@amritk 

```ts
import swagger from "@elysiajs/swagger";
import { Elysia } from "elysia";

const app = new Elysia()
  .use(
    swagger({
      scalarVersion: "1.25.26",
      path: "/api/docs",
      // doesn't generate anything in the openapi spec
      scalarConfig: {
        authentication: {
          preferredSecurityScheme: "BearerAuth",
        }
      },
    })
  )
  .get("/",
    () => {
      return "Hello Elysia"
    },
    {
      // removing this causes the select to be empty
      detail: {
        security: [
          {
            BearerAuth: []
          }
        ]
      }
    })
  .listen(3000);

console.log(
  `🦊 Elysia is running at ${app.server?.hostname}:${app.server?.port}`
);
```

```
{
openapi: "3.0.3",
info: {
title: "Elysia Documentation",
description: "Development documentation",
version: "0.0.0"
},
paths: {
/: {
get: {
operationId: "getIndex",
security: [
{
BearerAuth: [ ]
}
],
responses: {
200: { }
}
}
}
},
components: {
schemas: { }
}
}
```

Adding the security.BearerAuth property causes the auth tab to be completely empty. Not even a select is displayed in that case:
![image](https://github.com/user-attachments/assets/3d024e5b-a25c-4a9d-9557-10c62a44698d)

**Comment by amritk** [comment]
Ok yea so we need the securitySchemes in the components as well like this:
```json
"components": {
    "securitySchemes": {
      "BearerAuth": {
        "type": "http",
        "scheme": "bearer"
      },
    },
  }
```

check in the openapi generation in the elysia plugin maybe?

**Comment by jonasfroeller** [comment]
@amritk 

Where should I put it? Putting it here doesn't do much and above that throws a type error.

```
Object literal may only specify known properties, and 'components' does not exist in type 'ElysiaSwaggerConfig<"api">'.ts(2353)
```

```
scalarConfig: {
  components: {
	  securitySchemes: {
		  BearerAuth: {
			  type: "http",
			  scheme: "bearer"
		  },
	  },
  },
  authentication: {
	  preferredSecurityScheme: "BearerAuth",
  }
},
```

Result:
```
"components": {
  "schemas": {}
}
```

**Comment by amritk** [comment]
Alright I opened up a new ticket, you can follow it here!

https://github.com/elysiajs/elysia-swagger/issues/160

**Comment by amritk** [comment]
There should be a place to add it in elysia, I'm not quite sure where though

**Comment by cethink** [comment]
C# Bearer #4015
