### ISSUE TITLE
ASP .net ci failing in every PR

### ISSUE THREAD

**Issue by amritk** [scalar/scalar#3352]
### What happens?

This currently seems to be failing in every PR, should it also be moved in with the other tests?
![image](https://github.com/user-attachments/assets/c8409e5f-2875-4ddc-b16a-191b744119e7)

### What did you expect to happen?

The tests to pass

**Comment by hwkr** [comment]
Fixed here https://github.com/scalar/scalar/pull/3350

**Comment by hwkr** [comment]
This should be fixed now
