### ISSUE TITLE
Parameters for authorization request are sent as query string for OAuth2 password flow instead of x-www-form-urlencoded

### ISSUE THREAD

**Issue by a-haddaji** [scalar/scalar#3356]
### What happens?

password grant authorization always fail since all parameters are send as a query string instead of x-www-form-urlencoded

![image](https://github.com/user-attachments/assets/dadb49f4-a6a9-4e35-a2a9-949da50d3d5a)

![image](https://github.com/user-attachments/assets/9484a99e-be69-4d0e-bd25-f8f7f2a9a51f)

### What did you expect to happen?

looks like all the parameters for the token endpoint are added as query string this could be an issue since our identity server based on openiddict only expect x-www-form-urlencoded payload.

**Comment by amritk** [comment]
hmm strange looks like we are setting the headers
```ts
const headers: Record<string, string> = {
  'Content-Type': 'application/x-www-form-urlencoded',
}
```

I'll check it out

**Comment by a-haddaji** [comment]
> Oh! hey @a-haddaji are you trying this in the references? Care to try authorizing in the test client? We have different auth there

Yes i have tried with the test client and it seems to work but that is not consistent, in the references it uses query string while it should be the same as in the test client.

**Comment by amritk** [comment]
yes we are going to be moving it over soon! I will close this ticket and you can follow it here:
https://github.com/scalar/scalar/issues/3686

Cheers
