### ISSUE TITLE
Expand getting examples from requestbody

### ISSUE THREAD

**Issue by amritk** [scalar/scalar#3373]
### What happens?

~~Currently we only look at top level examples when generating a request body. HOWEVER schema properties can also have examples.~~

### ~~What did you expect to happen?~~

~~A spec like~~
```json
 "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "example": "Marc"
                  }
                },
                "required": [
                  "name"
                ]
              }
            }
          },
          "required": true
        },
```
~~should correctly add the name 'Marc' in the requestBody~~

Update: Turns out we do display it correctly if it comes in the correct format, unfortunately there is an issue with the upgrader. Maybe we should only upgrade if it is an older version. But also we should fix the upgrader.

It incorrectly changes 
```json
  "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "example": "Marc"
                  }
                },
                "required": [
                  "name"
                ]
              }
            }
          },
          "required": true
        },
```
to the deprecated:
```ts
    "requestBody": {
        "content": {
            "application/json": {
                "schema": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string",
                            "examples": {
                                "default": "Marc"
                            }
                        }
                    },
                    "required": [
                        "name"
                    ]
                }
            }
        },
        "required": true
    },
```

**Comment by amritk** [comment]
False alarm!

**Comment by amritk** [comment]
It was an example vs examples thing

**Comment by amritk** [comment]
I lied again, it is there, something is incorrectly converting it from example to examples

**Comment by amritk** [comment]
Ah it also seems to be happening in `dereference` as well, we should change this as its deprecated

>A free-form property to include an example of an instance for this schema. To represent examples that cannot be naturally represented in JSON or YAML, a string value can be used to contain the example with escaping where necessary.

>Deprecated: The example property has been deprecated in favor of the JSON Schema examples keyword. Use of example is discouraged, and later versions of this specification may remove it.

https://spec.openapis.org/oas/latest.html#fixed-fields-19

**Comment by hwkr** [comment]
I think the second one is correct isn't it because is should be `examples` (plural) not `example`?

```
    "requestBody": {
        "content": {
            "application/json": {
                "schema": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string",
                            "examples": {  // ← Plural so the good one
                                "default": "Marc"
                            }
                        }
                    },
                    "required": [
                        "name"
                    ]
                }
            }
        },
        "required": true
    },
```

**Comment by amritk** [comment]
Haha it's always up for interpretation. I thought it says examples is on the same level as schema. Also theres no default key

**Comment by hwkr** [comment]
Oh yes right it's in the wrong place

**Comment by hanspagel** [comment]
According to my research it’s valid to have an object, but more common to have an array (if it’s in a schema). Submitted a PR: #3411.
