### ISSUE TITLE
On 1.25.27, prefilled token no longer get passed to the "Test Request" dialog

### ISSUE THREAD

**Issue by lephuongbg** [scalar/scalar#3377]
### What happens?

Scalar allows setting a token in the `configuration` object to pre-fill the credentials for all API requests. For e.g

```javascript
var configuration =  {
   authentication: {
      http: {
            bearer: {token: getToken()},
            basic: {}
      },
   }
}
```

This seems to be broken on v1.25.27, where opening the "Test Request" dialog no longer shows the pre-filled token, or use the pre-filled token when making request. This still works for v1.25.0 at least.

This issue also seems to be related to this one: https://github.com/scalar/scalar/issues/3168.

### What did you expect to happen?

"Test Request" dialog should use pre-filled token from the configuration object.

**Comment by amritk** [comment]
Just wrapping up a feature then will tackle all of these after
