### ISSUE TITLE
When using hiddenClients: true, the endpoint uri is also hidden

### ISSUE THREAD

**Issue by markwinter** [scalar/scalar#3380]
### What happens?

Currently the http method + uri is part of the code snippet section, so when using the `hiddenClients: true` configuration option, it's not possible to see what uri should be used.

### What did you expect to happen?

The endpoint e.g. `POST /newresource` is still visible when using the `hiddenClients: true` configuration option. Perhaps it can be pulled out of the right section and added under the endpoint title/description

**Comment by hanspagel** [comment]
Oops, thanks for the report!
