### ISSUE TITLE
Theming stopped working in the React wrapper

### ISSUE THREAD

**Issue by jacando-hugo-aleixo** [scalar/scalar#3388]
### What happens?

After switching to the latest version 0.3.104 of @scalar/api-reference-react, themes stopped working. Switching between light and dark mode still works, but the custom background from themes like "kepler" don't apply anymore.

The last version that worked as expected was 0.3.19.

### What did you expect to happen?

I expected to get the same theme styling as per examples and documentation when applying it on the configuration.

### How can we reproduce the issue?

```javascript
'use client';
import React from 'react';
import { ApiReferenceReact } from '@scalar/api-reference-react';
import '@scalar/api-reference-react/style.css'

type Props = {
    spec: Record<string, any>;
};

const Docs = ({ spec }: Props): React.ReactElement => {
    return (
        <ApiReferenceReact
            configuration={{
                spec: {
                    content: spec
                },
                layout: 'modern',
                theme: 'kepler',
                hideDownloadButton: true,
                hideModels: true,
                darkMode: true,
            }}
        />
    );
};

export default Docs;
```

**Comment by jacando-timo-zimmermann** [comment]
This seems to be the same issue we had earlier: https://github.com/scalar/scalar/issues/2392

**Comment by antlio** [comment]
sorry about that, seems to be introduced by #3283, fixing now!

**Comment by jacando-hugo-aleixo** [comment]
Thanks for the quick solution and fast support. Keep up your great work!
