### ISSUE TITLE
Method 'GET' already declared for route '/reference/'

### ISSUE THREAD

**Issue by zbury** [scalar/scalar#3408]
### What happens?

I'm getting the following Fastify error with `@scalar/fastify-api-reference` versions `1.25.20` and above, if I downgrade to `1.25.19` the error goes away.

```
{
  code: "FST_ERR_DUPLICATED_ROUTE",
  name: "FastifyError",
  statusCode: 500,
  message: "Method 'GET' already declared for route '/reference/'"
}
```

I'm not doing anything particularly custom in my setup, I basically just followed the example here https://github.com/scalar/scalar/blob/main/examples/fastify-api-reference/src/index.ts

```ts
import swagger from '@fastify/swagger';
import apiReference from '@scalar/fastify-api-reference';

...

fastify.register(swagger, {
  hideUntagged: true,
  openapi: {
    openapi: '3.0.0',
    components: {
      securitySchemes: {
        bearerToken: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT'
        }
      }
    },
    security: [
      {
        bearerToken: []
      }
    ]
  }
});
fastify.register(apiReference, {
  routePrefix: '/reference'
});
```

### What did you expect to happen?

Expected to not get an error

**Comment by hanspagel** [comment]
Strange! I can only reproduce this, if I add another `fastify.get('/reference', …)`. Would you mind to double check you don’t have a route `/reference/` (with a trailing slash) already and don’t register the plugin twice? I’m lost here.

**Comment by zbury** [comment]
Interesting, looks like it only happens when instantiating Fastify with the [ignoreTrailingSlash](https://fastify.dev/docs/latest/Reference/Server/#ignoretrailingslash) option set to `true`.

**Comment by hanspagel** [comment]
Ah, makes sense! Will fix this!

**Comment by hanspagel** [comment]
Submitted a PR #3453
