### ISSUE TITLE
Configuration property `operationsSorter` not working as expected

### ISSUE THREAD

**Issue by lnans** [scalar/scalar#3466]
### What happens?

Using the latest api reference `https://cdn.jsdelivr.net/npm/@scalar/api-reference`.
I encountered an issue where the `operationsSorter` property of type function is not working as expected.

According to the documentation [Configuration](https://github.com/scalar/scalar/blob/main/documentation/configuration.md), it should be possible to pass a custom function to `operationsSorter`.

If i understand correclty, when using the CDN, i need to pass the configuration in the `<script>` tag like this:
```html
<body>
    <script
        id="api-reference"
        data-url="/openapi/v1.json"></script>
    <script>
      var configuration = {
        theme: 'purple',
        layout: 'modern',
        operationsSorter: (a, b) => {
            const methodOrder = ['GET', 'POST', 'PUT', 'DELETE']
            const methodComparison = methodOrder.indexOf(a.httpVerb) - methodOrder.indexOf(b.httpVerb)
        
            if (methodComparison !== 0) {
              return methodComparison
            }
        
            return a.path.localeCompare(b.path)
          },
      }
    
      document.getElementById('api-reference').dataset.configuration = JSON.stringify(configuration)
    </script>
    <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>
</body>
```

However a `function` cannot be stringified, and the custom `operationsSorter` does not work.
Am I missing something in the way I am trying to configure this?

### What did you expect to happen?

Have a way to pass custom functions in the configuration when using the CDN

**Comment by inyourtime** [comment]
Now, similar to `tagsSorter`, you can’t use custom sort functions that pass the configuration as a JSON string.

**Comment by hanspagel** [comment]
True! We need a different API. I think you could use our events to pass the configuration, but it’s not very intuitive.

**Comment by lnans** [comment]
Thank for the information :smiley:
Indeed, I hadn't seen the API reference [documentation](https://github.com/scalar/scalar/blob/main/packages/api-reference/README.md#scalarupdate-references-config).
It is tagged as `beta` but i've managed to get the function working with this: 
```html
<body>
  <script id="api-reference"></script>
  <script>
    document.addEventListener("DOMContentLoaded", function () {
      const ev = new CustomEvent("scalar:update-references-config", {
        detail: {
          configuration: {
            spec: {
              url: "/openapi/v1.json",
            },
            theme: "default",
            layout: "modern",
            operationsSorter: (a, b) => {
              const methodOrder = ["GET", "POST", "PUT", "DELETE"];
              const methodComparison =
                methodOrder.indexOf(a.httpVerb) -
                methodOrder.indexOf(b.httpVerb);

              if (methodComparison !== 0) {
                return methodComparison;
              }

              return a.path.localeCompare(b.path);
            },
          },
        },
      });
      document.dispatchEvent(ev);
      document.dispatchEvent(new Event("scalar:reload-references"));
    });
  </script>
  <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>
</body>
```
