### ISSUE TITLE
Random/Intermitment UI freezing happens when displaying large JSON responses

### ISSUE THREAD

**Issue by redstrike** [scalar/scalar#3467]
### What happens?

**Version:** 1.25.34

Noticable random and long freezing When testing any API endpoint that returns large JSON responses (~ 24 KiB download size).
It costs at least 3 seconds to display a response with 46 ms (round trip time).
Then, every UI components seems freezing, even hovering states are not displaying correctly.
After a few extra seconds, I can start scrolling the response view, but it may or may not scroll properly.
Using the small scrollbar for quickly navigating is completely broken, it has been frozen.
The UI may be unfrozen after a while or not, even on a very beefy workstation with 64 GiB RAM and a lot of processing cores.

### What did you expect to happen?

I think we should disable syntax highlighting for large JSON responses (similar to VS Code behaviors when opening very big files).
I see this kind of issues had been addressed, but not sure why Scalar UI cannot handle ~ 24 KiB of JSON responses without freezing.

https://github.com/scalar/scalar/issues/2503
https://github.com/scalar/scalar/issues/2333

**Comment by hanspagel** [comment]
We probably need to at least tweak the limit that we use to disable the syntax highlighting. 🤔

**Comment by amritk** [comment]
Yep let's lower the threshold, it was just a random number. Let's check how many characters this response is

**Comment by redstrike** [comment]
VS Code is using a threshold of 20k characters for **editor.maxTokenizationLineLength** setting.

![Editor - Max Tokenization Line Length](https://github.com/user-attachments/assets/3484076d-c52b-4666-bd38-9e335236bd81)

However, I think we should lower this max threshold to 15k characters (more conservative) until more optimizations can be applied.

Besides, I am not sure if we can prettify the response without freezing the UI or not?

**Comment by amritk** [comment]
Oh wow ours was set to 5 million. That makes sense
