### ISSUE TITLE
Too many preview apps are launching during PRs

### ISSUE THREAD

**Issue by amritk** [scalar/scalar#3468]
### What happens?

Seems like a new preview launches every time you make a change and the old ones are still up. This must be incurring some extra server costs. We should either: update/replace the initial preview OR take down the old one before launching a new one. That way there's only one currently running per PR

### What did you expect to happen?

Only one instance to be active at a time

**Comment by hanspagel** [comment]
Ah, I updated the PR comment action, that broke it.
