### ISSUE TITLE
API client ignores servers and baseServerURL

### ISSUE THREAD

**Issue by hanspagel** [scalar/scalar#3476]
### Discussed in https://github.com/scalar/scalar/discussions/3475

<div type='discussions-op-text'>

<sup>Originally posted by **crukundo** October 14, 2024</sup>
Hello, Here's my sample config:

"@scalar/api-reference": "^1.24.8",
"@scalar/api-reference-react": "^0.3.6",

const config: ReferenceConfiguration = {
  theme: "none",
  layout: "modern",
  baseServerURL: "https://sandbox.api.sample",
  spec: {
    url: "https://sandbox.api.sample/docs/openapi.json",
  },
  hideModels: false,
  servers: [
    { url: "https://sandbox.api.sample", description: "Sandbox API" },
    { url: "https://api.splice.sample", description: "Production API" },
  ],
};

What's confusing me is every time you try to use the Test Request client, it uses the current base domain where I'm hosting my api reference: docs.sample.com so all my requests are going through `docs.sample.com` for example: `/health_check` get endpoint will use `docs.sample.com/health_check` rather than say  `sandbox.api.sample/health_check` or one of the Server URLS I specified. I tried to use `baseServerURL` but that doesn't do it either. 

Is there anything I'm doing wrong? Please advise. </div>

**Comment by crukundo** [comment]
Hi team - checking in on this issue as it directly affects the docs we use to onboard new users. Is there any additional info needed from our side, or any way we can help move this forward?

I appreciate all the work you do. Thank you!

**Comment by amritk** [comment]
might need @hanspagel help on this one. Just adding servers looks to do something strange
![image](https://github.com/user-attachments/assets/c811d29a-60cc-4eb8-a8f3-a878dcaf32b7)

**Comment by amritk** [comment]
It's just waiting on a review, the PR is up
