### ISSUE TITLE
wrong examples for allOf in arrays

### ISSUE THREAD

**Issue by keenjus** [scalar/scalar#3510]
### What happens?

Currently AllOf schemas get listed as separate array items in the request body example.

Similar existing issue (fixed) but for responses https://github.com/scalar/scalar/issues/2137

![image](https://github.com/user-attachments/assets/bc6602d0-28c1-4754-b151-81364863a0d4)

### What did you expect to happen?

AllOf schema properties are combined in request body examples for arrays

### OpenAPI Document

https://sandbox.scalar.com/e/44Rod

**Comment by hanspagel** [comment]
Fixed in #3655
