### ISSUE TITLE
Use environment variables in auth

### ISSUE THREAD

**Issue by Flo4604** [scalar/scalar#3513]
### What happens?

I have a token set in dev/prod environments it only gets replaced if I use it in the header but not authentication input 

![44072](https://github.com/user-attachments/assets/486b59d0-4d6f-424b-ac98-e96a71f40d9d)
![97012](https://github.com/user-attachments/assets/fa3ec5c9-95c1-4faa-b095-770947ee8194)
![37761](https://github.com/user-attachments/assets/6c28fbcf-76ad-4329-b4b3-8c18aca4ae13)

### What did you expect to happen?

To be able to use the environment variables there too.

**Comment by marclave** [comment]
work in progress! https://github.com/scalar/scalar/pull/3552
