### ISSUE TITLE
example request isn’t used for the request body

### ISSUE THREAD

**Issue by bpreston-asti** [scalar/scalar#3545]
### What happens?

When attempting to test a request, the JSON request body is not pre-populated with anything other than an empty body.
![image](https://github.com/user-attachments/assets/52562878-0a5c-4bc3-a739-9eb80c843eb4)

### What did you expect to happen?

I would expect the same outcome as the old Swagger UI that pre-populates the request body like so (below is the same endpoint as above):
![image](https://github.com/user-attachments/assets/7e33f682-5952-4603-a9f8-5dd78b494087)

What do I need to configure using Scalar to achieve the same outcome?

**Comment by JamesLawton** [comment]
Receiving the same issue on the react component

**Comment by antlio** [comment]
hey @bpreston-asti, sorry about that! do you happen to have a document that i could use to replicate this, or do you mind adding an equivalent here: https://sandbox.scalar.com/

**Comment by xC0dex** [comment]
Here is an MRE of the OpenAPI document from the `Scalar.AspNetCore` playground, generated by .NET's built-in OpenAPI document generator.

```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "Scalar.AspNetCore.Playground | v1",
    "version": "1.0.0"
  },
  "paths": {
    "/books": {
      "post": {
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Book"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Book"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Book": {
        "required": [
          "title",
          "pages"
        ],
        "type": "object",
        "properties": {
          "bookId": {
            "type": "string",
            "format": "uuid"
          },
          "title": {
            "type": "string"
          },
          "description": {
            "type": "string",
            "nullable": true
          },
          "pages": {
            "type": "integer",
            "format": "int32"
          }
        }
      }
    }
  }
}
```

It seems like only the `required` properties are shown in the request body. The prefilled request body looks like this:

```json
{
  "title": "",
  "pages": 1
}
```

However, I would expect something like this:

```json
{
  "bookId": "123e4567-e89b-12d3-a456-426614174000",
  "title": "",
  "description": "",
  "pages": 1
}
```

I'm not sure if this behavior should be configurable or what the default value for a string should be.

**Comment by amranmo1** [comment]
can we have scalar to add custom attribute to allow this visible in the example? making the field 'Required' just to make it visible in the test request is breaking with the functionality

**Comment by bpreston-asti** [comment]
> hey @bpreston-asti, sorry about that! do you happen to have a document that i could use to replicate this, or do you mind adding an equivalent here and click share: https://sandbox.scalar.com/

So sorry @antlio, I did not see your reply. The example @xC0dex posted should work. As they mentioned, making a property required does indeed make it prefilled in the test request body, but so far that is the only way I can make it happen. If it could be an optional thing to be able to configure scalar to have all the request properties display in the test request body like Swagger UI does that would be awesome.

**Comment by devjuanca** [comment]
Same issue here. Only required properties are shown in the "Test Request" body section.

This could be an issue in large request bodies with many properties and some of them optionals.

**Comment by antlio** [comment]
thank you all for all the feedbacks, we do only display either properties with an example or if required, however having them all when testing makes total sense.

i opened a first pr proposal in that regard, as a first stepping stone. will wait here for @hanspagel feedback
