### ISSUE TITLE
[DOC-1242] Mapping from OpenAPI Models -> Response/Request payloads

### ISSUE THREAD

**Issue by marclave** [scalar/scalar#356]
### Expected Behavior

Currently there's no way to tell if a request/body is being mapped from an OpenAPI/Swagger model. We might want to have _some_ indicator to if/what is being mapped. Maybe a chip/pill that links to the model?

```
OpenAPI models are listed, but there is no visible mapping between request's payload and response to them (request shows copy of the model, response shows only example/generated-example )
```

### Actual Behavior

No mapping to openapi models from request/responses

### Reproduction steps

```bash
load a swagger spec :) and you can see the lack of mapping✨
```

### Version

latest

<sub>[DOC-1242](https://linear.app/api-docs/issue/DOC-1242/mapping-fropm-openapi-models-responserequest-payloads)</sub>

**Comment by hanspagel** [comment]
You mean a distinction between a given example and a generated example?

**Comment by marcklingen** [comment]
@marclave I recently started using Scalar for my project. It would be helpful to have models describe the API return types alongside example responses. Our models are complex, and providing descriptions/types would enhance user understanding.

Example from redoc
![CleanShot 2023-12-24 at 13 09 23@2x](https://github.com/scalar/scalar/assets/2834609/049343d4-13a6-4db9-b6a5-9b4f4d976687)

**Comment by marclave** [comment]
ah wicked @marcklingen , langfuse is great !

This is fantastic feedback, will look into this. We did have plans to do this earlier but got lost, will bring this up with @hanspagel and get it going in the new year ✨

**Comment by marcklingen** [comment]
In case it's helpful, here are our previews of scalar and redoc

Scalar: https://langfuse-docs-git-new-api-ref-langfuse.vercel.app/docs/api-reference

Redoc: https://langfuse.com/docs/api-reference

**Comment by marcklingen** [comment]
Thanks for looking into this

**Comment by hanspagel** [comment]
The schema is added to the reference now. :) #783

**Comment by kylemclaren** [comment]
@hanspagel This is awesome, though only seems to wrk for OpenAPI 3.0 and not Swagger 2.0?
