### ISSUE TITLE
Scalar_proxy_url is set to null by default and has no effect.

### ISSUE THREAD

**Issue by aoaostar** [scalar/scalar#3563]
### What happens?

I didn't set scalar_proxy_url, and it's default value was empty, but it still used scalar_proxy_url provided by you, which made my intranet service inaccessible.

![image](https://github.com/user-attachments/assets/f8f68170-4ebd-4b62-8463-312a3b3f109c)
![image](https://github.com/user-attachments/assets/63db6056-1ae7-4182-92c3-ec990698fe80)
![image](https://github.com/user-attachments/assets/f1913541-6fa9-473a-bd5e-decf97780d68)
![image](https://github.com/user-attachments/assets/0ff45370-fed0-4183-81ed-54f153599474)

### What did you expect to happen?

I need to access my api interface directly, not through your agent.

**Comment by dzkfzn** [comment]
I experiencing the same, bump it up

**Comment by arnis** [comment]
Same here. For now I switched to `@scalar/api-reference@1.25.40` to resolve the issue.
Seems like it started with #3528.

**Comment by antlio** [comment]
thanks for the feedback sorry about that! fix is currently ongoing cc @hanspagel

**Comment by marclave** [comment]
hi @arnis @aoaostar @dzkfzn , this is fixed in latest Scalar release ✨

**Comment by arnis** [comment]
Works for me with latest version (`@scalar/api-reference@1.25.47`).
Cheers guys! :+1:

**Comment by aoaostar** [comment]
> Works for me with latest version (`@scalar/api-reference@1.25.47`).适用于我的最新版本（ `@scalar/api-reference@1.25.47` ）。 Cheers guys! 👍 干杯伙计们！ 👍
👍👍👍
