### ISSUE TITLE
[DOC-1244] Command + K doesn't work for me (CDN version)

### ISSUE THREAD

**Issue by marclave** [scalar/scalar#358]
### Expected Behavior

Search should appear when CMD+K hotkey is engaged

### Actual Behavior

Command + K doesn't work for me (CDN version)

### Reproduction steps

```bash
load swagger in cdn version
hit CMD+K

or CNTRL+K
```

### Version

latest cdn

<sub>[DOC-1244](https://linear.app/api-docs/issue/DOC-1244/command-k-doesnt-work-for-me-cdn-version)</sub>

**Comment by marclave** [comment]
Chatting with the user who reported it, trying to recreate it but I can't seem to.

<img width="1507" alt="image" src="https://github.com/scalar/scalar/assets/6176314/9ce3b490-4f81-449f-abcf-a92b070788e1">

**Comment by hanspagel** [comment]
It’s not always … 😵‍💫

**Comment by marclave** [comment]
@hanspagel ah okay, seems like we got a tough bug to chase down 🕵️‍♀️

**Comment by hanspagel** [comment]
I think this is fixed, probably with this PR: #545
