### ISSUE TITLE
[dotnet][Swagger] Custom Request Headers don´t show up

### ISSUE THREAD

**Issue by mkalinski93** [scalar/scalar#3600]
### What happens?

I´ve created an OperationFilter (Header) that I want to include in my requests.

```csharp
public class AtlasCultureHeaderParameter : IOperationFilter
{
    public void Apply(OpenApiOperation operation, OperationFilterContext context)
    {
        operation.Parameters ??= new List<OpenApiParameter>();
        operation.Parameters.Add(new OpenApiParameter
        {
            Name = AtlasHttpHeader.Culture.Value,
            In = ParameterLocation.Header,
            Description = "Specifies the requested Culture",
            Required = true,
            Schema = new OpenApiSchema
            {
                Type = "string",
                Default = new OpenApiString(AtlasHttpHeader.FallbackCulture),
            }
        });
    }
}
```

In the SwaggerUI - the custom header will be requested everytime - although there´s a default value next to it.
![image](https://github.com/user-attachments/assets/5f0ae950-5bd1-45fb-adb1-caacf36fb90c)

In Scalar, I can see the headers
![image](https://github.com/user-attachments/assets/ef012f4e-5df4-4a95-ad88-2943dc393793)

But in the submit popup, they´re not being put in automatically. No default value, I have to manually add them.
![image](https://github.com/user-attachments/assets/f058c56f-6c61-4714-86f7-02a10e255b99)

How can I insert the custom headers in the popup?

### What did you expect to happen?

I expected to have the custom request headers being put into the request automatically.

**Comment by xC0dex** [comment]
I agree, the header fields in general are not shown in the API Client, but they are correctly displayed in the reference.

**Comment by amritk** [comment]
Hello we recently had a fix for headers, could you try again?

**Comment by xC0dex** [comment]
@amritk It's fixed on my end 🥳. I wasn't able to reproduce it anymore.

**Comment by mkalinski93** [comment]
Fixed on my end, as well 🥳 thank you
