### ISSUE TITLE
Content-type header missing when using the API Client without a proxy

### ISSUE THREAD

**Issue by hanspagel** [scalar/scalar#361]
When sending requests without a proxy, the content-type header seems to be missing.

Example spec: https://github.com/FotieMConstant/lanadoc/blob/main/public/resource/openapi-spec-sample.yaml

Screenshot: https://user-images.githubusercontent.com/42372656/277362781-ae63be4f-032f-43e7-8eba-b29549e0d507.png

Further context: https://github.com/scalar/scalar/discussions/351

**Comment by FotieMConstant** [comment]
This issue seems to have been fixed as of **^0.8.2** for some reason.

**Comment by hanspagel** [comment]
It’s fixed, and I’ve added a test and improved the `sendRequest` method in #384. :v:
