### ISSUE TITLE
Add .NET instructions under documentation/integrations

### ISSUE THREAD

**Issue by captainsafia** [scalar/scalar#3617]
### What happens?

Currently, the [documentation/integrations directory](https://github.com/scalar/scalar/tree/4cf8c529a48794b1f77140c888da347b2e1cb2da/documentation/integrations) doesn't contain docs for the .NET integration. We should copy them over here.

### What did you expect to happen?

I would expect to see a `dotnet.md` file with instructions on how to use Scalar's `Scalar.AspNetCore` NuGet package.

**Comment by xC0dex** [comment]
This sounds like the perfect task for me to tackle over the weekend! 👀 I'll write some nice docs with some examples.

**Comment by captainsafia** [comment]
@xC0dex Sounds good! Happy to chime in with a review once you get a PR out if you'd like.
