### ISSUE TITLE
Error parsing OpenAPI spec in version 1.25

### ISSUE THREAD

**Issue by Star3Lord** [scalar/scalar#3624]
### What happens?

When I click `Test Request` button, the dialog that opens is blank. Inspecting the page using browser dev tools shows the errors logged as follows:
```
standalone.js:17246 Error: INVALID SCHEMA FOR OAUTH EXAMPLE
    at oK (standalone.js:16996:7)
    at standalone.js:17237:9
    at Array.reduce (<anonymous>)
    at mJ (standalone.js:17236:63)
    at async l (standalone.js:17406:61)
    at async importSpecFromUrl (standalone.js:17418:30)
    at async standalone.js:17602:29
    at async init (standalone.js:17599:7)
    at async standalone.js:17611:29
```
Weirdly this happens with version 1.25 only. I tried version 1.24 and that works.

### What did you expect to happen?

No errors, and, dialog has headers and body params to test the request.

### OpenAPI Document

https://sandbox.scalar.com/e/u8Uaa

**Comment by amritk** [comment]
Alright we are not handling OpenIdConnect very well. 

Made [one PR](https://github.com/scalar/scalar/pull/3658) to prevent everything from breaking.

Added [one issue](https://github.com/scalar/scalar/issues/3656) to add OpenID Connect support
