### ISSUE TITLE
CodeInput is always unmasked

### ISSUE THREAD

**Issue by leonlarsson** [scalar/scalar#3630]
### What happens?

Currently, the button to toggle password masking does not work. The input stays unmasked.
![2024-10-25_17-13-19](https://github.com/user-attachments/assets/21744ae9-940b-4e92-8685-e4bc2c117547)

### What did you expect to happen?

I expect the mask toggle button to work

**Comment by antlio** [comment]
hey @leonlarsson great catch! sorry about that i believe it's been introduced in #3552
