### ISSUE TITLE
@scalar/import doesn’t use a proxy

### ISSUE THREAD

**Issue by hanspagel** [scalar/scalar#3657]
The import package doesn’t use a proxy (yet), which could lead to issues with resolving URLs.

Example: https://api-docs.printeers.com/reference
Client Import: https://client.scalar.com/workspace/default/request/default?url=https://api-docs.printeers.com/reference

**Comment by gtolarc** [comment]
After updating to the latest version, I encountered an error where the openapi.json file is not being read properly. Could this issue be related to the update?
<img width="1496" alt="스크린샷 2024-10-29 12 49 23" src="https://github.com/user-attachments/assets/af950898-93d1-4bec-90a0-417cf8d049b6">

**Comment by hanspagel** [comment]
Yes! We rolled back the change, so it should be gone. Working on a proper fix now.

**Comment by hanspagel** [comment]
Fixed in #3694
