### ISSUE TITLE
[package: @scalar/api-reference] In my example query parameter "locale_id" (Enum with integer values) not shown on the page "Test Request".

### ISSUE THREAD

**Issue by alexxbar** [scalar/scalar#3681]
### What happens?

[package: @scalar/api-reference@1.25.52]
In my example query parameter "locale_id" (Enum with integer values) not shown on the page "Test Request".
[openapi.json](https://github.com/user-attachments/files/17566922/openapi.json)

Visible in docs:
![visible_in_docs](https://github.com/user-attachments/assets/e502c565-eeb2-47e5-a871-c618a0f57170)

Invisible on the page "Test Request" 
![invisible_in_test_request](https://github.com/user-attachments/assets/3d1cd56b-67e4-49de-bc1f-7f6ae6ae1d9a)

### What did you expect to happen?

I expected to see in the "Test Request" query parameter "locale_id" like it was in @scalar/api-reference@1.22.43
![example](https://github.com/user-attachments/assets/115e157c-bac1-43ea-b177-8321aeacffcd)

### OpenAPI Document

https://sandbox.scalar.com/e/8V5Hx

**Comment by inyourtime** [comment]
It looks like I missed something in #3666, so I will create a PR to parse the parameter enum for integer and boolean types as well.

**Comment by alexxbar** [comment]
It still doesn't work for me in the current version api-reference@1.25.54
And here too: https://sandbox.scalar.com/e/8V5Hx

**Comment by inyourtime** [comment]
It was released in api-reference@1.25.55 (#3692). Could you recheck it? @alexxbar

**Comment by alexxbar** [comment]
> It was released in api-reference@1.25.55 (#3692). Could you recheck it? @alexxbar

Yes. It works on 1.25.55: https://cdn.jsdelivr.net/npm/@scalar/api-reference
But sometimes for some reason the old version (1.25.54) is downloaded.

Thank you!
