### ISSUE TITLE
`hiddenClients` list still shows parent language even when all clients are hidden

### ISSUE THREAD

**Issue by sanscontext** [scalar/scalar#3688]
### What happens?

Currently [working around a bug with hiding all autogen'd clients](https://github.com/scalar/scalar/issues/3689), and overriding and hiding each language individually.
With this config:
```
"hiddenClients":["libcurl", "clojure", "clj_http", "httpclient", "restsharp", "native", "http1.1", "asynchttp", "nethttp", "okhttp", "unirest", "xhr", "axios", "fetch", "jquery", "okhttp", "undici", "native", "request", "axios", "fetch", "nsurlsession", "cohttp", "curl", "guzzle", "http1", "http2", "webrequest", "restmethod", "python3", "requests", "httr", "native", "curl", "httpie", "wget", "nsurlsession"]
```

It renders the list including the parent language items, even if there's no snippet for this.
![image](https://github.com/user-attachments/assets/5a75be20-4229-4d96-9cf5-6ad19725c3df)

### What did you expect to happen?

I would expect not to see the empty top-level category in the drop down menu.

### OpenAPI Document

https://developer.nylas.com/_spec-files/v3-ecc.yaml

**Comment by hwkr** [comment]
Hi @sanscontext! It shouldn't be doing that 😅 I'll have a look asap!
