### ISSUE TITLE
wrong parameter values

### ISSUE THREAD

**Issue by alexxbar** [scalar/scalar#3734]
### What happens?

Test case:
1. Chose endpoint "Get user list​" and open page "Test Request"
![1](https://github.com/user-attachments/assets/e8a10f9e-2295-4efd-98ff-fdf728d55393)

2. Chose endpoint "Get user info​​" and open page "Test Request".
Error! Param "locale_id" has invalid value "User"
![2](https://github.com/user-attachments/assets/83f2fa0c-4c68-44be-aac2-3b46ee440490)

3. Check possible values for param "locale_id"
![3](https://github.com/user-attachments/assets/80f4bf99-771e-4154-bb40-75c8c3f7b851)

### What did you expect to happen?

I expected to see valid values for param "locale_id"
![4](https://github.com/user-attachments/assets/ff0e0aed-5589-4422-929e-40a35ad6b919)

### OpenAPI Document

https://sandbox.scalar.com/e/KK4AY

**Comment by antlio** [comment]
great catch, it seems like the value displayed here is the selected one from the previous endpoint. digging!

**Comment by alexxbar** [comment]
Not working on current version api-reference@1.25.58

**Comment by antlio** [comment]
hey @alexxbar, this hasn't been released yet see #3781 - but will be part of the next batch!

**Comment by alexxbar** [comment]
> hey @alexxbar, this hasn't been released yet see #3781 - but will be part of the next batch!

Works great! Thank you!
