### ISSUE TITLE
Support Next 15

### ISSUE THREAD

**Issue by codenomnom** [scalar/scalar#3742]
### What happens?

Hi there,
I've migrated to the latest Next 15, but `@scalar/nextjs-api-reference@0.4.98` is giving me headaches because of `next@"^14.0.0"` dependency. Can we check if Scalar is compatible with Next 15 and provide an `or` dependency so we don't block usage?

Thanks!

p.s.
I'm not sure if this issue is constrained to `@scalar/nextjs-api-reference` solely.

### What did you expect to happen?

Be able to install project dependencies without any hassle (i.e. `--legacy-peer-deps`).

**Comment by amritk** [comment]
Hey I actually had a branch going for this, but its on pause for now. Will get back and wrap it up after auth. It also added proper SSR

**Comment by bensmith2093** [comment]
Hi @amritk, also interested in this request, do you have a high-level timeline for this going in?

Thanks!

**Comment by amritk** [comment]
@bensmith2093 nothing exact, all I can tell you is currently I'm plowing through this list

https://github.com/scalar/scalar/issues/3696

**Comment by codenomnom** [comment]
@amritk would it be possible to at least make the dependency 14 _or_ 15? I hate to have Scalar being the only dependency in my list that requires `--legacy-peer-deps`. Do you think that would hurt further work? I'm fully aware Scalar wasn't tested with Next 15, so things might break, but that doesn't bother me that much.

**Comment by amritk** [comment]
@codenomnom going to do it now actually!

**Comment by codenomnom** [comment]
Thanks, @amritk! Happy holidays! 🎈
