### ISSUE TITLE
When I try to select the Body type in the Test Request, the scroll position goes back to the first API.

### ISSUE THREAD

**Issue by uyrabi** [scalar/scalar#3796]
### What happens?

This issue was confirmed by
1. when building API references with a CDN
2. for example, API reference of Supabase

This did not occur in the official demo.
https://docs.scalar.com/swagger-editor#description/resources

As shown in the video, when I open the test request window and try to change the request body type, I am forced to scroll to the API position at the beginning.

https://github.com/user-attachments/assets/5767d3a8-7218-458b-94d1-c72ba53ea52f

### What did you expect to happen?

Remain in the current scroll position.

**Comment by antlio** [comment]
thank for you reporting this @uyrabi, issue should be fixed by now but feel free to jump back in if you still encounter it!
