### ISSUE TITLE
if requestBody is set to examples, content-type is missing in the code example.

### ISSUE THREAD

**Issue by uyrabi** [scalar/scalar#3809]
### What happens?

As the title says, it occurs in both curl and non-curl.

```sh:
## with examples

curl --request POST \
  --url https://sandbox.scalar.com/withExample \
  --data '{
  "email": "hoge@example.com",
  "password": "hogehoge"
}'
```

```sh:
## without examples

curl --request POST \
  --url https://sandbox.scalar.com/withOutExample \
  --header 'Content-Type: application/json' \
  --data '{
  "email": "marc@scalar.com",
  "password": "i-love-scalar"
}'
```

### What did you expect to happen?

It is correct that Content-type: application/json; is set in the request header

### OpenAPI Document

https://sandbox.scalar.com/e/ZM3A8

**Comment by antlio** [comment]
hey @uyrabi, does that issue is still remaining? 

<img width="491" alt="image" src="https://github.com/user-attachments/assets/f4c811fd-e8bd-44f3-b24f-5466937c6283" />

**Comment by uyrabi** [comment]
Hi @antlio 
I think it has been resolved. Thank you for your response.
