### ISSUE TITLE
cannot download after request api with file pdf on .net core 8 

### ISSUE THREAD

**Issue by Kimloang** [scalar/scalar#3850]
### What happens?

![Screenshot 2024-11-11 194020](https://github.com/user-attachments/assets/22ade09c-a030-41e3-8057-a56ddae1464d)

### What did you expect to happen?

it must me button where i can download a file like other request with json 
![image](https://github.com/user-attachments/assets/ca864549-2c22-4ab5-a711-d460e4ab75b7)

**Comment by hanspagel** [comment]
Oops, thanks for the report!

**Comment by amritk** [comment]
hello @Kimloang I believe we fixed this one, want to try again?

**Comment by Kimloang** [comment]
yes

**Comment by Kimloang** [comment]
![image](https://github.com/user-attachments/assets/a56840a3-7846-4a22-a9d5-cf2b4c05f42b)
problem is solved with version 1.2.39
