### ISSUE TITLE
.net 9 without comments in scalar UI

### ISSUE THREAD

**Issue by XLJ-CN** [scalar/scalar#3881]
### What happens?

hi,
你好啊，
.net 9 release lastday;
.net9昨天发布了；
Thank you for your excellent work！
感谢你们的付出！
I wrote the code according to documentation,But I have some problems.
我按照文档来编写代码，但是遇到了一些问题
There is no detailed annotation explanation in the web view, such as my method description and the meaning of my fields;
使用Scalar时在web界面中不显示方法注释和我的字段说明；
swagger
![image](https://github.com/user-attachments/assets/30dbbc09-8cd5-408d-92b8-c94b0d007e61)
scalar(no comments )
![image](https://github.com/user-attachments/assets/63e348c9-285f-4be3-8d69-d38de5824bca)

Do I need to configure it in OpenAPI or in Scalar to solve this problem?(in the swagger i can use XML file)
我是需要配置OpenApi呢还是配置Scalar？(使用swagger的时候是配置一个XML文件就可以)
Thank you very much!
非常非常感谢！

### What did you expect to happen?

Display my method instructions and field descriptions
显示方法说明和字段说明

**Comment by XLJ-CN** [comment]
> Hey, which OpenAPI document generator are you using? Did you switch to `Microsoft.AspNetCore.OpenApi` package? If so, this package currently has no support for reading XML comments. This feature request is reported in [dotnet/aspnetcore#39927](https://github.com/dotnet/aspnetcore/issues/39927). However, you could use attributes like `[EndpointDescription]`. The docs can be found [here](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/include-metadata?view=aspnetcore-9.0&tabs=minimal-apis#include-openapi-metadata-for-endpoints).

thank you very much,your reply help me a lot!
非常感谢，你的回复对我帮助很大！
use such as [EndpointDescription] can work!
使用像 [EndpointDescription] 这样的标签就可以了！
But I also hope can support https://github.com/dotnet/aspnetcore/issues/39927 it is very convenient !
但是我还是期望能够实现这个请求，这样读取xml生成文档的方式是非常方便的！

**Comment by xC0dex** [comment]
Glad to hear that your question has been answered. I'll close this issue.
