### ISSUE TITLE
Error when using oAuth2 with client credentials

### ISSUE THREAD

**Issue by danstanciu90** [scalar/scalar#3884]
### What happens?

I encountered an error in the console when passing a specification that uses the OAuth2 client credentials flow. Additionally, the OAuth fields are not displayed correctly on the page.
The attached image shows the error from [Scalar Sandbox](https://sandbox.scalar.com/e/-JukW). The same issue occurs when using the `@scalar/api-reference-react package`.
![image](https://github.com/user-attachments/assets/4f3e3649-07d1-4430-a6ae-59d6e9e6bf2a)

### What did you expect to happen?

No error and correctly display the OAuth fields on the page.

### OpenAPI Document

https://sandbox.scalar.com/e/-JukW

**Comment by amritk** [comment]
Hello! Could you try in the test client instead? Hit the test request button then try authorizing there. We should have it fixed in the client and will have it fixed in here after [this ticket](https://github.com/scalar/scalar/issues/3686)

**Comment by danstanciu90** [comment]
Importing the OpenAPI file into the test client seems to be working great. Do you have any idea when you expect this to be fixed in `@scalar/api-reference-react`?

**Comment by amritk** [comment]
Working on it right now!
