### ISSUE TITLE
Searchbox in Firefox needs to have correct z-index

### ISSUE THREAD

**Issue by jzs11** [scalar/scalar#3893]
### What happens?

![image](https://github.com/user-attachments/assets/4db9afa0-04b4-4add-84f1-b0f430cbf16f)

### What did you expect to happen?

Searchbox should be at front

**Comment by hwkr** [comment]
Hi @jzs11! It looks like the search on [galaxy.scalar.com](https://galaxy.scalar.com/) is working in Firefox, do you have a link to your documentation where you're experiencing the issue or a repo with a minimal reproduction?

![Firefox-2024-11-14-19-45-39@2x](https://github.com/user-attachments/assets/ce667eb2-6d0d-406a-9b1f-5c14b5f9d141)

**Comment by hwkr** [comment]
Hmmmm I'm also on MacOS Sequoia (15.0.1 to be specific) and Firefox 132.0.2.

Can you confirm you're also seeing the issue on [galaxy.scalar.com](https://galaxy.scalar.com/)?

Also have you tried a private window in Firefox?

![Firefox-2024-11-14-20-20-37@2x](https://github.com/user-attachments/assets/536b363a-5d4f-4035-882b-db7b86057663)
