### ISSUE TITLE
.NET integration missing from docs page

### ISSUE THREAD

**Issue by captainsafia** [scalar/scalar#3903]
### What happens?

The docs for the .NET integration don't show up in the table of contents in the side of the docs page.

### What did you expect to happen?

.NET integration docs should show up alongside other docs. I think [this file](https://github.com/scalar/scalar/blob/44aad162d747cc8cf717bfe9433af65f05295b9a/scalar.config.json) needs to be updated.

cc: @xC0dex 

### OpenAPI Document

N/A

**Comment by xC0dex** [comment]
You're right, I'll add this!
