### ISSUE TITLE
Oauth2 References Input breaks after Authenticating

### ISSUE THREAD

**Issue by hwkr** [scalar/scalar#3934]
### What happens?

https://github.com/user-attachments/assets/16bb622d-fd87-4867-ba9b-9764a8925ead

### What did you expect to happen?

It should maybe go underneath or replace the other inputs 🤔 

### OpenAPI Document

https://galaxy.scalar.com/

**Comment by amritk** [comment]
This one is gunna get replaced so I wouldn't bother!

**Comment by amritk** [comment]
https://github.com/scalar/scalar/issues/3696
