### ISSUE TITLE
Horizontal overflow in ui.

### ISSUE THREAD

**Issue by jonasfroeller** [scalar/scalar#3956]
### What happens?

Horizontal overflow in `@scalar/api-reference` version `1.25.68`.

### What did you expect to happen?

No overflow.

**Comment by antlio** [comment]
hey @jonasfroeller thanks for the feedback, would you happen to have a screenshot about the issue you encountered?

**Comment by jonasfroeller** [comment]
@antlio Sry I thought I added it. The overflow comes from the sidebar.

![image](https://github.com/user-attachments/assets/2584b3f2-570e-4053-b92a-2fcb30f9cb8d)
