### ISSUE TITLE
 Bug: Scalar API Reference fails to parse OAuth2 authorizationUrl

### ISSUE THREAD

**Issue by ThilinaTLM** [scalar/scalar#3959]
### What happens?

When using the Scalar API Reference tool with my OpenAPI specification for OAuth2 Authorization Code flow, I encounter the following error in the console:

```
TypeError: Cannot read properties of undefined (reading 'authorizationUrl')
    at scalar.js:18747:93
    at e.value.ai.default.e.value.type.ai.default.ai.default.di.default.ui.onClick.n.<computed>.n.<computed> (scalar.js:18753:2)
    at cr (scalar.js:639:40)
    at ur (scalar.js:640:40)
    at HTMLButtonElement.n (scalar.js:1390:53)
```

However, this specification works perfectly in the Swagger Editor.

### What did you expect to happen?

The OpenAPI specification should allow the OAuth2 flow to function correctly in the Scalar API Reference tool. When clicking the "Authorize" button, it should redirect me to the Keycloak sign-in page as expected. This behavior works correctly in Swagger Editor, but in Scalar, it throws a JavaScript error instead of initiating the OAuth2 authorization flow.

I also tested this on [sandbox.scalar.com](https://sandbox.scalar.com,) and the same issue persists.

### OpenAPI Document

https://sandbox.scalar.com/e/vnOgM

**Comment by amritk** [comment]
Hey we are working on this and it will be fixed very soon! You can track it here

https://github.com/scalar/scalar/issues/3686

**Comment by amritk** [comment]
Np we are so close!

**Comment by ThilinaTLM** [comment]
@amritk   

Thanks for the amazing work!  

I tested the new version, and it is working as expected. By the way, I am using the [Scalar.AspNetCore](https://www.nuget.org/packages/Scalar.AspNetCore) package with my .NET project.  

![image](https://github.com/user-attachments/assets/0c11331c-4e33-40ed-8789-49e55523039c)
