### ISSUE TITLE
Response Body not pretty printed

### ISSUE THREAD

**Issue by abdulamite** [scalar/scalar#3962]
### What happens?

When there is a successful response, it is printed on a single line.
![image](https://github.com/user-attachments/assets/242d0e08-0afc-4931-a68f-2965258f6959)

### What did you expect to happen?

The response should be pretty-printed to be more easily readable. Additionally should give the option for raw response.

### OpenAPI Document

https://bolt-docs-git-abdul-api-ref-by-scalar-technical-writing.vercel.app/api-bolt/#tag/transactions/GET/v1/merchant/transactions/{REFERENCE}

**Comment by antlio** [comment]
hey @abdulamite thanks for the issue! a similar one has been opened where a fix is ongoing #3955

**Comment by abdulamite** [comment]
Hey @antlio  thank you so much for letting me know! We can close this request. I will follow the other thread!
