### ISSUE TITLE
Make the standalone version reactive

### ISSUE THREAD

**Issue by hanspagel** [scalar/scalar#397]
### Expected Behavior

Currently, the standalone version picks up the spec on load.

### Actual Behavior

Would be nice to have that reactive … 🤔 

### Reproduction steps

```bash
1. Use CDN version
2. Pass a Swagger spec
3. Update the Swagger spec without reloading
4. Content didn’t change
```

**Comment by hanspagel** [comment]
Out of scope for now.

**Comment by amritk** [comment]
Reopened!

**Comment by amritk** [comment]
Hey @hanspagel this is possible now with the `scalar:update-references-config` event
