### ISSUE TITLE
Code blocks not scrolling horizontally

### ISSUE THREAD

**Issue by AnnikaV9** [scalar/scalar#3996]
### What happens?

Code blocks in Guides wrap instead of scrolling horizontally.

For example, the 2nd last line: 

![image](https://github.com/user-attachments/assets/c4329279-cbf0-4fb4-a34b-25c45dca67ab)

### What did you expect to happen?

I'd expect the blocks to scroll horizontally as it's easier to read, especially on mobile devices.

**Comment by antlio** [comment]
Thanks for reporting it @AnnikaV9, a PR has been opened, will follow up here once released
