### ISSUE TITLE
Why i can't get proper sequence when i import JSON in Scalar desktop app

### ISSUE THREAD

**Issue by marclave** [scalar/scalar#4088]
### Discussed in https://github.com/scalar/scalar/discussions/4076

<div type='discussions-op-text'>

<sup>Originally posted by **aditya05062002** December  3, 2024</sup>
Can some one help me why i get different sequence from original in scalar desktop app. In Scalar Document i get proper sequence like post, get, put, delete, search but in scalar desktop app i get sequence  like delete, get, post, put, get why that happening if i import same JSON into both of them 
![Screenshot (81)](https://github.com/user-attachments/assets/780da2c4-6b40-4250-ba7a-a9064b9c9c59)
![Screenshot (83)](https://github.com/user-attachments/assets/abb48198-3b06-44db-bc4a-5298f02252e6)
</div>

**Comment by hanspagel** [comment]
The order of the requests should be the same as the order in the OpenAPI document, but it’s not for the API client. We need to fix that. 👍
