### ISSUE TITLE
`app` Check for Updates... button doesn't work

### ISSUE THREAD

**Issue by vladshcherbin** [scalar/scalar#4099]
### What happens?

When `Check for Updates` is clicked, nothing is happening

### What did you expect to happen?

When `Check for Updates` is clicked, a new version is checked, downloaded and installed

Scalar 0.1.96
macOS Sequoia 15.1.1

**Comment by vladshcherbin** [comment]
@antlio nice to hear!

How does it update? I can clearly see from github the version in `package.json` is 0.1.100, however the `Check for updates` does nothing, it's still `0.1.96` for me as it was initially

**Comment by antlio** [comment]
scalar app is now running on `v0.1.102` which include that fix
