### ISSUE TITLE
Layout is not configurable in the dotnet package

### ISSUE THREAD

**Issue by SaifAqqad** [scalar/scalar#4126]
### What happens?

The `layout` configuration option was not added in the `ScalarOptions` class, and there's no way to add custom configuration options (like an `AdditionalOptions` dictionary or something similar) [see ScalarOptions.cs](https://github.com/scalar/scalar/blob/main/packages/scalar.aspnetcore/src/Scalar.AspNetCore/Options/ScalarOptions.cs)

### What did you expect to happen?

All supported configuration options should be available in the dotnet configuration

**Comment by hanspagel** [comment]
True! 😬 We’ll add this.
