### ISSUE TITLE
`app` Impossible to get latest version

### ISSUE THREAD

**Issue by vladshcherbin** [scalar/scalar#4128]
### What happens?

The installer from [Download page](https://scalar.com/download) always downloads `0.1.96` version while on github it's already [0.1.102](https://github.com/scalar/scalar/blob/main/packages/scalar-app/package.json)

<img width="652" alt="image" src="https://github.com/user-attachments/assets/27c7e3b1-0714-46ec-a694-577245cc19a1">

In 0.1.96 `Check for updates` button doesn't work so it's impossible to install any version later

macOS 15.1.1

### What did you expect to happen?

- Installer should download and install latest version
- `Check for updates` button should show and install updates

**Comment by antlio** [comment]
hey @vladshcherbin thank you for your feedback! the current released version is `0.1.96`, we are about to release the latest updates today. 

we will do a better job is exposing what is the released version vs what's in GH to provide more clarity here. I'll follow up in that issue for when the last version is released (along with the check for updates fix).

**Comment by antlio** [comment]
@vladshcherbin the app has been released to its latest version `v0.1.102`, let me know if it's up on your side!

**Comment by vladshcherbin** [comment]
yep, `Check for updates` just installed the latest `0.1.102`

Thank you for such a great product! ♥️
