### ISSUE TITLE
Enum values don't flow through to API Client

### ISSUE THREAD

**Issue by Jono-S-NetValue** [scalar/scalar#4142]
### What happens?

Enum values are missing in when you open the api client.

In the API Docs...
![Screenshot 2024-12-10 162634](https://github.com/user-attachments/assets/d822e0bf-6915-4e0d-8381-87d1122f9db7)

In the API Client...
![Screenshot 2024-12-10 162813](https://github.com/user-attachments/assets/bd4eacc9-59a8-487b-b285-c2988e6df350)

You can see the boolean correctly renders a select element to choose true/false, however the enums are not selectable and must be typed in each time.

### What did you expect to happen?

The enum values should be selectable from a dropdown list. In this case with multiselect since it is an array value. 

For context, in SwaggerUI it looks something like this...

![Screenshot 2024-12-10 162859](https://github.com/user-attachments/assets/e33af1e1-a0d7-4ffa-814b-6488abbd21aa)

### OpenAPI Document

https://sandbox.scalar.com/e/xvuZh

**Comment by antlio** [comment]
hey @Jono-S-NetValue thanks for reporting this! an PR has been open regarding this issue

**Comment by Jono-S-NetValue** [comment]
@antlio that was very quick. It has been great to see the progress with scalar these last few months, it is very quickly becoming one of my favourite API documentation tools. Thanks heaps!
