### ISSUE TITLE
Scalar configuration not getting deployed with empty Guides value

### ISSUE THREAD

**Issue by deepanshu-rajput-git** [scalar/scalar#4161]
### What happens?

I am on the pro-plan and I am using a github Scalar API docs project with my custom domain.
But I am getting the error while publishing the project: `Unknown error. Please contact support`

Here is my [scalar.config.json](https://sandbox.scalar.com/e/rWcAN)

### What did you expect to happen?

My expectations from configuration file:
- Remove the guides tab.
- Change the References tab name to APIs and make it the default.
- Add a button on the header for external redirection.
- Change the title and the favicon of the documentation webpage.

@antlio: Please take a look. Is it something wrong with the product or the configuration file.

- [My OpenAPI Document](https://sandbox.scalar.com/e/q5df_)

**Comment by antlio** [comment]
hey @deepanshu-rajput-git, thanks for reporting, sorry about this will take a look at this right now

**Comment by antlio** [comment]
the great @tmastrom has been able to reproduce the issue and is currently patching the issue, will keep you updated once it's released!

**Comment by deepanshu-rajput-git** [comment]
@antlio and @tmastrom, Please keep me updated about the release. I'm eagerly waiting for this. And please take a look at my scalar configuration file to see whether I will be able to achieve all my requirements mentioned above or not.

**Comment by antlio** [comment]
hey @deepanshu-rajput-git, fix has been deployed, feel free to jump back in if you experience issue still regarding this!

**Comment by deepanshu-rajput-git** [comment]
Thanks, @antlio. I was able to publish my API docs, but other configurations like:
- Add a button on the header for external redirection and
- Change the title and the favicon of the documentation webpage are not reflected in the web page.

Please take a look for that as well.

[My API docs](https://apidocs.neetocal.com/apis#tag/bookings)
