### ISSUE TITLE
Missing image for programming-language-http

### ISSUE THREAD

**Issue by cskwrd** [scalar/scalar#420]
### Expected Behavior

Image loads / 200

### Actual Behavior

404

### Reproduction steps

```bash
1. Load example into demo editor.
1. Change lang to HTTP.
1. See broken image.
```

### Version

Demo broken, presumably, latest.

### What browsers are you seeing the problem on?

Firefox

**Comment by hanspagel** [comment]
Oh, yes! Good find.
