### ISSUE TITLE
Server url is stuck in Mac OS app

### ISSUE THREAD

**Issue by Yolley** [scalar/scalar#4240]
### What happens?

If I try to import `scalar-galaxy` example schema that has `servers` configured to Mac OS app the server url will be pre selected across the whole application, even when I try to create a request in a separate folder/workspace.

<img width="1263" alt="image" src="https://github.com/user-attachments/assets/8d0b7ecd-cfb8-4ceb-a44e-ae691c57ab85" />
<img width="1265" alt="image" src="https://github.com/user-attachments/assets/4590273c-6f6e-4292-bdc1-845d306b6029" />

I can't remove the base url or even select a different one.

### What did you expect to happen?

The `servers` configured should applicable only to requests within the collection folder/workspace (I guess within the collection folder is more appropriate).

### OpenAPI Document

https://sandbox.scalar.com/files/m8sCN/openapi.yaml

**Comment by vladshcherbin** [comment]
Guys, how is it even possible to make such releases?

Params are broken, test request params are also broken, now it's even impossible to change the request url. Is there any automated or manual testing setup?

`Scalar` looks and feels phenomenal but the amount of bugs and blocked usage is simply unbelievable 🤯

**Comment by antlio** [comment]
hey @Yolley sorry about that - thank you for reporting, we just patched this in #4197 and I'm releasing the desktop app as of right now!

**Comment by antlio** [comment]
@vladshcherbin thank you for your feedback - i completely understand how frustrating it must be to encounter broken functionality.. 

while we do have automated tests and manual checks in place, this release clearly slipped through, which is on me 🙏.

to address your concerns, we just fixed the issue regarding params not being displayed - this has just been released see #4242 however if any issue remain, hit me up and i'll personally look at it asap!

**Comment by vladshcherbin** [comment]
@antlio macOS app is fixed, I can confirm, thank you 🙌

From what I've seen, path params are not fixed. https://github.com/scalar/scalar/pull/4242 has [example link](https://github.com/scalar/scalar/pull/4242#issuecomment-2547337745) and standalone example [still show invalid params](https://c4ae92ab-f2c5-4253-b0bb-09de142669ce--scalar-deploy-preview.netlify.app/standalone-api-reference#tag/planets/GET/planets/{planetId})

Invalid symbols in param example:

<img width="1089" alt="image" src="https://github.com/user-attachments/assets/3c7b1ce0-1be4-4d38-a070-09f923f48d67" />

No param setting in `Test Request` (I bet I used them in some version before):

<img width="1467" alt="image" src="https://github.com/user-attachments/assets/91a03abd-f30d-487f-98ed-a0f271373a0c" />

**Comment by antlio** [comment]
great to hear @vladshcherbin! great catch thank you i'm diving into it as of right now!

regarding the symbols, we are encoding the url in the request example, would you expect otherwise? thank you so much for reporting all this!

**Comment by vladshcherbin** [comment]
@antlio yes, I'd prefer to see it the same as in url: `{planetId}`. It's much friendlier for developers (same as copy-paste url from docs) and `%7BplanetId%7D` looks like something is misconfigured or charset is incorrect.

I also remember not seeing it in previous version. Check same example from https://github.com/scalar/scalar/pull/4170, with version 1.25.80 - [example link](https://github.com/scalar/scalar/pull/4170#issuecomment-2537402710), here is [the same request](https://95a87044-ed84-40dc-a0bc-beed8d07ef93--scalar-deploy-preview.netlify.app/standalone-api-reference#tag/planets/GET/planets/{planetId}):

<img width="1099" alt="image" src="https://github.com/user-attachments/assets/dfde306b-59f8-46d4-96ed-c96a44555344" />

I believe it's populated from example and looks nice. For some reason current version also doesn't take the param from example

**Comment by antlio** [comment]
@vladshcherbin I agree! I believe this is "breaking" as it is related to the path parameters not being populateed/parsed anymore. we are reducing the scope and hopefully will push a fix as of today!

thank you for your precious feedback on this!

**Comment by antlio** [comment]
@hanspagel created an issue regarding the example request in #4256

**Comment by antlio** [comment]
@vladshcherbin regarding the path params issue i reverted a piece of code in #4263 and will take some more time tomorrow.

@Yolley feel free to close that issue accordingly once everything is ok on your end regarding the server url.

**Comment by antlio** [comment]
@Yolley sorry about that, we updated it for clean slate but i'm adding right now a migration so it will remove juste that part from your draft request 🙏 will keep you update here once released

**Comment by amritk** [comment]
@Yolley we should have the fix up later today! Let us know if it doesn't work!
