### ISSUE TITLE
API Client window is blank

### ISSUE THREAD

**Issue by lc-soft** [scalar/scalar#4245]
### What happens?

1. Run `pnpm dev:reference`
2. Open `http://localhost:5173/`
3. Click `Test request` button
4. Look the API Client window

![request-view-error](https://github.com/user-attachments/assets/4b7099af-1018-4b8f-b053-1f0cf9840310)

### What did you expect to happen?

I tried to find the last release that worked properly and finally found [`cfef80`](https://github.com/scalar/scalar/commit/cfedf80a76dc9975219023de66586ba708ce299b), and this issue has been present since the next release [`5f0caa`](https://github.com/scalar/scalar/commit/5f0caae0edbe40b59f0c832cd4e1a8386392bb60).

Using `cfef80` version to perform the following steps can meet my expectations.

1. Run `git checkout cfef80`
2. Run `pnpm install`
3. Run `pnpm dev:reference`
4. Open `http://localhost:5173/`
5. Click `Test request` button
6. Look the API Client window

![request-view-normal](https://github.com/user-attachments/assets/dfe952f8-5fc1-46fd-abda-944feafd3c3e)

### OpenAPI Document

https://cdn.jsdelivr.net/npm/@scalar/galaxy/dist/latest.json

**Comment by antlio** [comment]
hey @lc-soft thank you for reporting this! i do not replicate on my side, can you run `pnpm turbo build` prior to `pnpm dev:reference`? and potentially clear your browser storage?

let me know how it goes!

**Comment by lc-soft** [comment]
> hey @lc-soft thank you for reporting this! i do not replicate on my side, can you run `pnpm turbo build` prior to `pnpm dev:reference`? and potentially clear your browser storage?
> 
> let me know how it goes!

Okay, my GitHub Codespaces reached 100% usage and cannot be used after creating this issue. I will try to reproduce this issue after completing my work.

**Comment by antlio** [comment]
> > hey @lc-soft thank you for reporting this! i do not replicate on my side, can you run `pnpm turbo build` prior to `pnpm dev:reference`? and potentially clear your browser storage?
> > let me know how it goes!
> 
> Okay, my GitHub Codespaces reached 100% usage and cannot be used after creating this issue. I will try to reproduce this issue after completing my work.

oh! ok sure feel free to let me know!

**Comment by antlio** [comment]
> This issue is caused by GitHub Codespaces, and sometimes CORS errors occur when requesting files. Changing the visibility in port forwarding from Private to Public can solve this issue.

that's good to know, thank you for sharing!
