### ISSUE TITLE
Query parameters are longer being sent

### ISSUE THREAD

**Issue by Yolley** [scalar/scalar#4325]
### What happens?

It seem that there was a regression in one of the recent scalar versions. The web client currently does not send any query parameters, it's reproducible with an Example Galaxy API if we try to make a `Get All Planets` request with limit and offset configured.

<img width="1800" alt="image" src="https://github.com/user-attachments/assets/cb7fb58d-3478-4ffe-928c-308472529c1c" />

### What did you expect to happen?

I expect the API client to send query parameters if they were configured and enabled.

### OpenAPI Document

https://sandbox.scalar.com/files/u7-Dw/openapi.yaml

**Comment by amritk** [comment]
Thanks for the report, fix on the way!
