### ISSUE TITLE
Impossible to use App on macOS

### ISSUE THREAD

**Issue by vladshcherbin** [scalar/scalar#4327]
### What happens?

I've no idea how this is happening since I don't have anything in the app, but new Workspaces somehow can't do clean requests.

Simplest new workspace test to `https://google.com`

https://github.com/user-attachments/assets/950bef09-56ae-4c58-b5a2-d4882e9cee9c

<img width="396" alt="image" src="https://github.com/user-attachments/assets/0bef07b1-0317-49db-9152-3123f127d71f" />

### What did you expect to happen?

Request should return `https://google.com` response, not some other workspace/cached/deleted/idk where taken response

### OpenAPI Document

no need

**Comment by amritk** [comment]
hello there @vladshcherbin do you have anything set as the proxy?  hit settings in the bottom left
![image](https://github.com/user-attachments/assets/2a4eda71-742f-4607-a7b3-80ea0791d769)
![image](https://github.com/user-attachments/assets/9e4477e4-b8b8-48c8-8979-8d0c6d09c968)

Then you should be able to see if anything is set there. Seems like its proxying through a vercel app

**Comment by vladshcherbin** [comment]
I don't have any settings for proxy or environment

**Comment by vladshcherbin** [comment]
Anyway I've moved back to Insomnia, can't stand the amount of bugs I find on daily basis. Closing since I won't be able to test.

There's also a bug where watch mode doesn't work the expected way. If you stop it - it will still do schema requests every ~5 seconds. Won't open another issue for it, just a note.

**Comment by marclave** [comment]
hey @vladshcherbin , we really appreciate you opening this issue and giving us context.

we also apologize for the bugs you've been hitting! i'm looking into this one right now.

stability is something we are moving towards, there was a lot of sweeping changes we had to make in the last 3 months that were a necessary evil that unfortunately made stability a bit hard to maintain.

no excuses, just wanted to give context. we are working hard on stability now.

i will update this thread once this is resolved, and also hope in the future you can try out scalar again :) 


appreciate your time.
