### ISSUE TITLE
Move the config object to a ref in the examples

### ISSUE THREAD

**Issue by hanspagel** [scalar/scalar#482]
people find the configuration object a bit confusing and heard to edit inline

i think we can move the config object to a ref in the examples so people arent inlining inside the template tags but rather the script tags

**Comment by ATREAY** [comment]
hey @hanspagel, I would like to work on this issue if it's open.
Additionally, could you provide a link or reference to the location of this issue?

**Comment by hanspagel** [comment]
Oh, this is great! I think those are the relevant files:

1. https://github.com/scalar/scalar/blob/main/README.md
2. https://github.com/scalar/scalar/blob/main/packages/api-reference/README.md

**Comment by ATREAY** [comment]
Hey @hanspagel, just a quick check-in. Should we relocate the configuration section to the main README.md file of the repository, or is the intention to include examples related to the configuration of the API reference in the main README.md file?

**Comment by hanspagel** [comment]
I think the root README should just have something to quickly grasp what this is about and the package README should have a full reference with all options. Wdyt?

**Comment by ATREAY** [comment]
Certainly, we can implement the following approach: In the main README.md file, we'll include a summary of the configuration section from the package's README.md file. For more detailed information, we'll provide a link to the specific package's README.md file. 

Placing this in the "Getting Started" section, following the "from a CDN" part, seems like a good placement.

What are your thoughts on this?

**Comment by ATREAY** [comment]
Hey @hanspagel, I have added a summary about configuring the API reference. Could you please take a look whenever you have a moment?
