### ISSUE TITLE
invalid url when model is selected.

### ISSUE THREAD

**Issue by Mohib834** [scalar/scalar#512]
### Expected Behavior

When selecting the model from the sidebar it should show the same model name in the url as well.

### Actual Behavior

Selecting the model sets the name of the adjacent model in the URL which is invalid but shows valid content. 

<img width="663" alt="Screenshot 2023-11-19 at 8 55 20 PM" src="https://github.com/scalar/scalar/assets/47316464/5b2559b7-b803-48ef-a85b-3293bb241199">

### Reproduction steps

```bash
1. Create a Test petstore
2. Start clicking on the models on the sidebar
3. Switch models multiple times
4. Check the url
```

### Version

[v0.1.0](https://github.com/scalar/scalar/releases/tag/v0.1.0)

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by hanspagel** [comment]
Thanks for reporting! We keep track of it in #296. ✌️
