### ISSUE TITLE
Doesn't render enum values

### ISSUE THREAD

**Issue by thelinuxlich** [scalar/scalar#525]
### Expected Behavior

When a field has the enum property, Scalar should show the possible values

### Actual Behavior

It shows the field simply as string: 
![image](https://github.com/scalar/scalar/assets/5043/85575ac0-2e18-4c1c-921b-0657c318923b)

### Reproduction steps

```bash
Add a property like this:


"entity_type": {
    "type": "string",
    "enum": [
         "company",
         "user"
    ]
}

And render it on Scalar
```

### Version

latest

### What browsers are you seeing the problem on?

Chrome

**Comment by hanspagel** [comment]
You’re so right

**Comment by thelinuxlich** [comment]
I think we can close this one

**Comment by shrawani92** [comment]
how to use this with scalar_fastapi library?

**Comment by Songkeys** [comment]
Can we add support to render dropdowns for enums in Test Request?
