### ISSUE TITLE
Endpoint-level parameters not provided as variables in API client

### ISSUE THREAD

**Issue by bigmike36c** [scalar/scalar#531]
### Expected Behavior

This is an extension of issue #499. While endpoint-level parameters are now properly documented, they do not show up as variables in the API client like method-level parameters do, even if they are required.

The API client should populate the variables with endpoint-level parameters just like it does for method-level parameters. Ideally, they should also use the default values when provided in the spec.

### Actual Behavior

The variables for endpoint-level parameters must be manually added for every request.

### Reproduction steps

```bash
1. Go to this API spec: https://raw.githubusercontent.com/gravitee-io/gravitee-api-management/master/gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/resources/openapi/openapi-apis.yaml
2. Copy the spec and paste it into the demo: https://docs.scalar.com/swagger-editor
3. Go to preview and go to the first endpoint "List APIs"
4. Select "Test Request"
5. There is no variable for endpoint-level parameter envId
```

### Version

Demo and/or CDN

### What browsers are you seeing the problem on?

Chrome, Safari (macOS)

**Comment by hanspagel** [comment]
Thanks for creating the follow-up issue. I saw this, too and took a note, will follow up with that feature. ✌️
