### ISSUE TITLE
Endpoints get rendered with security scheme even if they don't have it

### ISSUE THREAD

**Issue by thelinuxlich** [scalar/scalar#532]
### Expected Behavior

A security scheme defined on the document root should be applied only for endpoints which refer to the scheme through the `security` object.

### Actual Behavior

For example, a Bearer scheme defined on top but a endpoint that doesn't require it: 
![image](https://github.com/scalar/scalar/assets/5043/63883820-f709-4e83-92e4-871c25107a77)

### Reproduction steps

```bash
Add a security scheme to the root


"components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    },
    "schemas": {}
  }


Then add a endpoint without a security object, you should see it requiring the security scheme anyway
```

### Version

latest

### What browsers are you seeing the problem on?

Chrome

**Comment by hanspagel** [comment]
Oh, that’s a good find, I didn’t notice this!

**Comment by thelinuxlich** [comment]
Great find, but I think it's worth mentioning that the optional part was added in OpenAPI 3.1, it seems with 3.0 the behavior should be to ignore the top-level security scheme if the endpoint doesn't have a definition.

**Comment by zz5840** [comment]
Any update on this? 

I hope there could have a lock icon if endpoint needs authentication, just like what Swagger UI does.
