### ISSUE TITLE
landing page bug

### ISSUE THREAD

**Issue by murithigeo** [scalar/scalar#567]
### Expected Behavior

When requesting the path `/`, Scalar should return the response returned to (that) path at `http://serveraddress/v1/` 
![Screenshot (25)](https://github.com/scalar/scalar/assets/128323054/857ce8a3-9b50-4281-aea2-47c644e5a0d6)

### Actual Behavior

Scalar actually requests a non correct path at `http://serveraddress/`. This is incorrect as that is an invalid path. However, if you use a new path at `http://serveraddress//`, then Scalar queries the correct path. I dunno how to describe it more than that. 
![Screenshot (27)](https://github.com/scalar/scalar/assets/128323054/063f110b-b37a-40df-a61e-499d1c27ca38)

### Reproduction steps

```bash
1. Any OAS/Swagger file with the paths "/" and "//"
2. Any HTTP server that can serve data to those paths.
3. Generate scalar docs at the http server address.
4. Request data from the paths specified.
```

### Version

CDN

### What browsers are you seeing the problem on?

Chrome

**Comment by marclave** [comment]
Looks like github automagically closed this ✨  @murithigeo you can see this fixed in the latest release `@scalar/api-reference@1.2.7
`
