### ISSUE TITLE
ApiReference ignores footer slot

### ISSUE THREAD

**Issue by BenediktHeinrichs** [scalar/scalar#568]
### Expected Behavior

ApiReference should respect footer slot.

### Actual Behavior

When upgrading to 1.2.5 from 1.0.6, the footer slot does not get rendered anymore.

ApiReferenceBase still has that slot, but exchanging them is not really sufficient in my use case.

### Reproduction steps

```bash
1. Use #footer in ApiReference
```

### Version

1.2.5

### What browsers are you seeing the problem on?

Chrome

**Comment by hanspagel** [comment]
Oh no, I’ll check that.

**Comment by hwkr** [comment]
Hi @BenediktHeinrichs! Looks like this got pulled out during the layout refactor we did a while ago, I've added it back to be below the content :)

**Comment by BenediktHeinrichs** [comment]
Love the response time of you guys, really great product & team!
