### ISSUE TITLE
Scalar does not add optional query parameters to the request path

### ISSUE THREAD

**Issue by murithigeo** [scalar/scalar#578]
### Expected Behavior

Scalar should variables to request url. For instance, if I wanted to filter by using `http://localhost/api` and parameter `f=json` then the request URL should be `http://localhost/api?f=json`.

### Actual Behavior

As it is, scalar is not initializing the entered parameter variables to the url

### Reproduction steps

```bash
1. Clone the repo at: https://github.com/murithigeo/scalartestreproduce.git
2. Install the needed packages (npm install) and run the http server to listen at localhost using node server.js
3. Go to http://localhost/api?f=html to view the docs.
4. Request data from the /api path but using the f=html parameter.
5. Open the Developer tools on your browser to see the requests being made.
```

### Link to site / OpenAPI Spec

https://github.com/murithigeo/scalartestreproduce.git

### Version

@scalar/express-api-reference: 0.0.11

### What browsers are you seeing the problem on?

Chrome for Windows latest

**Comment by Mohib834** [comment]
This works when you add a key-value pair in the "Query parameters" section instead of "Variables" section in the API client modal. 

@hanspagel i thinkg we should add the parameters of query to the "Query parameters" section ? Let me know, i'll take the task.

Thanks

```
openapi: 3.0.3
info:
  version: 1.0_scalar_CORS_test
  title: test
servers:
  - url: 'http://localhost/v1'
paths:
  /api:
    x-exegesis-controller: jsonController
    get:
      x-exegesis-operationId: apiDef
      parameters:
        - in: query
          name: f
          required: false
          schema:
            type: string
            enum:
              - json
              - html
      responses:
        '200':
          description: Ok.
          content:
            application/vnd.oai.openapi+json;version=3.0:
              type: string
            text/html:
              schema:
                type: string
```

**Comment by murithigeo** [comment]
I think having two sections for path or query parameters is redundant, considering that the query parameters are displayed on the Variables section but not in the Query Parameters section but don't do anything there.

**Comment by hanspagel** [comment]
Yeah, this is pretty much work in progress. Variables are used in a lot of places, so we need this as a separate interface.

But query parameters should be prefilled as far as we can do that based on the spec. @Mohib834 If you want to work on this, your contributions are appreciated! 👍

**Comment by murithigeo** [comment]
Will scalar therefore detect query parameters and move them into the Query Parameters section instead of prefilling in the variables section?

**Comment by Mohib834** [comment]
> Will scalar therefore detect query parameters and move them into the Query Parameters section instead of prefilling in the variables section?

Yes most likely.

**Comment by shfrmn** [comment]
@hanspagel Hilariously I encountered this issue and came across this thread literally the minute when you released the fix. Instant life improvement :) Thank you for your work!
