### ISSUE TITLE
Getting underline on the search items

### ISSUE THREAD

**Issue by Mohib834** [scalar/scalar#583]
### Expected Behavior

I don't think underline is a desired behavior in search items.

### Actual Behavior

Search items showing the underline.

<img width="557" alt="Screenshot 2023-11-28 at 4 44 27 PM" src="https://github.com/scalar/scalar/assets/47316464/4d412bc0-1db4-4018-8f2a-a90b20b82c7d">

### Reproduction steps

```bash
1. Go to search
```

### Version

latest

### What browsers are you seeing the problem on?

Chrome

**Comment by hanspagel** [comment]
Confirmed, fix is in the works.

**Comment by hanspagel** [comment]
Fixed in #584
