### ISSUE TITLE
Oauth 2.0 is unfinished, PKCE is missing

### ISSUE THREAD

**Issue by marclave** [scalar/scalar#604]
### Expected Behavior

oauth2.0 to be functional

### Actual Behavior

![image](https://uploads.linear.app/06a32804-030f-45a1-98aa-79d02a076af5/52e38c5a-2f4a-4eb4-81bb-d0399a5dea6b/d26cb30f-29af-4949-9708-ebe2f4777acb?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzA2YTMyODA0LTAzMGYtNDVhMS05OGFhLTc5ZDAyYTA3NmFmNS81MmUzOGM1YS0yZjRhLTRlYjQtODFiYi1kMDM5OWE1ZGVhNmIvZDI2Y2IzMGYtMjlhZi00OTQ5LTk3MDgtZWJlMmY0Nzc3YWNiIiwiaWF0IjoxNzAxMzYyNTM5LCJleHAiOjE3MDE0NDg5Mzl9.Svq0h0NPwnE0sq_fkfe0cHKNx_0zuFJ0J0OZejXHc4E)

### Reproduction steps

```
on latest main with oauth2.0 as an auth type, it's missing and has warning
```

### Link to site / OpenAPI Spec

[docs.scalar.com/swagger-editor](http://docs.scalar.com/swagger-editor)

### Version

latest

### What browsers are you seeing the problem on?

*No response*

<sub>From [SyncLinear.com](https://synclinear.com) | [DOC-1382](https://linear.app/api-docs/issue/DOC-1382/oauth-20-is-unfinished)</sub>

**Comment by hanspagel** [comment]
Started to implement in #613 

**Remaining Tasks**
- [ ] Retrieve the token after the redirect, and keep that in the store
- [ ] Show the stored token
- [ ] Use that token for all requests
- [ ] Optional: Set up an Open Auth 2 backend to test the flow

**Comment by big-kahuna-burger** [comment]
Anyone willing to collaborate on this to have it finished?

TBH, I'm not a good UI developer.
But I can provide supporting OP (OIDC Provider that you can also run locally) 
I depend on `@scalar/fastify-api-reference`. The way I use scalar it is to expose a management API for provider.

https://github.com/big-kahuna-burger/f0

What I'm looking for is a similar behaviour as in SwaggerUI, supporting both oauth2/openIdConnect props in swagger definition and token pre-fill for relevant APIs. 

LMK

**Comment by marclave** [comment]
@big-kahuna-burger thanks for the comment! Would love some support on OIDC provider ✨

Any good docs on integration? So we can brainstorm the UI

@hanspagel what is left for oauth 2.0? let's spec it out and get this wrapped up ✨

**Comment by big-kahuna-burger** [comment]
I suggest you try and spin my project locally (needs docker to run postgres container). 
There is a readme to get started.
Any feedback you give, bug report, will help me understand where I lack good get started documetation and it will give you a local issuer.

That you can then plug into a openapi description (use issuer metadata, set auth/token endpoints, etc...) and start using it as OIDC provider.

**Comment by big-kahuna-burger** [comment]
@marclave I can also provide you with a feedback on how to approach the integration related to oidc/oauth2 RFCs and protocol implementation details (grant types, parameters required, how to interpret metadata etc...). 
So you don't have to read and learn that dry RFC lingo.

**Comment by marclave** [comment]
amazing, thanks so much @big-kahuna-burger . will keep you posted on progress ✨

**Comment by benox3** [comment]
Would love to have the ability to use client credentials flow

**Comment by hanspagel** [comment]
@benox3 Is your specification public? Having a straight forward example would help me to quickly add to the feature for you.

**Comment by benox3** [comment]
> @benox3 Is your specification public? Having a straight forward example would help me to quickly add to it.

Unfortunately not, hopefully @big-kahuna-burger can spin up a good example, otherwise when I have time i can try to create a demo repo.

**Comment by big-kahuna-burger** [comment]
@hanspagel with Client Credentials Grant two methods that can be used for client auth are Basic and POST.
Here is example for both with my server: https://gist.github.com/big-kahuna-burger/c3292572d2e7ba2dbf8945e63b03872d

Please note that Basic is a recommended method, and post should only be used when clients have no means of sending auth header properly, but would be ideal to support both of them.

**Comment by big-kahuna-burger** [comment]
So, in UI there can be a select between Basic and POST with Basic as default option. Also a map for extra parameters would be nice so we can select resource/scope. For example, some auth servers like Auth0, will support resource in `audience` parameter, that's why freeform Object/Map for additional properties is desired.

**Comment by seanlaff** [comment]
Should scalar display the required scopes for an endpoint, or is that out of scope for the work being discussed here?

**Comment by big-kahuna-burger** [comment]
@seanlaff it could be showing scopes from api spec file. Openapi spec supports that. Swagger UI supports that. 
Scalar should, if it wants to topple swagger ui in terms of goto UI for Openapi spec files.

**Comment by big-kahuna-burger** [comment]
@seanlaff it's matter of proper interpretation of the spec file. Definitely possible and desired.

See: https://swagger.io/docs/specification/authentication/

Scope section there. Both OAuth2 and Oidc versions support scopes by this docs site. (Not sure how authoritative this is, but I think pretty correct)

**Comment by big-kahuna-burger** [comment]
As you align the branch let me know. I'd be glad to take a look at it. 
Let me know if you need to setup different grant types for testing, i'd be glad to provide various  RP client setups.

**Comment by big-kahuna-burger** [comment]
Great!
But that is just implicit flow.

Authorization Code grant (PKCE)
Client credentials... resource/scope support?

Also, implicit is somewhat not recommended to use, like becoming deprecated flow, PKCE being secure alternative.

**Comment by marclave** [comment]
@big-kahuna-burger great point! I am re-opening this :) 

our oauth journey is ✨ just getting started ✨

**Comment by big-kahuna-burger** [comment]
I'm going to set up tomorrow my OP with a client that is public oAuth client (token endpoint authentication method being none), and give a bare minimum example how to do Auth Code Grant with PKCE using this client.

Should set the implementor on the right track.

**Comment by nowells** [comment]
@marclave did you intend for the release commit to re-close this?

**Comment by marclave** [comment]
@hanspagel @nowells this is still ongoing :)

**Comment by hanspagel** [comment]
Oops, was auto closed, my bad. Let’s add to this!

**Comment by big-kahuna-burger** [comment]
went under my radar due to closing, will provide clients as described above

**Comment by jhancock-taxa** [comment]
It appears that "OpenIdConnect" is not enabled too?

**Comment by OwenCross289** [comment]
Are there any updates on this? I would love to start using Scalar in my ASP.NET Core project, but sadly I can't until PKCE as a log in flow is available

**Comment by CrisBeFranc** [comment]
> Are there any updates on this? I would love to start using Scalar in my ASP.NET Core project, but sadly I can't until PKCE as a log in flow is available

Backing this one up here - was trying today to finally move over from Swagger but without the PKCE flow I sadly have to park it over until that is possible.

**Comment by amritk** [comment]
![image](https://github.com/user-attachments/assets/9610573a-a477-436b-9c43-4b6a4e83ae11)
pkce flow is coming!

**Comment by amritk** [comment]
![image](https://github.com/user-attachments/assets/9151c5a2-c32d-4ecd-b342-27ef4ec67d50)

Alright we are almost there, just need to do the front-end now. Do you usually want to enter in the code verifier + challenge method or have it auto generated?

**Comment by big-kahuna-burger** [comment]
> ![image](https://github.com/user-attachments/assets/9151c5a2-c32d-4ecd-b342-27ef4ec67d50)
> 
> 
> 
> Alright we are almost there, just need to do the front-end now. Do you usually  enter in the code verifier + challenge method or have it auto generated?
> 
> 
> 
> Edit: for v1 I will just leave it auto generated, then we can add some UI to enter custom verifiers after 😄 

You should leave it auto generated. No need to have custom at all. Also, if you want to be compliant with strict providers, you need to have code_verifier base64url encoded of starting random 32 bytes length.

```
const verifier = () => base64url.encode(randomBytes(32));
```

**Comment by amritk** [comment]
@big-kahuna-burger thanks for the review, will implement those changes next week!

**Comment by amritk** [comment]
Alright how's it look now? Does anyone care to test it out? 

https://github.com/scalar/scalar/pull/3732

**Comment by skolmer** [comment]
> Alright how's it look now? Does anyone care to test it out?
> 
> #3732

Great work! 👍 The final missing piece now is a PKCE option in here: https://github.com/scalar/scalar/blob/main/packages/scalar.aspnetcore/src/Scalar.AspNetCore/Options/Authentication/OAuth2Options.cs

**Comment by rhuanbarreto** [comment]
Great work. Also is there a way to document how to initialize the clientid and scopes so it comes pre filled?

**Comment by sorcerb** [comment]
Thank you, and how preset "Use PKCE: SHA-256"?
OAuth2Options have only ClientId and Scopes

**Comment by magahl** [comment]
> Thank you, and how preset "Use PKCE: SHA-256"? OAuth2Options have only ClientId and Scopes

Below worked for me.
```csharp
var securitySchema =
            new OpenApiSecurityScheme
            {
                Type = SecuritySchemeType.OAuth2,
                Scheme = "Bearer",
                BearerFormat = "JWT",
                Flows = new()
                {
                    AuthorizationCode = new OpenApiOAuthFlow()
                    {
                        AuthorizationUrl = new Uri($"{Constants.Authority}/oauth2/v2.0/authorize"),
                        TokenUrl = new Uri($"{Constants.Authority}/oauth2/v2.0/token"),
                        Scopes = new Dictionary<string, string> { { $"<insert your scope>", "Access the API" } },
                        Extensions = new Dictionary<string, IOpenApiExtension>()
                        {
                            ["x-usePkce"] = new OpenApiArray()
                            {
                                new OpenApiString("SHA-256"), new OpenApiString("no")
                            }
                        },
                    },
                },
            };

```
