### ISSUE TITLE
[DOC-1388] REST API Client doesnt reset response when changing active item

### ISSUE THREAD

**Issue by marclave** [scalar/scalar#619]
### Expected Behavior

the response should be empty or chosen from response history of the active request

### Actual Behavior

last request regardless of active

### Reproduction steps

```bash
send request
change active item
response is for other request
```

### Version

latest

<sub>[DOC-1388](https://linear.app/api-docs/issue/DOC-1388/rest-api-client-doesnt-reset-response-when-changing-active-item)</sub>

**Comment by hanspagel** [comment]
Good news, this was fixed in #573 already: https://github.com/scalar/scalar/blob/main/packages/api-reference/src/helpers/showItemInClient.ts#L21
