### ISSUE TITLE
Fastify w/ Fluent JSON Schema Body

### ISSUE THREAD

**Issue by puchesjr** [scalar/scalar#634]
### Expected Behavior

Expect the plugin to properly identify the request body schema. @mcollina

### Actual Behavior

Does not detect the request body schema. Does detect the params.

### Reproduction steps

```bash
npm i @scalar/fastify-api-reference @fastify/swagger

create an route with fluent schema for validation. 
create plugin using @fastify/swagger
create plugin using @scalar/fastify-api-reference

set documentation to /documentation - works and documentation is visible.

path params are detected, but not json body request validation from the schema.
```

### Version

0.8.3

### What browsers are you seeing the problem on?

Chrome, Safari (macOS), Firefox

**Comment by rozbo** [comment]
+1

**Comment by GrzegorzKastelik** [comment]
+1

**Comment by MrSharpp** [comment]
I want to do this task, but i am unable to move it to in progress!

**Comment by mcollina** [comment]
Could you add a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by IgorHalfeld** [comment]
+1

**Comment by mcollina** [comment]
@marclave can you take a look?

**Comment by marclave** [comment]
investigating now :)

**Comment by hanspagel** [comment]
I’m testing this snippet:

```js
const S = require('fluent-json-schema')

// You can have an object like this, or query a DB to get the values
const MY_KEYS = {
  KEY1: 'ONE',
  KEY2: 'TWO'
}

const bodyJsonSchema = S.object()
  .prop('someKey', S.string())
  .prop('someOtherKey', S.number())
  .prop('requiredKey', S.array().maxItems(3).items(S.integer()).required())
  .prop('nullableKey', S.mixed([S.TYPES.NUMBER, S.TYPES.NULL]))
  .prop('multipleTypesKey', S.mixed([S.TYPES.BOOLEAN, S.TYPES.NUMBER]))
  .prop('multipleRestrictedTypesKey', S.oneOf([S.string().maxLength(5), S.number().minimum(10)]))
  .prop('enumKey', S.enum(Object.values(MY_KEYS)))
  .prop('notTypeKey', S.not(S.array()))

const schema = {
  body: bodyJsonSchema,
}

export default async function (fastify, opts) {
  fastify.post('/example', { schema }, async (request, reply) => {
    return { hello: fastify.example }
  })
}
```

and get this result:

![Screenshot 2024-01-06 at 01 25 42](https://github.com/scalar/scalar/assets/1577992/1099bdf1-5726-458c-92d6-d3e780f53587)

I see a few things that we can improve, but it does show the JSON body schema. What am I missing? Can someone provide a fluent schema, where the body isn’t shown? 🤔

**Comment by GrzegorzKastelik** [comment]
@hanspagel When I use typebox then result is:
 
![Zrzut ekranu 2024-01-10 o 10 39 26](https://github.com/scalar/scalar/assets/102555611/78811aec-37e6-474c-b9c8-8206732b2093)

When in this case swaggerUI show body like that:

![Zrzut ekranu 2024-01-10 o 10 41 38](https://github.com/scalar/scalar/assets/102555611/d640583a-128b-446b-8740-4728532c9639)

And this is my schema definition:

![Zrzut ekranu 2024-01-10 o 10 42 47](https://github.com/scalar/scalar/assets/102555611/c87ed8dd-9ea2-466a-a5f3-33cc48355e61)

And body def:

![Zrzut ekranu 2024-01-10 o 10 43 31](https://github.com/scalar/scalar/assets/102555611/fb0accba-137a-4f23-9ed6-d11633508ae8)

Maybe it's not working for typebox?

**Comment by alzalabany** [comment]
i get "default response" for all routes; eventho when downloading specs i can see response definition.
switching to swaggerUI show response docs okay.

**Comment by marclave** [comment]
@GrzegorzKastelik thanks for sharing this extra detail! this is helpful, investigating now :)

**Comment by marclave** [comment]
@alzalabany do you have an example swagger file I can look to for which you mean "default response" for all routes?

**Comment by hanspagel** [comment]
Jumped through a few hoops to get to it, but I’ve finally got an OpenAPI spec that’s generated by typebox. This doesn’t render properly. We’ll come up with a fix for it. :v:

```js
{
  "openapi":"3.1.0",
  "info":{
     "title":"Hello World",
     "version":"1.0.0"
  },
  "paths":{
     "/typebox":{
        "post":{
           "parameters":[
              {
                 "name":"body",
                 "in":"body",
                 "schema":{
                    "type":"object",
                    "properties":{
                       "x":{
                          "type":"string"
                       },
                       "y":{
                          "type":"number"
                       },
                       "z":{
                          "type":"boolean"
                       }
                    },
                    "required":[
                       "x",
                       "y",
                       "z"
                    ]
                 }
              }
           ],
           "responses":{
              "200":{
                 "description":"Default Response"
              }
           }
        }
     }
  }
}
```
