### ISSUE TITLE
Changing the example request library the scroll position needs to be updated

### ISSUE THREAD

**Issue by hanspagel** [scalar/scalar#65]
When changing the example request library, the example request code snippet becomes shorter/longer and the scroll position needs to be updated.

**Comment by hwkr** [comment]
Okay so after digging into this a bit it seems like this just shouldn't be happening. That being said it is... All modern browser seem to support [scroll anchoring](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-anchor/Guide_to_scroll_anchoring) but for some reason its not being enabled for us, I tried debugging but haven't figured out why not yet.

https://github.com/WICG/ScrollAnchoring/blob/master/explainer.md

**Comment by hanspagel** [comment]
TIL scroll anchoring

Thanks for doing this deep dive! I think we can just ignore this for now then. 🤡
