### ISSUE TITLE
page title can’t be changed

### ISSUE THREAD

**Issue by hanspagel** [scalar/scalar#709]
I think there’s no way to change the page title, though I assumed you can do it through the `metaData` configuration. 🤔

Would be nice to have a way to set a custom page title, too.

**Comment by hanspagel** [comment]
Nobody seems to be interested in this, so let’s close it for now. :)

**Comment by 1qh** [comment]
I'm interested

**Comment by marclave** [comment]
> I'm interested

Re-opened :)

**Comment by hex0id** [comment]
interested

**Comment by Yomudogly** [comment]
I'm interested

**Comment by hanspagel** [comment]
Short update: This package we use ([vueuse/head](https://github.com/vueuse/head)) doesn’t seem to work in that scenario. I tried a few things, but I’m still not sure whether it’s me holding it wrong or if it’s the package. Unfortunately, I was interrupted, so it needs further investigation.

**Comment by hex0id** [comment]
@hanspagel according to vueuse/head docs it's sunsetting:

> The @vueuse/head package has been sunset in favour of Unhead. This means no new features will be added to this package and installation of this package directly will be discouraged.

ref: https://github.com/vueuse/head

**Comment by hanspagel** [comment]
Fixed in #2085. :)
