### ISSUE TITLE
Show response schemas next to the response examples

### ISSUE THREAD

**Issue by hanspagel** [scalar/scalar#710]
### Discussed in https://github.com/scalar/scalar/discussions/329

<div type='discussions-op-text'>

<sup>Originally posted by **myftija** October 19, 2023</sup>
Hi 👋

It would be useful to show the schema of the response object instead of only an example response. Maybe somewhat similar to how Github approaches this: [link](https://docs.github.com/en/free-pro-team@latest/rest/repos/repos?apiVersion=2022-11-28#get-a-repository). Is it something you would consider in the future?

Scalar looks very promising. Love the design. Keep up the great work!</div>

**Comment by hanspagel** [comment]
Time to get this added, I’ve submitted a PR here: https://github.com/scalar/scalar/pull/783

**Comment by marclave** [comment]
in the release `@scalar/api-reference@1.13.3` ✨
