### ISSUE TITLE
[DOC-1430] Scalar NestJS Integration with Helmet doesnt work

### ISSUE THREAD

**Issue by marclave** [scalar/scalar#727]
### Expected Behavior

it won't run alongside Helmet https://docs.nestjs.com/security/helmet.

### Actual Behavior

it should work with helmet

### Reproduction steps

```bash
install nestjs
install scalar nestjs integration
install helmet
wont run
```

### Version

latest

<sub>[DOC-1430](https://linear.app/api-docs/issue/DOC-1430/scalar-nestjs-integration-with-helmet-doesnt-work)</sub>

**Comment by marclave** [comment]
hey @emmanuelvr, i wasn't able to reproduce this. are you able to share a repo or show console log errors of helmet not working with Scalar & NestJS? :) 

<img width="637" alt="image" src="https://github.com/scalar/scalar/assets/6176314/49645e4a-ed75-401c-8d78-8e85a670f35f">

<img width="1512" alt="image" src="https://github.com/scalar/scalar/assets/6176314/f8973264-4978-4bda-8283-b08b753a6030">

**Comment by emmanuelvr** [comment]
Hi @marclave! Thanks a lot for looking into this.

In my case, whenever I enable `helmet` and try to access the `/reference` endpoint, I see this error in my browser's console:
`Refused to load the script 'https://cdn.jsdelivr.net/npm/@scalar/api-reference' because it violates the following Content Security Policy directive: "script-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.`

And then the screen just remains white. I thought that having CORS enabled might have to do with the issue, but only Helmet seems to affect the website.

**Comment by marclave** [comment]
@emmanuelvr are you using it with express or fastify?

https://docs.nestjs.com/security/helmet

It looks like its related to the CSP issue in this guide, you will probably need to add the following :) 

```
await app.register(fastifyHelmet, {
   contentSecurityPolicy: {
     directives: {
       defaultSrc: [`'self'`, 'unpkg.com'],
       styleSrc: [
         `'self'`,
         `'unsafe-inline'`,
         'cdn.jsdelivr.net',
         'fonts.googleapis.com',
         'unpkg.com',
       ],
       fontSrc: [`'self'`, 'fonts.gstatic.com', 'data:'],
       imgSrc: [`'self'`, 'data:', 'cdn.jsdelivr.net'],
       scriptSrc: [
         `'self'`,
         `https: 'unsafe-inline'`,
         `cdn.jsdelivr.net`,
         `'unsafe-eval'`,
       ],
     },
   },
 });
```

let me know if that works ✨

**Comment by emmanuelvr** [comment]
That solved the issue!! Thanks a lot @marclave. I'm using Express, so I had to combine your suggestion and the Express step. It looks like this:

```typescript
app.use(
    helmet({
      crossOriginEmbedderPolicy: false,
      contentSecurityPolicy: {
        directives: {
          defaultSrc: [`'self'`, 'unpkg.com'],
          styleSrc: [
            `'self'`,
            `'unsafe-inline'`,
            'cdn.jsdelivr.net',
            'fonts.googleapis.com',
            'unpkg.com',
          ],
          fontSrc: [`'self'`, 'fonts.gstatic.com', 'data:'],
          imgSrc: [`'self'`, 'data:', 'cdn.jsdelivr.net'],
          scriptSrc: [
            `'self'`,
            `https: 'unsafe-inline'`,
            `cdn.jsdelivr.net`,
            `'unsafe-eval'`,
          ],
        },
      },
    }),
  );
```

**Comment by marclave** [comment]
Amazing! Glad to hear it all works @emmanuelvr ✨

**Comment by artsiommiksiuk** [comment]
For those who facing issue with fonts loading and CSR, in the solution above, replace ```fonts.gstatic.com``` to ```fonts.scalar.com```.

**Comment by iampato** [comment]
> That solved the issue!! Thanks a lot @marclave. I'm using Express, so I had to combine your suggestion and the Express step. It looks like this:
> 
> ```ts
> app.use(
>     helmet({
>       crossOriginEmbedderPolicy: false,
>       contentSecurityPolicy: {
>         directives: {
>           defaultSrc: [`'self'`, 'unpkg.com'],
>           styleSrc: [
>             `'self'`,
>             `'unsafe-inline'`,
>             'cdn.jsdelivr.net',
>             'fonts.googleapis.com',
>             'unpkg.com',
>           ],
>           fontSrc: [`'self'`, 'fonts.gstatic.com', 'data:'],
>           imgSrc: [`'self'`, 'data:', 'cdn.jsdelivr.net'],
>           scriptSrc: [
>             `'self'`,
>             `https: 'unsafe-inline'`,
>             `cdn.jsdelivr.net`,
>             `'unsafe-eval'`,
>           ],
>         },
>       },
>     }),
>   );
> ```

This should be added to the documentation

**Comment by MertcanYuzer** [comment]
This should be in documentation, this is hard to find with github search.

**Comment by kieraneglin** [comment]
Here's how to get it working on Rails:

```ruby
class DocsController < ApplicationController
  before_action :allow_inline_styles_without_nonce, only: :index

  content_security_policy do |policy|
    policy.style_src(*policy.style_src, :unsafe_inline)
  end

  def index
    # ...
  end

  private

  def allow_inline_styles_without_nonce
    request.content_security_policy_nonce_directives = ["script-src"]
  end
end
```
