### ISSUE TITLE
Persist REST API Client Modal State [DOC-1432]

### ISSUE THREAD

**Issue by marclave** [scalar/scalar#735]
### Expected Behavior

when you close the api client modal, the request history and inputs should be kept :)

Source: [https://github.com/elysiajs/elysia-swagger/pull/85#pullrequestreview-1803686282](https://github.com/elysiajs/elysia-swagger/pull/85#pullrequestreview-1803686282)

### Actual Behavior

you lose the work + state

### Reproduction steps

```
1. load petstore
2. click test request
3. modify any parameter or body
4. close the client modal
5. open the client modal with the test request button
6. work is lost
```

### Link to site / OpenAPI Spec

*No response*

### Version

latest

### What browsers are you seeing the problem on?

*No response*

<sub>From [SyncLinear.com](https://synclinear.com) | [DOC-1432](https://linear.app/api-docs/issue/DOC-1432/persist-rest-api-client-modal-state)</sub>

**Comment by marclave** [comment]
@abhisheksoni27 we are currently doing some big work on the new API Client, so this work will be bundled inside of that!

in the meantime i will see if there's a short term fix we can do but will keep you updated nonetheless :)

**Comment by hanspagel** [comment]
Done already!
