### ISSUE TITLE
[DOC-1434] Add Fetch to JavaScript http snippets

### ISSUE THREAD

**Issue by marclave** [scalar/scalar#737]
### Expected Behavior

Fetch is an option

### Actual Behavior

No fetch 

### Reproduction steps

```bash
load petstore on latest scalar
```

### Version

latest

<sub>[DOC-1434](https://linear.app/api-docs/issue/DOC-1434/add-fetch-to-javascript-http-snippets)</sub>

**Comment by hanspagel** [comment]
Already in snippetz :) Just need to update and add it.
