### ISSUE TITLE
Ctrl K -> select doesn't scroll to appropriate place

### ISSUE THREAD

**Issue by pq43** [scalar/scalar#755]
### Expected Behavior

When I Ctrl K / search and select a route, I expect it to scroll / jump to that route

### Actual Behavior

It doesn't, so I have to manually scrolldown

### Reproduction steps

```bash
1. Ctrl K or click search
2. Click on any endpoint
3. Notice scroll doesn't happen
```

### Version

"@scalar/api-client": "0.8.3"

### What browsers are you seeing the problem on?

Chrome

**Comment by marclave** [comment]
hey @pq43, i noticed this happens when an endpoint is in a tag that is collapsed, is this what you are seeing as well?

**Comment by pq43** [comment]
H, yes I think that's it! Would be really nice to be able to ctrl k any endpoint tho :)

**Comment by pq43** [comment]
Thank you so much! working with you all through open source has been a joy :)
