### ISSUE TITLE
Body schema properties description doesnt show as markdown

### ISSUE THREAD

**Issue by Lumca** [scalar/scalar#756]
### Expected Behavior

OAS supports markdown in the properties description.

### Actual Behavior

The properties description doesnt show as markdown.
![image](https://github.com/scalar/scalar/assets/4989415/a17455f6-5a62-4bd6-88ed-beaf6cf0e74a)

Can be seen in redocly
![image](https://github.com/scalar/scalar/assets/4989415/39eb1309-247e-4b94-90c0-1911276ef733)

### Reproduction steps

```bash
"api": {
"type": "object",
"properties": {
"limit": {
"type": "integer",
"description": "How many maximum number of matching items should be returned in `rows`.",
"format": "int64",
"nullable": true,
"example": 10
}
```

### Version

latest

### What browsers are you seeing the problem on?

Chrome

**Comment by marclave** [comment]
thanks for reporting this @Lumca! let's fix this 😎

**Comment by marclave** [comment]
@Lumca the fix is in the release `@scalar/api-reference@1.12.9`

**Comment by Lumca** [comment]
Awesome, thanks for letting me know @marclave 👍🏻
