### ISSUE TITLE
Inline Codeblock for description doesn't work for Body in POST. But it works for Query in GET.

### ISSUE THREAD

**Issue by Blankeos** [scalar/scalar#766]
### Expected Behavior

I'm using ElysiaJS to generate my docs with Scalar. So far it's been fantastic! But there's definitely a few rough edges to polish when compared to Swagger. Do let me know if it's a good idea though.

My expected behavior is that when I use the `` ` `` character, it would turn the characters inside just like an inline codeblock on markdown. I tend to use a lot of Inline Codeblocks to help readers read specific things easier. e.g. `Default: 20,000`

### Actual Behavior

![image](https://github.com/scalar/scalar/assets/38070918/14128fef-e93c-4b2b-9dcf-44fa9a451bc1)

### Reproduction steps

```ts
// 1. 🟢 Sample query for what works:
app.get(
  "/",
  async ({ query}) => {},
  {
    query: t.Object({
        property: t.Optional(
          t.Numeric({
            description:
              "This works `Default: 20,000`.",
          })
        ),
      }),
  }
);
```

```ts
// 2. 🔴 Sample query for what doesn't work:
app.post(
  "/",
  async ({ body}) => {},
  {
    body: t.Object({
        property: t.Optional(
          t.Numeric({
            description:
              "This doesn't work. `Default: 20,000`.",
          })
        ),
      }),
  }
);
```

### Version

I'm using `@elysiajs/swagger` ^0.8.3. Not sure what version it uses.

### What browsers are you seeing the problem on?

Chrome, Other

**Comment by marclave** [comment]
hi @Blankeos 

thanks for the comment and the kind words, hopefully we can keep smoothing out the rough edges as fast as possible :) 

we actually fixed this issue in #756 and the release of `1.12.9` https://github.com/scalar/scalar/issues/756#issuecomment-1885761969

you should be able to pass in the release version to ElysiaJS to confirm this works, but I will open a pull request to update the version so it's fixed for everyone :)

**Comment by marclave** [comment]
also, I really appreciate the reproduction steps!

**Comment by Blankeos** [comment]
@marclave. Thanks for the quick response! I didn't know this was sort of a duplicate issue haha, sorry! 
Thanks as well for letting me know I can do this on ElysiaJS. Apparently the default [@scalar/api-reference](https://www.npmjs.com/package/@scalar/api-reference) is `'1.12.5'`. Upped it to the version you mentioned and it works now!

![image](https://github.com/scalar/scalar/assets/38070918/bab90d30-862e-4403-af32-22364e76d6c9)

### What I did:
```diff
const app = new Elysia().use(
  swagger({
    path: "/docs",
    exclude: ["/docs", "/docs/json"],
+    scalarVersion: "1.12.9",
  })
);
```

Thanks a bunch! You guys are doing amazing work here!

**Comment by marclave** [comment]
amazing @Blankeos , I also created a PR to get this updated for everyone :) 

https://github.com/elysiajs/elysia-swagger/pull/92

I'll do a better job of updating the packages when we do a release... it is quite frequent so maybe i need to use dependabot. I will chat with https://github.com/saltyaom about the best way to do this :)
