### ISSUE TITLE
Running `parse` from `@scalar/swagger-parser` throws `utils.inherit is not a function` when running in a Vue app.

### ISSUE THREAD

**Issue by vishalbalaji** [scalar/scalar#767]
### Expected Behavior

The `parse` function parses the given the OpenAPI schema and returns the parsed spec.

### Actual Behavior

Throws an error with the following message, available in the browser's console:
`Uncaught TypeError: util.inherits is not a function`

Stackblitz reproduction: https://stackblitz.com/edit/vitejs-vite-akahxy?file=src%2FApp.vue

This issue was brought up by me on Discord and seen by @marclave, opening a ticket here with a reproduction.

### Reproduction steps

```bash
1. Setup the `ssg` example from the `scalar` examples
2. Install `@scalar/swagger-parser`
3. Import `parse` from `@scalar/swagger-parser` run the function on any OpenAPI schema.
4. Open the console to view the error.
```

### Link to site / OpenAPI Spec

https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/petstore.json

### Version

1.12.9

### What browsers are you seeing the problem on?

Chrome, Safari (macOS), Firefox

**Comment by marclave** [comment]
thanks for opening this issue @vishalbalaji , the end of the week got away from me and i slipped making this issue from our convo on discord. sorry about that!

@hanspagel any thoughts on this issue?

**Comment by hanspagel** [comment]
Yeah, this is the similar problem as described in #264. The lib we’re using requires Node polyfills.

#704 would solve this, or an own fork.

**Comment by hanspagel** [comment]
I think we’ll replace the whole package soon. And we can keep track of it in #264, it’s basically the same issue. ✌️
