### ISSUE TITLE
Read-only properties should not show up in the request examples

### ISSUE THREAD

**Issue by federicobond** [scalar/scalar#774]
### Expected Behavior

Properties with `readOnly: true` should not be included in the client payload examples that show up in the right sidebar.

### Actual Behavior

Readonly properties are included in the request payload for the client example requests.

### Reproduction steps

```bash
1. Use Scalar with an OpenAPI schema that contains readOnly properties
2. Scroll down to an operation that specifies a request with readOnly properties
4. Example payload to the right contains readOnly properties
```

### Version

latest

### What browsers are you seeing the problem on?

Firefox

**Comment by hanspagel** [comment]
Thanks for the report, fixed in #782! :)

**Comment by federicobond** [comment]
Thank you!

**Comment by adnweedon** [comment]
I think this might not be fixed - I just spotted this in my own code?
![image](https://github.com/user-attachments/assets/7f38d0a6-5cf5-474b-93be-52ba4266e9c7)

**Comment by federicobond** [comment]
@adnweedon note that this issue is only for the payload in the example requests that appear to the right.

**Comment by JStuve** [comment]
@federicobond I'm experiencing the same issue that @adnweedon reported. Should we open another issue regarding the request documentation? It can be very confusing seeing an `id`, `read-only`, property as part of the request body.

**Comment by federicobond** [comment]
Yes, I agree. I think it merits opening another issue.
