### ISSUE TITLE
securityScheme description field and key aren't displayed

### ISSUE THREAD

**Issue by mrchimp** [scalar/scalar#792]
### Expected Behavior

Maybe this should be a feature request as it's something that the package doesn't do already, but it's something that is in the spec which isn't being displayed in the docs, so that feels like a bug to me.

The Open API spec allows [a `description` attribute](https://swagger.io/specification/#security-scheme-object). I would expect this field to be displayed. It should also allow rendering markdown.

Each scheme will also have a unique key which can be useful for differentiating otherwise similar schemes. I would expect this to be displayed somewhere in the UI, perhaps in the dropdown when picking an authentication type.

### Actual Behavior

The description and key aren't visible.

### Reproduction steps

```bash
Create a spec including like so:


{
  [...]
  "components": {
    "securitySchemes": {
      "MyAuthScheme": {
        "type": "apiKey",
        "description": "Here is some *helpful text*.",
        "name": "Authorization",
        "in": "header"
      }
    }
  }
}
```

Observer that `MyAuthScheme` and `Here is some *helpful text*` aren't displayed in the UI.
```


### Link to site / OpenAPI Spec

_No response_

### Version

1.12.7

### What browsers are you seeing the problem on?

Chrome

**Comment by hanspagel** [comment]
You're right. Addressed in https://github.com/scalar/scalar/pull/793. :)

**Comment by mrchimp** [comment]
Wow, that was quick!

**Comment by flexwie** [comment]
This issue seems to be unfixed still. When pasting this sample into the editor, the description is not rendered.
We are observing the same behaviour with @scalar/docusaurus v0.2.9

```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "Test API",
    "version": "v1.0.0"
  },
  "paths": {
    "/api/example": {
          "get": {
            "tags": [
              "example"
            ],
            "summary": "An example Request",
            "operationId": "GET api/example",
          }
      },
  },
  "components": {
    "securitySchemes": {
          "Bearer": {
            "type": "apiKey",
            "description": "Here is some *helpful text*.",
            "name": "Authorization",
            "in": "header"
          }
      },
    },
  "security": [
    {
      "Bearer": [ ]
    }
  ]
}
```
