### ISSUE TITLE
Expected header x-api-key in curl preview, but got X-Api-Key

### ISSUE THREAD

**Issue by simonharrer** [scalar/scalar#799]
### Expected Behavior

In the curl preview 

```
curl --request GET \
  --url https://api.datamesh-manager.com/api/dataproducts \
  --header 'x-api-key: '
```

### Actual Behavior

In the curl preview 

```
curl --request GET \
  --url https://api.datamesh-manager.com/api/dataproducts \
  --header 'X-Api-Key: '
```

### Reproduction steps

```bash
With an openapi.yaml like this:


components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      description: ...
      in: header
      name: x-api-key
```
```


### Link to site / OpenAPI Spec

https://app.datamesh-manager.com/openapi.yaml

### Version

the latest via CDN

### What browsers are you seeing the problem on?

Chrome

**Comment by hanspagel** [comment]
Thanks for reporting! Isn’t it the same, though?

> According to HTTP specification header names are case-insensitive, so content-type is the same as Content-Type.
https://www.rfc-editor.org/rfc/rfc9110.html#section-5.1-3

**Comment by simonharrer** [comment]
Ah, I was not aware of that. Still, to me, it felt strange that it doesn't reuse the header field name exactly as I specified it. Why change it / capitalize it? But this is probably more a matter of taste/opinion, so closing this.
