### ISSUE TITLE
Arrow on the left panel doesn't expand/shrink the tag routes

### ISSUE THREAD

**Issue by thelinuxlich** [scalar/scalar#805]
### Expected Behavior

When I click on the arrow next to a tag text on the left panel, it should expand/shrink the tagged routes

### Actual Behavior

![image](https://github.com/scalar/scalar/assets/5043/928d329a-4a53-4ad5-a489-4c1b8d91c169)
Clicking on the arrow pointing to the right does nothing

### Reproduction steps

```bash
Click on the arrow next to a tag text on the left panel.
```

### Version

latest

### What browsers are you seeing the problem on?

Chrome

**Comment by marclave** [comment]
@thelinuxlich great catch! this must have been introduced as a regression, will make this an issue and get it fixed asap
