### ISSUE TITLE
Error when scrolling inside Next.js

### ISSUE THREAD

**Issue by ginkcode** [scalar/scalar#835]
### Expected Behavior

Integrate scalar with Next.js with [veaury](https://github.com/devilwjp/veaury)
Things should work fine when scrolling.

### Actual Behavior

After click on any specific link and then scrolling, a bunch of errors throw in the console
<img width="751" alt="Screenshot 2024-01-19 at 8 47 35 PM" src="https://github.com/scalar/scalar/assets/9301098/3c504d1b-6dee-4db5-ba23-cab56d6cbac2">

### Reproduction steps

```bash
1. Go to Api Document page (setup inside Next.js with veaury)
2. Click on any link in the sidebar
3. Scroll up / down
4. See error
```

### Version

1.13.10

### What browsers are you seeing the problem on?

Chrome, Safari (macOS), Firefox

**Comment by amritk** [comment]
hey @ginkcode do you have some example code of your setup? Also which version of Next.js were you using?

**Comment by ginkcode** [comment]
@amritk I'm using Next.js 14
Let me extract a sample to reproduce it

**Comment by ginkcode** [comment]
Here it is
https://github.com/ginkcode/reproduce-scalar-issue

**Comment by amritk** [comment]
Thanks for doing that! I will check it out

**Comment by ginkcode** [comment]
Sounds cool. I’m willing to assist.

**Comment by amritk** [comment]
hey @ginkcode I got a PR up if you want to check it out. You can clone the repo and test out the example if you like

https://github.com/scalar/scalar/pull/854

😄

**Comment by ginkcode** [comment]
Thank so much @amritk 
Now we can skip `veaury` and import ApiReference directly.
But there's still some issues.
The new adapter has peer dependencies with next "^13". So when install this package with Next.js 14 we will see this error
```sh
npm ERR! Found: next@14.1.0
npm ERR! node_modules/next
npm ERR!   next@"14.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer next@"^13" from @scalar/nextjs-api-reference@0.1.0
```

And the exception throwing when scrolling after click any link in the sidebar is still there. I'm not sure this is Scalar or Next issue. Because it seems Next override some behaviors on `window.history` also.

**Comment by hanspagel** [comment]
Oops! Maybe like this: https://github.com/scalar/scalar/pull/865

**Comment by amritk** [comment]
Ah I see the issue @ginkcode we do update the history and use it for highlighting the sidenav + allowing the back button to navigate backwards. I will see what is conflicting on the next side.

**Comment by amritk** [comment]
Alright @ginkcode second try

https://github.com/scalar/scalar/pull/866/files

**Comment by ginkcode** [comment]
Cool @amritk 
I've tested with that branch and it seems the exception is gone.

**Comment by ginkcode** [comment]
Hi @amritk not related to the topic issue.
But I just found with the new adapter `nextjs-api-reference`. ApiReference is always attached to body tag no matter where we define in the component. It doesn't respect component structure.

Btw to @hanspagel 
The right syntax for peer dependencies is `||`, not `|`.
So we need `"next": "^13 || ^14",`
😅

**Comment by amritk** [comment]
Hey @ginkcode so the quick fix to the scrolling issue was to rip the component out and use an API route. This way the next.js client side code doesn't get injected onto the page. The downside is it a standalone page by itself that you have no control over.

However, we will be adding the component back once we figure out a solution to the scrolling issue. I will probably jump on this soon so it shouldn't be too long.

**Comment by ginkcode** [comment]
Got it 👍
