### ISSUE TITLE
Images in Markdown

### ISSUE THREAD

**Issue by hanspagel** [scalar/scalar#850]
It is related to my other [question](https://github.com/scalar/scalar/discussions/781). I want to expand documentation with some static data, like overall architecture diagrams, description of use cases etc. From what I understood I could do it by adding this content as a markdown in  OpenAPI spec file. All headers would be then reflected in the sidebar and navigation/search would work the same way as it were a regular endpoint documentation. If there is another way to extend sidebar with static content, please let me know

_Originally posted by @SebastianBienert in https://github.com/scalar/scalar/discussions/842#discussioncomment-8208154_

**Comment by marclave** [comment]
Fixed in #858
