### ISSUE TITLE
Doesn't generate correct examples  for requests/responses

### ISSUE THREAD

**Issue by 0xdeafbeef** [scalar/scalar#867]
### Expected Behavior

Example values are rendered:)
![image](https://github.com/scalar/scalar/assets/32823131/ad63e22b-6e17-47dd-873a-63a4ad16ff49)

### Actual Behavior

![image](https://github.com/scalar/scalar/assets/32823131/fee74e0b-e7f3-4739-9bed-ec2674dcb051)
![image](https://github.com/scalar/scalar/assets/32823131/fbab4147-c76f-4f6e-868f-4a4d632a099f)

### Reproduction steps

```bash
Grab swagger from [swagger](https://github.com/KappaShilaff/scalar_issue/blob/main/swagger.yaml) or

cd $(mktemp -d)
git clone https://github.com/KappaShilaff/scalar_issue.git
cd scalar_issue
cargo run
```
open [scalar](http://127.0.0.1:9000/v1/docs#tag/issue/[post]/scalar/issue).

It doesn't render the proper example value, neither in the request nor in the response.
```


### Link to site / OpenAPI Spec

https://raw.githubusercontent.com/KappaShilaff/scalar_issue/main/swagger.yaml

### Version

latest hosted on https://docs.scalar.com/swagger-editor or shipped with aide

### What browsers are you seeing the problem on?

Chrome, Firefox

**Comment by marclave** [comment]
thanks for reporting this @0xdeafbeef ! Will investigate and see what's going on ✨

**Comment by 0xdeafbeef** [comment]
@marclave 
I've found the issue :) Substituting 'examples' with 'example' fixes the problem...
Maybe the issue is deeper

**Comment by 0xdeafbeef** [comment]
> @marclave I've found the issue :) Substituting 'examples' with 'example' fixes the problem... Maybe the problem is deeper

Unfortunately, a quick hack won't work because the examples are an array. However, recursively converting examples with only one item to an example as an object does work:)

**Comment by hanspagel** [comment]
Thanks for reporting! I tried to come up with a solution in #869. :)
