### ISSUE TITLE
patch label in sidebar is wrapper

### ISSUE THREAD

**Issue by sbdchd** [scalar/scalar#871]
### What happens?

<img width="272" alt="image" src="https://github.com/scalar/scalar/assets/7340772/0867e6c1-49a0-4035-92ab-9095d6447cd9">

### What did you expect to happen?

no wrapping

### How can we reproduce the issue?

seems like it's reproducible on the default swagger editor setup

### Swagger/OpenAPI Example

https://sandbox.scalar.com/e/N2Uai

**Comment by hanspagel** [comment]
This doesn’t really happy for me on macOS, but font rendering is complex. I tried to improve the styling in #872. Are you able to check out the branch and test it? This is how you can 

1. git@github.com:scalar/scalar.git
2. cd scalar
3. git checkout style/no-wrap-for-method-badges
4. pnpm install
5. make up
6. http://localhost:5050/api-reference
