### ISSUE TITLE
wrong proxy response

### ISSUE THREAD

**Issue by hanspagel** [scalar/scalar#925]
Is this expected behavior? I'm using the same Swagger doc and getting 2 different response outputs:

<img width="1448" alt="Screenshot 2024-02-01 at 1 48 44 PM" src="https://github.com/scalar/scalar/assets/14568/1973acaa-08ac-4b11-9d82-9489f80702ac">
<img width="1451" alt="Screenshot 2024-02-01 at 1 51 45 PM" src="https://github.com/scalar/scalar/assets/14568/847b5662-ace8-40fb-af57-2c42146d59b3">

_Originally posted by @paulmeller in https://github.com/scalar/scalar/discussions/921_

**Comment by hanspagel** [comment]
This was probably fixed when we rolled back the changes to the proxy, would you mind to test it again? @paulmeller

**Comment by paulmeller** [comment]
It seems to be working now. Thanks.
