### ISSUE TITLE
Better control over the list of clients

### ISSUE THREAD

**Issue by mrchimp** [scalar/scalar#930]
### What happens?

This comes from [this discussion](https://github.com/scalar/scalar/discussions/807). Raising it as an issues as it is a blocker for me.

In short, a lot of clients/languages are listed as icons and in dropdown lists which might not appropriate for a given project and the options available don't allow removing them.

### What did you expect to happen?

- Allow maintaining a list of clients to _include_
- Make client names unique so that they can be targeted accurately
- Allow filtering clients icons

### How can we reproduce the issue?

See above

**Comment by hanspagel** [comment]
See https://github.com/scalar/scalar/discussions/976

**Comment by hanspagel** [comment]
Relevant PR #1250

**Comment by mrchimp** [comment]
Much appreciated!
