### ISSUE TITLE
Do not include properties with unknown values in generated code

### ISSUE THREAD

**Issue by pontus-eliason** [scalar/scalar#933]
### What happens?

When request body is generated, it includes properties that are not required and have no examples values. So it include these as `""` (empty string) if the type is string.

### What did you expect to happen?

It should not include these properties, since it is very likely that an empty string is invalid. It also feels unnecessary to include these, since they are after all not required.

### How can we reproduce the issue?

Create a schema with three string type properties, 

(A) with an example value and being required .
(B) without an example and not being required.
(C) with an example and not being required.

A and C should be included in generated request, B should not.

**Comment by hanspagel** [comment]
I think you’re so right. Let me tackle this.

**Comment by hanspagel** [comment]
This is way more complex than expected. 😆  But I’m on it.
