### ISSUE TITLE
Option ` servers: [{ url: "v1" }]` generate bad request

### ISSUE THREAD

**Issue by hapaxlife** [scalar/scalar#937]
### What happens?

When we add the option ` servers: [{ url: "v1" }]`, the request doesn't add the basepath of url (localhost or https://mysite.com)

In the console, the request is :
`http://v1/hello/Peter`

### What did you expect to happen?

the correct request is :
`http://locahost:8000/v1/hello/Peter`

### How can we reproduce the issue?

in openapi.json
```
{
  "openapi": "3.1.0",
  "info": {
    "version": "1.0.0",
  },
  "tags": [
    {
      "name": "foo",
      "description": "foo API Endpoints"
    }
  ],
  "servers": [
    {
      "url": "v1"
    }
  ],
```

### Swagger/OpenAPI Example

https://sandbox.scalar.com/e/y1nlJ

**Comment by marclave** [comment]
@hapaxlife thanks for making this issue!


I think we should check if it's a valid URL, and if it's a path we append it to the window origin, thoughts @hanspagel  @hapaxlife ? :)

**Comment by bigmike36c** [comment]
Not sure if I should create a new issue, but this change results in issues where the protocol is also parameterized. For example, here is the `servers` property in our openAPI spec:
<img width="776" alt="Screenshot 2024-02-14 at 9 37 52 PM" src="https://github.com/scalar/scalar/assets/81941044/a479e7bd-e382-4ddd-9810-c3d42f265a0d">

This results in Scalar generating broken URLs such as `http://127.0.0.1:3000/https://localhost:8083/management/v2/environments/{envId}/apis`.
