### ISSUE TITLE
Failed to install @scalar/nextjs-api-reference

### ISSUE THREAD

**Issue by yacinelakel** [scalar/scalar#938]
### What happens?

When running `npm install @scalar/nextjs-api-reference` in a new nextjs project (v 14.1.0),  I receive the following error message:

```
# npm resolution error report

While resolving: undefined@undefined
Found: next@14.1.0
node_modules/next
  next@"latest" from the root project

Could not resolve dependency:
peer next@"^13 | ^14" from @scalar/nextjs-api-reference@0.1.14
node_modules/@scalar/nextjs-api-reference
  @scalar/nextjs-api-reference@"*" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.
```

### What did you expect to happen?

Expected to successfully install the package

### How can we reproduce the issue?

1. run `create-next-app` (that uses 14.1.0)
2. run  `npm install @scalar/nextjs-api-reference`

**Comment by hanspagel** [comment]
Oh, looks like the version syntax is wrong. That was my mistake, I’ll take care of it! Thanks for reporting! ✌️
