### ISSUE TITLE
Response body is returning `{}` on requests that don't return `200`

### ISSUE THREAD

**Issue by dromzeh** [scalar/scalar#939]
### What happens?

As discussed on [discord](https://discord.com/channels/1135330207960678410/1135330208627564597/1204433174579515443), when creating a request to a any type (such as Post, Patch, Delete, Get) of route through Scalar's API Reference that doesn't return `200`, the response body is `{}` only, the rest of the response (such as headers) appears as expected. 

Additionally, no errors are reported in the console on the client or through the Hono client, where the API Reference/Documentation is running.

### What did you expect to happen?

The response body should be the response given by the route, as it is listed correctly in the console.
![image](https://github.com/scalar/scalar/assets/65048232/c2eac3c3-d618-4d4d-be41-ef42fc8c1ffc)

### How can we reproduce the issue?

https://github.com/wanderer-moe/api/blob/v2/src/index.ts

**Comment by hwkr** [comment]
This might have to do with the blob changes I did to the proxy, do we know if this is always happening or only when using the proxy?

**Comment by dromzeh** [comment]
> This might have to do with the blob changes I did to the proxy, do we know if this is always happening or only when using the proxy?

This occurs with and without using a proxy.

**Comment by hwkr** [comment]
Hmmmmm okay, so after some testing it seems like this happens because axios likes to throw an error when it receives a non-200 status code and we weren't handling the data from that correctly.

It shouldn't have been happening when using a proxy (since the proxy always returns 200 and puts the proxied responses status code in a special header). I also wasn't able to replicate the issue when using the proxy.

I have a fix up in #955

**Comment by dromzeh** [comment]
> Hmmmmm okay, so after some testing it seems like this happens because axios likes to throw an error when it receives a non-200 status code and we weren't handling the data from that correctly.
> 
> It shouldn't have been happening when using a proxy (since the proxy always returns 200 and puts the proxied responses status code in a special header). I also wasn't able to replicate the issue when using the proxy.
> 
> I have a fix up in #955

Ah yeah, I see - thank you so much for releasing such a quick fix! Now I think of it, proxy issues were most likely on my side as I am running the documentation within a fairly isolated environment. I will update on this issue when the PR is merged and then re-test with/without proxy 😸
