### ISSUE TITLE
background color in language picker select has poor contrast with font

### ISSUE THREAD

**Issue by geoffgscott** [scalar/scalar#958]
### What happens?

The language picker background colour does not seem to respect dark mode.

### What did you expect to happen?

 Should be explicitly set for dark mode to provide cross-platform compatibility. 

![Screenshot_20240208_084141](https://github.com/scalar/scalar/assets/59206100/7e950035-be70-46c6-ad1a-53677c4280b0)

### How can we reproduce the issue?

1. Select language picker dropdown in dark mode in linux or windows
2. See background

**Comment by hwkr** [comment]
Alright so I tested in Chrome, Chromium, Edge and Firefox on Windows (with the Windows theme set to both light and dark mode) and wasn't able to replicate the issue. I wasn't able to test on Linux as I don't have a Linux machine but it's possible it's a Linux only issue?

## Chromium

![chrome_bpXlqMGJIV](https://github.com/scalar/scalar/assets/6374090/934624f6-9a5e-4ef8-a4e2-b42cd8a5fca9)
![chrome_XFCInl75TP](https://github.com/scalar/scalar/assets/6374090/271cf481-a7d7-4f1a-a765-cff517aa251e)

## Firefox

![firefox_6T9MXU6MS4](https://github.com/scalar/scalar/assets/6374090/43d8dae6-83ba-4c29-bfed-caec490c6a4c)
![firefox_vALLzhW8EI](https://github.com/scalar/scalar/assets/6374090/ae4e1af9-9fc1-45fd-b2c2-b7cd06895e0d)

## Edge

![msedge_tLGvP8rX9b](https://github.com/scalar/scalar/assets/6374090/f6e3b61d-d1c1-4f44-92d3-835545485f78)
![msedge_PR7veSHgk1](https://github.com/scalar/scalar/assets/6374090/00fef631-14d9-42d3-bcd1-053d1de5dda5)

**Comment by hanspagel** [comment]
I’ve just tried to find a way to quickly spin up a linux VM on macOS, and this is really good. You just need to make sure to donwload the ARM images, the x86 images are too slow to be usable on my M1:

https://mac.getutm.app/

Unfortunately, it took me already way to long to get to this screen:

<img width="548" alt="Screenshot 2024-02-22 at 13 13 50" src="https://github.com/scalar/scalar/assets/1577992/ccda63b7-6912-41d7-89d2-d70c97536544">

@geoffgscott I think we need some more information here. :)
