### ISSUE TITLE
Body is empty when 400 code occurs

### ISSUE THREAD

**Issue by chlorophant** [scalar/scalar#966]
### What happens?

Using:
"@scalar/express-api-reference": "0.2.46"

When an endpoint is called and it returns a 400 (and presumably other error status codes) the body always shows as an empty object despite response data being returned.

### What did you expect to happen?

The response from the service should be shown

### How can we reproduce the issue?

0. Create an express endpoint which returns a 400 and a non-empty body
1. Create a corresponding openapi spec
2. Load it into scalar on service start
3. Goto the reference page in the browser
4. Make a request to the endpoint using the reference page in the browser
5. Note the empty body response "{}"

**Comment by amritk** [comment]
@hwkr is this something you fixed?

**Comment by hwkr** [comment]
Yeah I mean this seems like the issue that #955 fixed

**Comment by marclave** [comment]
our express package at 0.2.46 is latest and includes the fix so we should investigate :) 

I appear to be getting this issue locally on latest main in scalar

**Comment by hwkr** [comment]
> our express package at 0.2.46 is latest and includes the fix so we should investigate :)
> 
> I appear to be getting this issue locally on latest main in scalar

Yeah I was just looking at that, welp

**Comment by hwkr** [comment]
Hmmmm, my 200 requests in the test harness aren't working either, I'll have a look 😅 

<img width="1330" alt="Google Chrome-2024-02-08-17-09-12@2x" src="https://github.com/scalar/scalar/assets/6374090/47fd7efc-9a55-4407-908d-3d340f3e8d43">

**Comment by hwkr** [comment]
Okay we rolled back some changes in #970 to the api client proxy which should have fixed this.
