### ISSUE TITLE
styling issues in React/Tailwind project

### ISSUE THREAD

**Issue by hanspagel** [scalar/scalar#975]
Hi,

so far I am happy how this project looks like, however it seems that the search box isnt looking the way it should. I am using firefox (edit: looks the same in chromium).
![Screenshot from 2024-02-09 08-33-48](https://github.com/scalar/scalar/assets/11553694/272ac79c-6cc4-4496-9cb7-cad25889c7a6)

I am not sure if its a bug or some side effect of the rest of my page. I am using veaury as described to make scalar work with the react stuff. Below is the code how I use the ApiReference.

`const ApiDocumentationContainer = ({ specUrl }) => {
	return (
		<div className="prefix-px-8">
			<ApiReference configuration={{ spec: {url: specUrl} }} />
		</div>
	)
}`

This is the span in the browser.
![Screenshot from 2024-02-09 08-42-37](https://github.com/scalar/scalar/assets/11553694/2b8d41ba-938d-4e68-855f-08da721b320c)

Maybe someone has an idea what happens to the search field...please let me know if further information is required.

_Originally posted by @juliusjoosten in https://github.com/scalar/scalar/discussions/973_

**Comment by juliusjoosten** [comment]
@hanspagel thank you for accepting this as a bug. In the meanwhile I had a deeper check with the help of one of my colleagues and it turns out that if we overwrite some CSS it shows which values seem to be wrongly setup.

If I add this CSS:
```
.sidebar-search-placeholder {
	background: transparent;
	border: none;
}
```
The result looks like this:
![Screenshot from 2024-02-09 14-34-38](https://github.com/scalar/scalar/assets/11553694/5cb95c9c-42ce-446f-a3bb-83156a9da162)

Which is still not the original idea I guess, but works for now.

**Comment by hwkr** [comment]
Hi @juliusjoosten! Do you have a link to a live site / reproduction where you're seeing the issue? I'm guessing it's something targeting `type="text"` but setting `appearance: none` like you have in the above screenshot doesn't reproduce the issue for me.

<img width="1509" alt="Google Chrome-2024-02-09-13-31-21@2x" src="https://github.com/scalar/scalar/assets/6374090/a772710c-1367-4fac-936f-80748f361e8f">

**Comment by hwkr** [comment]
@juliusjoosten can you try in the inspector just deleting the `type="text"` off of the `<span class="sidebar-search-placeholder" ...` element? I've opened a PR (#980) to that does that which I'm hoping fixes your issue.

**Comment by juliusjoosten** [comment]
Hi @hwkr thanks a lot for taking care of this, and sorry for late reply. The project is not released yet, so I cant provide a public link.
However, your suggestion works! :)
See screenshots: I removed the type attribute and it looks now like below.

![Screenshot from 2024-02-12 08-05-28](https://github.com/scalar/scalar/assets/11553694/8d1182e6-1af7-43c1-a38a-d0a89b44677d)
![Screenshot from 2024-02-12 08-05-37](https://github.com/scalar/scalar/assets/11553694/888da38c-df7d-404e-9868-37ca3d194502)

**Comment by hwkr** [comment]
> Hi @hwkr thanks a lot for taking care of this, and sorry for late reply. The project is not released yet, so I cant provide a public link.
> 
> However, your suggestion works! :)
> 
> See screenshots: I removed the type attribute and it looks now like below.
> 
> 
> 
> ![Screenshot from 2024-02-12 08-05-28](https://github.com/scalar/scalar/assets/11553694/8d1182e6-1af7-43c1-a38a-d0a89b44677d)
> 
> ![Screenshot from 2024-02-12 08-05-37](https://github.com/scalar/scalar/assets/11553694/888da38c-df7d-404e-9868-37ca3d194502)
> 
> 

@juliusjoosten Awesome! I have a fix that should be released soon for you 😊

**Comment by juliusjoosten** [comment]
Using 1.15.6 now and it looks fine. Thanks a lot for fast reaction!
