### ISSUE TITLE
if the client returns a really long body it overflows the viewport 

### ISSUE THREAD

**Issue by hanspagel** [scalar/scalar#997]
Looks good to me! The if the client returns a really long body it seems to kind of overflow the viewport but the same behaviour exists on main.

@marclave @cameronrohani is this what we want or should we have some sort of max height?

https://github.com/scalar/scalar/assets/6374090/f6f3a974-07ab-4e27-8043-589e80a71a42

_Originally posted by @hwkr in https://github.com/scalar/scalar/pull/996#pullrequestreview-1878743595_

**Comment by marclave** [comment]
@hanspagel let's do max height :)

**Comment by hanspagel** [comment]
Fixed in #1022 🎉
